window.P24 = window.P24 || {};
window.P24.lazyComponents = ["player","viewer"];
/* Prototype 24 · js/p24-home.js — generated by tools/assemble.cjs from tools/pages.json; do not edit. */

(function (w, d) {
  'use strict';

  var h = d.documentElement;
  var MQ_MOTION = '(prefers-reduced-motion: no-preference)';
  var MQ_REDUCE = '(prefers-reduced-motion: reduce)';
  var MQ_MOBILE = '(max-width: 760px)';
  var EASE = Object.freeze({ out: 'expo.out', inOut: 'power3.inOut', ui: 'power2.out', window: 'cubic-bezier(.65,0,.35,1)', page: 'cubic-bezier(.16,1,.3,1)' });
  var FLIP_SRC = 'vendor/Flip.min.js';
  var MOBILE_FACTOR = 0.85;
  var SKIP_TO_END_S = 0.25;

  var P24 = w.P24 = w.P24 || {};
  var units = [];
  var components = [];
  var finals = [];
  var errors = P24.errors = P24.errors || [];
  var qa = h.classList.contains('qa');

  function mq(q) { return w.matchMedia(q).matches; }
  function toArray(x) {
    if (!x) return [];
    if (x.nodeType === 1) return [x];
    return Array.prototype.slice.call(x);
  }
  function timeout(ms, value) { return new Promise(function (resolve) { setTimeout(function () { resolve(value); }, ms); }); }
  function report(id, err) {
    errors.push({ unit: id, message: String(err && err.message || err) });
    setTimeout(function () { throw err; }, 0);
  }

  function own(els) { toArray(els).forEach(function (el) { el.classList.add('m-owned'); }); }

  function fontsReady(ms) {
    if (!d.fonts || !d.fonts.load) return Promise.resolve(true);
    return Promise.race([
      d.fonts.load('600 1em Eczar').then(function () { return true; }, function () { return false; }),
      timeout(ms == null ? 500 : ms, false)
    ]);
  }
  function whenLoaded(img) {
    if (!img) return Promise.resolve(false);
    if (img.complete && img.naturalWidth) return Promise.resolve(true);
    return new Promise(function (resolve) {
      img.addEventListener('load', function () { resolve(true); }, { once: true });
      img.addEventListener('error', function () { resolve(false); }, { once: true });
    });
  }
  function decodeOne(img) {
    if (!img) return Promise.resolve();
    if (img.decode) return img.decode();
    return whenLoaded(img);
  }
  function decodeAll(imgs, ms) {
    return Promise.race([
      Promise.all(toArray(imgs).map(decodeOne)).then(function () { return true; }, function () { return false; }),
      timeout(ms == null ? 600 : ms, false)
    ]);
  }
  function lite() {
    var c = w.navigator.connection;
    if (!c) return false;
    return !!c.saveData || /^(slow-2g|2g|3g)$/.test(c.effectiveType || '');
  }

  var flipPromise = null;
  function loadFlip() {
    if (w.Flip && w.gsap) { w.gsap.registerPlugin(w.Flip); return Promise.resolve(w.Flip); }
    if (flipPromise) return flipPromise;
    flipPromise = new Promise(function (resolve, reject) {
      var s = d.createElement('script');
      s.src = FLIP_SRC;
      s.async = true;
      s.onload = function () {
        if (!w.Flip || !w.gsap) { reject(new Error('Flip failed to load')); return; }
        w.gsap.registerPlugin(w.Flip);
        resolve(w.Flip);
      };
      s.onerror = function () { flipPromise = null; reject(new Error('Flip failed to load')); };
      d.head.appendChild(s);
    });
    return flipPromise;
  }

  function onFinal(fn) { if (typeof fn === 'function') finals.push(fn); }

  function enter(el, o) {
    if (!el || !o || typeof o.play !== 'function' || !('IntersectionObserver' in w)) return;
    var state = 'unknown';
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (e) {
        if (state === 'unknown') {
          var below = e.boundingClientRect.top >= (w.innerHeight || h.clientHeight);
          if (!below) { state = 'static'; io.disconnect(); return; }
          state = 'waiting';
          if (o.prepare) o.prepare(el);
          onFinal(function () { if (state === 'waiting') { state = 'done'; io.disconnect(); finish(); } });
          return;
        }
        if (state === 'waiting' && e.isIntersecting) { state = 'done'; io.disconnect(); o.play(el); }
      });
    }, { rootMargin: o.rootMargin || '0px 0px -15% 0px' });
    var jumpTimer = 0;
    function onJump() {
      clearTimeout(jumpTimer);
      jumpTimer = setTimeout(function () {
        if (state !== 'waiting') { w.removeEventListener('scroll', onJump); return; }
        if (el.getBoundingClientRect().bottom <= 0) { state = 'done'; io.disconnect(); w.removeEventListener('scroll', onJump); finish(); }
      }, 150);
    }
    w.addEventListener('scroll', onJump, { passive: true });
    function finish() {
      if (o.final) { o.final(el); return; }
      el.style.opacity = ''; el.style.transform = ''; el.style.clipPath = ''; el.style.visibility = '';
    }
    io.observe(el);
  }

  function runFinals() {
    var g = w.gsap;
    if (g && g.globalTimeline) g.globalTimeline.getChildren(true, true, true).forEach(function (t) { if (t.progress() < 1) t.progress(1); });
    if (d.getAnimations) d.getAnimations().forEach(function (a) { try { if (a.effect && a.effect.getTiming().iterations !== Infinity) a.finish(); } catch (err) { /* not finishable */ } });
    finals.slice().forEach(function (fn) { try { fn(); } catch (err) { report('final', err); } });
  }
  w.addEventListener('beforeprint', runFinals);
  d.addEventListener('beforematch', runFinals, true);

  var MOD_KEY = /^(Shift|Control|Alt|Meta|F\d{1,2})$/;
  function skipOnInput(tl) {
    if (!tl) return function () {};
    var coarse = mq('(pointer: coarse)');
    var startY = w.scrollY;
    var down = null;
    var opt = { passive: true, capture: true };
    var done = false;
    var list = [['keydown', onKey]];
    if (coarse) list.push(['pointerdown', onDown], ['pointerup', onUp]);
    else list.push(['wheel', fire], ['pointerdown', fire], ['scroll', onScroll]);
    function off() {
      if (done) return;
      done = true;
      list.forEach(function (p) { w.removeEventListener(p[0], p[1], opt); });
    }
    function fire() {
      off();
      if (qa) { tl.progress(1); return; }
      var rem = tl.duration() - tl.time();
      if (rem > 0) tl.timeScale(Math.max(tl.timeScale(), rem / SKIP_TO_END_S));
    }
    function onKey(e) { if (!MOD_KEY.test(e.key || '')) fire(); }
    function onScroll() { if (Math.abs(w.scrollY - startY) > 8) fire(); }
    function onDown(e) { down = { x: e.clientX, y: e.clientY, t: e.timeStamp }; }
    function onUp(e) {
      if (!down) return;
      var near = Math.abs(e.clientX - down.x) <= 10 && Math.abs(e.clientY - down.y) <= 10;
      var quick = e.timeStamp - down.t <= 300;
      down = null;
      if (near && quick) fire();
    }
    list.forEach(function (p) { w.addEventListener(p[0], p[1], opt); });
    var prev = tl.eventCallback('onComplete');
    var params = tl.vars && tl.vars.onCompleteParams;
    tl.eventCallback('onComplete', function () { off(); if (prev) prev.apply(tl, params || []); });
    return off;
  }

  var LAZY = {
    player: { sel: 'a[data-clip], button[data-clip]', methods: ['open', 'close', 'isOpen', 'manifest', 'rail', 'hoverPreview'] },
    viewer: { sel: 'a[data-view]', methods: ['open', 'close'] }
  };
  var lazyNames = (P24.lazyComponents || []).filter(function (n) { return !!LAZY[n]; });
  var lazyLoads = {};
  var lazyReady = {};
  function findComponent(name) {
    for (var i = 0; i < components.length; i++) if (components[i].name === name) return components[i];
    return null;
  }
  function loadComponent(name) {
    if (lazyLoads[name]) return lazyLoads[name];
    lazyLoads[name] = new Promise(function (resolve, reject) {
      var s = d.createElement('script');
      s.src = 'js/components/' + name + '.js';
      s.async = true;
      s.onload = function () {
        var c = findComponent(name);
        if (!c) { reject(new Error('component ' + name + ' did not register')); return; }
        var api = c.factory(P24.ctx || makeCtx(h.classList.contains('js-motion')));
        if (P24.ctx) P24.ctx[name] = api;
        resolve(api);
      };
      s.onerror = function () { lazyLoads[name] = null; reject(new Error('component ' + name + ' failed to load')); };
      d.head.appendChild(s);
    });
    return lazyLoads[name];
  }
  function proxy(name) {
    var p = { lazy: true };
    LAZY[name].methods.forEach(function (m) {
      p[m] = function () {
        var a = arguments;
        return loadComponent(name).then(function (api) { return api[m].apply(api, a); });
      };
    });
    return p;
  }
  lazyNames.forEach(function (name) {
    var sel = LAZY[name].sel;
    d.addEventListener('click', function (e) {
      if (lazyReady[name]) return;
      var t = e.target.closest && e.target.closest(sel);
      if (!t || e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
      e.preventDefault();
      loadComponent(name).then(function (api) { api.open(t); }, function () { if (t.href) w.location.href = t.href; });
    });
    var warm = function (e) {
      if (lazyReady[name] || !e.target.closest || !e.target.closest(sel)) return;
      loadComponent(name).catch(function () { /* retried on click */ });
    };
    d.addEventListener('pointerover', warm, { passive: true });
    d.addEventListener('focusin', warm);
    d.addEventListener('touchstart', warm, { passive: true });
  });
  if (lazyNames.length) {
    w.addEventListener('load', function () {
      setTimeout(function () { lazyNames.forEach(function (n) { loadComponent(n).catch(function () { /* on demand */ }); }); }, 4000);
    }, { once: true });
  }

  function makeCtx(motionOK) {
    var mobile = mq(MQ_MOBILE);
    var ctx = {
      gsap: w.gsap || null,
      SplitText: w.SplitText || null,
      motionOK: motionOK,
      mobile: mobile,
      coarse: mq('(pointer: coarse)'),
      qa: qa,
      lite: lite(),
      internalNav: h.classList.contains('vt-nav'),
      m1: { play: !h.classList.contains('m1-skip'), holdName: h.classList.contains('m1-type') },
      ease: EASE,
      dur: function (s) { return mq(MQ_MOBILE) ? s * MOBILE_FACTOR : s; },
      enter: enter,
      loadFlip: loadFlip,
      fontsReady: fontsReady,
      decodeAll: decodeAll,
      whenLoaded: whenLoaded,
      own: own,
      onFinal: onFinal,
      skipOnInput: skipOnInput,
      setIntro: function (intro) { P24.intro = intro || null; },
      vt: {
        internalNav: h.classList.contains('vt-nav'),
        supported: !!(P24._vt && P24._vt.supported),
        name: function (el, n) { if (P24._vt) P24._vt.name(el, n); }
      }
    };
    ctx.reveal = function (els, opts) { return P24._reveal ? P24._reveal(ctx, els, opts || {}) : undefined; };
    ctx.heading = function (el, opts) { return P24._type ? P24._type.heading(ctx, el, opts || {}) : undefined; };
    ctx.roll = function (el, text) {
      if (P24._type) return P24._type.roll(ctx, el, text);
      if (el) el.textContent = text;
      return undefined;
    };
    components.forEach(function (c) {
      try { ctx[c.name] = c.factory(ctx); } catch (err) { report('component:' + c.name, err); }
    });
    lazyNames.forEach(function (n) { if (!ctx[n]) ctx[n] = proxy(n); });
    return ctx;
  }

  function runUnits(motionOK) {
    var ctx = makeCtx(motionOK);
    P24.ctx = ctx;
    var cleanups = [];
    units.forEach(function (u) {
      try {
        var c = u.mod.init(ctx);
        if (typeof c === 'function') cleanups.push(c);
      } catch (err) {
        report(u.id, err);
        h.classList.remove('js-motion');
      }
    });
    return function () { cleanups.forEach(function (c) { try { c(); } catch (err) { report('cleanup', err); } }); };
  }

  P24.register = function (id, mod) {
    if (!id || !mod || typeof mod.init !== 'function') throw new Error('P24.register(id, { init }) expects an init function');
    if (units.some(function (u) { return u.id === id; })) throw new Error('P24.register: duplicate id ' + id);
    units.push({ id: id, mod: mod });
  };
  P24.component = function (name, factory) {
    if (!name || typeof factory !== 'function') throw new Error('P24.component(name, factory) expects a factory');
    if (components.some(function (c) { return c.name === name; })) throw new Error('P24.component: duplicate ' + name);
    components.push({ name: name, factory: factory });
    if (LAZY[name]) lazyReady[name] = true;
  };

  function boot() {
    if (P24.booted) return;
    P24.booted = true;
    var g = w.gsap;
    if (!g) { h.classList.remove('js-motion'); runUnits(false); return; }
    if (w.SplitText) g.registerPlugin(w.SplitText);
    g.config({ autoSleep: 60, nullTargetWarn: false });
    g.defaults({ ease: EASE.out, duration: 0.6 });
    var mm = g.matchMedia();
    P24.mm = mm;
    mm.add({ ok: MQ_MOTION, reduce: MQ_REDUCE }, function (c) {
      var ok = !!c.conditions.ok;
      h.classList.toggle('js-motion', ok);
      return runUnits(ok);
    });
  }

  P24.ease = EASE;
  P24.loadFlip = loadFlip;
  P24.finish = runFinals;

  if (qa) {
    w.__p24 = {
      seek: function (t) {
        var i = P24.intro;
        if (!i || !i.timeline) return false;
        i.timeline.pause();
        i.timeline.seek(Number(t) || 0, false);
        return true;
      },
      state: function () {
        return {
          booted: !!P24.booted,
          motion: h.classList.contains('js-motion'),
          classes: h.className,
          intro: !!P24.intro,
          vtLog: (P24.vtLog || []).slice(),
          errors: errors.slice()
        };
      },
      finish: runFinals
    };
  }

  if (d.readyState === 'loading') d.addEventListener('DOMContentLoaded', boot, { once: true });
  else setTimeout(boot, 0);
})(window, document);

(function (w) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};

  function list(x) {
    if (!x) return [];
    if (x.nodeType === 1) return [x];
    return Array.prototype.slice.call(x);
  }

  function lines(ctx, el, opts) {
    if (ctx.heading) { ctx.heading(el, { rootMargin: opts.rootMargin }); return; }
    var g = ctx.gsap;
    var ST = ctx.SplitText;
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () { g.set(el, { autoAlpha: 0 }); },
      play: function () {
        g.set(el, { autoAlpha: 1 });
        if (!ST) { g.from(el, { y: ctx.mobile ? 12 : 20, autoAlpha: 0, duration: ctx.dur(0.7) }); return; }
        var split = ST.create(el, { type: 'lines', mask: 'lines', linesClass: 'p24-line', aria: 'auto' });
        g.from(split.lines, {
          yPercent: 110,
          duration: ctx.dur(0.7),
          stagger: 0.08,
          ease: ctx.ease.out,
          onComplete: function () { split.revert(); }
        });
      },
      final: function () { g.set(el, { clearProps: 'opacity,visibility' }); }
    });
  }

  function photo(ctx, el, opts) {
    var g = ctx.gsap;
    var frame = el.classList.contains('p24-frame') ? el : el.querySelector('.p24-frame') || el;
    var img = frame.querySelector('img, video');
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () {
        g.set(frame, { clipPath: 'inset(100% 0% 0% 0%)' });
        if (img) g.set(img, { scale: 1.06, transformOrigin: '50% 100%' });
      },
      play: function () {
        var open = function () {
          var d = ctx.dur(0.8);
          g.to(frame, { clipPath: 'inset(0% 0% 0% 0%)', duration: d, ease: ctx.ease.out, clearProps: 'clipPath' });
          if (img) g.to(img, { scale: 1, duration: d, ease: ctx.ease.out, clearProps: 'transform' });
        };
        if (!img || img.tagName !== 'IMG' || !ctx.decodeAll) { open(); return; }
        if (img.loading === 'lazy') img.loading = 'eager';
        ctx.decodeAll([img], 900).then(function (ok) {
          if (ok) { open(); return; }
          g.set(frame, { clearProps: 'clipPath' });
          g.set(img, { clearProps: 'transform' });
        });
      },
      final: function () {
        g.set(frame, { clearProps: 'clipPath' });
        if (img) g.set(img, { clearProps: 'transform' });
      }
    });
  }

  function group(ctx, el, opts) {
    var g = ctx.gsap;
    var kids = Array.prototype.slice.call(el.children);
    if (!kids.length) return;
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () { g.set(kids, { y: ctx.mobile ? 12 : 16, autoAlpha: 0 }); },
      play: function () {
        g.to(kids, {
          y: 0,
          autoAlpha: 1,
          duration: ctx.dur(0.7),
          stagger: opts.stagger == null ? 0.06 : opts.stagger,
          ease: ctx.ease.out,
          clearProps: 'transform,opacity,visibility'
        });
      },
      final: function () { g.set(kids, { clearProps: 'transform,opacity,visibility' }); }
    });
  }

  P24._reveal = function (ctx, els, opts) {
    if (!ctx.motionOK || !ctx.gsap) return;
    var type = opts.type || 'group';
    list(els).forEach(function (el) {
      if (type === 'lines') lines(ctx, el, opts);
      else if (type === 'photo') photo(ctx, el, opts);
      else group(ctx, el, opts);
    });
  };
})(window);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var ROLL_TRAVEL = 8;

  function hasDeva(el) { return !!(el.closest('[lang="hi"]') || el.querySelector('[lang="hi"]')); }

  function rise(ctx, el, done) {
    var g = ctx.gsap;
    var ST = ctx.SplitText;
    var dur = ctx.mobile ? 0.6 : 0.7;
    g.set(el, { autoAlpha: 1 });
    if (!ST || hasDeva(el)) {
      g.from(el, { y: ctx.mobile ? 12 : 20, autoAlpha: 0, duration: dur, ease: ctx.ease.out, clearProps: 'transform,opacity,visibility', onComplete: done });
      return;
    }
    var tween = null;
    var split = ST.create(el, {
      type: 'lines',
      mask: 'lines',
      linesClass: 'p24-line',
      aria: 'auto'
    });
    tween = g.from(split.lines, {
      yPercent: 110,
      duration: dur,
      stagger: 0.08,
      ease: ctx.ease.out,
      onComplete: function () { split.revert(); if (done) done(); }
    });
    return split;
  }

  function heading(ctx, el, opts) {
    if (!el || !ctx.motionOK || !ctx.gsap) return;
    var g = ctx.gsap;
    if (opts.now) {
      if (ctx.internalNav) return;
      if (w.getComputedStyle(el).opacity !== '0') return;
      ctx.own(el);
      rise(ctx, el);
      return;
    }
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () { g.set(el, { autoAlpha: 0 }); },
      play: function () { rise(ctx, el); },
      final: function () { g.set(el, { clearProps: 'opacity,visibility' }); }
    });
  }

  function roll(ctx, el, text) {
    if (!el) return;
    text = text == null ? '' : String(text);
    if (el._p24roll) { el._p24roll.progress(1); el._p24roll = null; }
    var oldText = el.textContent;
    if (oldText === text) return;
    var g = ctx.gsap;
    if (!ctx.motionOK || !g || !el.isConnected || !oldText) { el.textContent = text; return; }
    el.classList.add('p24-roll');
    el.textContent = '';
    var next = d.createElement('span');
    next.className = 'p24-roll__new';
    next.textContent = text;
    var ghost = d.createElement('span');
    ghost.className = 'p24-roll__old';
    ghost.setAttribute('aria-hidden', 'true');
    ghost.textContent = oldText;
    el.appendChild(next);
    el.appendChild(ghost);
    var dur = ctx.dur(0.3);
    el._p24roll = g.timeline({
      onComplete: function () { el.textContent = text; el.classList.remove('p24-roll'); el._p24roll = null; }
    })
      .to(ghost, { y: -ROLL_TRAVEL, autoAlpha: 0, duration: dur * 0.7, ease: 'power2.in' }, 0)
      .from(next, { y: ROLL_TRAVEL, autoAlpha: 0, duration: dur, ease: ctx.ease.ui }, dur * 0.3);
  }

  P24._type = { heading: heading, roll: roll };
})(window, document);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var lastLink = null;
  var NAMES = { 'cta-panel': 1, 'family-hero': 1 };

  function visible(el) {
    if (!el) return false;
    var r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0 && r.bottom > 0 && r.top < w.innerHeight;
  }

  function sourceFor(link, name) {
    if (name === 'cta-panel') return link;
    var sel = link.getAttribute('data-vt-source');
    if (sel) { var s = d.querySelector(sel); if (visible(s)) return s; }
    var node = link.parentElement;
    while (node && node !== d.body) {
      var stages = node.querySelectorAll('[data-story-stage]');
      for (var i = 0; i < stages.length; i++) {
        var win = stages[i].querySelector('.p24-story__window') || stages[i];
        if (visible(win)) return win;
      }
      node = node.parentElement;
    }
    return null;
  }

  function showKeyFrame(link, win) {
    var block = link.closest('[data-story-block]');
    if (!block || !win || !win.classList.contains('p24-story__window')) return;
    var key = block.getAttribute('data-story-key');
    if (!key) { var st = block.querySelector('[data-story-step]'); key = st ? (st.getAttribute('data-story-step') || '').split(/\s+/)[0] : ''; }
    var layer = key ? win.querySelector('.p24-story__layer[data-frame="' + key + '"]') : null;
    if (!layer || !layer.style.width) return;
    var img = layer.querySelector('img');
    if (img && !img.complete) return;
    var all = win.querySelectorAll('.p24-story__layer');
    for (var i = 0; i < all.length; i++) {
      if (all[i].getAnimations) all[i].getAnimations().forEach(function (an) { an.cancel(); });
      if (all[i] !== layer) all[i].classList.remove('is-on', 'is-top');
    }
    if (win.getAnimations) win.getAnimations().forEach(function (an) { an.cancel(); });
    layer.classList.add('is-on');
    layer.style.clipPath = '';
    var area = win.parentElement || win;
    var l = parseFloat(layer.style.left) || 0, t = parseFloat(layer.style.top) || 0;
    var lw = parseFloat(layer.style.width) || 0, lh = parseFloat(layer.style.height) || 0;
    win.style.clipPath = 'inset(' + t + 'px ' + Math.max(0, area.clientWidth - l - lw) + 'px ' + Math.max(0, area.clientHeight - t - lh) + 'px ' + l + 'px)';
  }

  function name(el, n) {
    if (!el || !n) return;
    var prev = d.querySelectorAll('[data-vt-named]');
    for (var i = 0; i < prev.length; i++) {
      if (prev[i].style.viewTransitionName === n) { prev[i].style.viewTransitionName = ''; prev[i].removeAttribute('data-vt-named'); }
    }
    el.style.viewTransitionName = n;
    el.setAttribute('data-vt-named', '');
  }
  function clearAll() {
    var named = d.querySelectorAll('[data-vt-named]');
    for (var i = 0; i < named.length; i++) { named[i].style.viewTransitionName = ''; named[i].removeAttribute('data-vt-named'); }
  }

  d.addEventListener('click', function (e) {
    var a = e.target && e.target.closest ? e.target.closest('a[href]') : null;
    lastLink = a && a.hasAttribute('data-vt') ? a : null;
  }, true);

  w.addEventListener('pageswap', function (e) {
    var vt = e.viewTransition;
    try { w.sessionStorage.removeItem('p24-vt'); } catch (err) { /* storage off: pairs are skipped */ }
    if (!vt) return;
    try {
      clearAll();
      var link = lastLink;
      lastLink = null;
      var entry = e.activation && e.activation.entry;
      if (!link || !entry || link.href !== entry.url) return;
      var n = link.getAttribute('data-vt');
      if (!NAMES[n]) return;
      var src = sourceFor(link, n);
      if (!visible(src)) return;
      if (n === 'family-hero') showKeyFrame(link, src);
      name(src, n);
      w.sessionStorage.setItem('p24-vt', n);
      if (d.documentElement.classList.contains('qa')) {
        var r = src.getBoundingClientRect();
        w.sessionStorage.setItem('p24-vtlog', JSON.stringify({ name: n, source: src.tagName.toLowerCase() + '.' + String(src.className).split(' ')[0], rect: [Math.round(r.left), Math.round(r.top), Math.round(r.width), Math.round(r.height)], url: entry.url }));
      }
    } catch (err) {
      vt.skipTransition();
    }
  });

  w.addEventListener('pageshow', function (e) { if (e.persisted) { clearAll(); lastLink = null; } });

  P24._vt = {
    name: name,
    clear: clearAll,
    internalNav: function () { return d.documentElement.classList.contains('vt-nav'); },
    supported: typeof d.startViewTransition === 'function' && !!w.CSS && CSS.supports('view-transition-name: none')
  };
})(window, document);

(function (w, d) {
  'use strict';
  var h = d.documentElement;
  var body = d.body;
  var hasIO = 'IntersectionObserver' in w;
  function each(sel, fn) { Array.prototype.forEach.call(d.querySelectorAll(sel), fn); }

  var page = body.getAttribute('data-page');
  each('[data-nav]', function (a) {
    if (page && a.getAttribute('data-nav') === page) a.setAttribute('aria-current', 'page');
  });

  var menuBtn = d.querySelector('[data-menu-open]');
  var menu = d.getElementById('p24-menu');
  if (menuBtn && menu && typeof menu.showModal === 'function') {
    var closeBtn = menu.querySelector('[data-menu-close]');
    var setOpen = function (open) {
      if (open && !menu.open) menu.showModal();
      if (!open && menu.open) menu.close();
      menuBtn.setAttribute('aria-expanded', String(open));
    };
    menuBtn.addEventListener('click', function () { setOpen(true); });
    if (closeBtn) closeBtn.addEventListener('click', function () { setOpen(false); });
    menu.addEventListener('close', function () {
      menuBtn.setAttribute('aria-expanded', 'false');
      menuBtn.focus({ preventScroll: true });
    });
    menu.addEventListener('click', function (e) {
      var a = e.target.closest('a');
      if (a && a.getAttribute('href').charAt(0) === '#') setOpen(false);
    });
    var closedOnHide = false;
    var reset = function () {
      menuBtn.setAttribute('aria-expanded', 'false');
      menuBtn.textContent = 'Menu';
      if (menu.open) menu.close();
    };
    w.addEventListener('pagehide', function () { if (menu.open) { closedOnHide = true; reset(); } });
    w.addEventListener('pageshow', function (e) {
      if (!e.persisted) return;
      var was = closedOnHide || menu.open;
      closedOnHide = false;
      reset();
      if (was) menuBtn.focus({ preventScroll: true });
    });
    var mqWide = w.matchMedia('(min-width: 761px)');
    var onWide = function () { if (mqWide.matches) setOpen(false); };
    if (mqWide.addEventListener) mqWide.addEventListener('change', onWide);
  } else if (menuBtn) {
    menuBtn.addEventListener('click', function () { var f = d.getElementById('p24-footer-pages'); if (f) f.scrollIntoView(); });
  }

  var dock = d.querySelector('[data-dock]');
  if (dock && !body.hasAttribute('data-no-dock')) {
    var sentinels = d.querySelectorAll('[data-dock-sentinel]');
    var footerCta = d.querySelector('[data-footer-cta]');
    var state = { sentinel: sentinels.length > 0, footer: false, typing: false };
    d.addEventListener('p24:dock', function () { render(); });
    var links = dock.querySelectorAll('a, button');
    var render = function () {
      var show = !state.sentinel && !state.footer && !state.typing && !h.classList.contains('story-stuck');
      if (show) dock.setAttribute('data-show', ''); else dock.removeAttribute('data-show');
      h.classList.toggle('dock-on', show);
      dock.setAttribute('aria-hidden', String(!show));
      Array.prototype.forEach.call(links, function (l) { l.tabIndex = show ? 0 : -1; });
    };
    if (hasIO && sentinels.length) {
      var seen = new Set();
      var ioS = new IntersectionObserver(function (entries) {
        entries.forEach(function (e) {
          if (e.isIntersecting && e.intersectionRatio >= 0.99) seen.add(e.target); else seen.delete(e.target);
        });
        state.sentinel = seen.size > 0;
        render();
      }, { threshold: [0, 0.99, 1] });
      Array.prototype.forEach.call(sentinels, function (s) { ioS.observe(s); });
    }
    if (hasIO && footerCta) {
      new IntersectionObserver(function (entries) {
        state.footer = entries[0].isIntersecting;
        render();
      }).observe(footerCta);
    }
    d.addEventListener('focusin', function (e) {
      state.typing = !!(e.target.closest && e.target.closest('input, select, textarea'));
      render();
    });
    render();
  }

  each('[data-replay-opening]', function (a) {
    a.addEventListener('click', function (e) {
      if (e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
      e.preventDefault();
      if ('scrollRestoration' in w.history) w.history.scrollRestoration = 'manual';
      w.scrollTo(0, 0);
      w.location.reload();
    });
  });

  if (h.classList.contains('qa')) {
    var qaBox = d.createElement('pre');
    qaBox.className = 'p24-qa';
    qaBox.setAttribute('aria-hidden', 'true');
    var draw = function () {
      var P24 = w.P24 || {};
      var NL = String.fromCharCode(10);
      qaBox.textContent = 'P24 QA · ' + h.className + NL + (P24.vtLog || []).map(function (x) { return JSON.stringify(x); }).join(NL);
    };
    draw();
    body.appendChild(qaBox);
    setTimeout(draw, 1200);
  }
})(window, document);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var DWELL_MS = 150;
  var HOLD_MS = 700;
  var PAIR_HOLD_MS = 900;
  var WINDOW_MS = 500;
  var FADE_MS = 320;
  var SETTLE_MS = 120;
  var RESIZE_MS = 150;
  var EASE_WINDOW = 'cubic-bezier(.65,0,.35,1)';

  function qsa(root, sel) { return Array.prototype.slice.call(root.querySelectorAll(sel)); }
  function shown(el) { return !!el && el.getClientRects().length > 0; }
  function frames(step) { return (step.getAttribute('data-story-step') || '').split(/\s+/).filter(Boolean); }
  function insetOf(box, area) {
    return 'inset(' + box.top + 'px ' + Math.max(0, area.w - box.left - box.w) + 'px ' + Math.max(0, area.h - box.top - box.h) + 'px ' + box.left + 'px)';
  }

  function factory(ctx) {
    return function story(root, opts) {
      if (!root) return { go: function () {}, destroy: function () {} };
      opts = opts || {};
      var motion = ctx.motionOK;
      var blocks = qsa(root, '[data-story-block]');
      var steps = qsa(root, '[data-story-step]');
      var templates = {};
      qsa(root, 'template[data-story-frame]').forEach(function (t) { templates[t.getAttribute('data-story-frame')] = t; });
      var stages = [];
      var label = d.createElement('span');
      label.className = 'p24-inphoto';
      label.textContent = 'In the photo';
      var state = { marker: null, pending: null, frame: null, stage: null, last: 0, token: 0, pairTimer: 0, dwellTimer: 0, settleTimer: 0, resizeTimer: 0, live: false, forced: null };
      var observers = [];
      var offs = [];
      var markers = blocks.map(function (b) { return { el: b, block: b, step: null }; })
        .concat(steps.map(function (s) { return { el: s, block: s.closest('[data-story-block]'), step: s }; }))
        .sort(function (a, b) { return a.el.compareDocumentPosition(b.el) & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1; });

      function on(t, type, fn, o) { t.addEventListener(type, fn, o); offs.push(function () { t.removeEventListener(type, fn, o); }); }
      function vh() { return w.innerHeight || d.documentElement.clientHeight; }
      function lineFraction() {
        if (typeof opts.readingLine === 'number') return opts.readingLine;
        return ctx.mobile ? 0.6 : 0.5;
      }
      function blockOf(el) { return el.closest('[data-story-block]'); }
      function keyOf(block) {
        var k = block.getAttribute('data-story-key');
        if (k) return k;
        var s = block.querySelector('[data-story-step]');
        return s ? frames(s)[0] : null;
      }
      function stepFor(frameId) {
        for (var i = 0; i < steps.length; i++) if (frames(steps[i]).indexOf(frameId) > -1) return steps[i];
        return null;
      }

      function stageRec(el) {
        for (var i = 0; i < stages.length; i++) if (stages[i].el === el) return stages[i];
        var area = el.querySelector('.p24-story__area');
        if (!area) {
          area = d.createElement('div');
          area.className = 'p24-story__area';
          var win = d.createElement('div');
          win.className = 'p24-story__window';
          area.appendChild(win);
          var stat = el.querySelector('[data-story-static]');
          if (stat && stat.parentNode === el) el.insertBefore(area, stat.nextSibling); else el.insertBefore(area, el.firstChild);
        }
        var rec = { el: el, area: area, win: area.querySelector('.p24-story__window'), layers: {}, cur: null, anims: [] };
        stages.push(rec);
        return rec;
      }
      function stageFor(block) {
        var own = block ? qsa(block, '[data-story-stage]').filter(shown)[0] : null;
        if (own) return stageRec(own);
        var shared = qsa(root, '[data-story-stage]').filter(function (s) { return !blockOf(s) && shown(s); })[0];
        return shared ? stageRec(shared) : null;
      }
      function areaSize(st) { return { w: st.area.clientWidth, h: st.area.clientHeight }; }
      function fit(layer, st) {
        var a = areaSize(st);
        var ar = layer.ar;
        var wd = a.w;
        var ht = a.w / ar;
        if (ht > a.h) { ht = a.h; wd = a.h * ar; }
        wd = Math.round(wd);
        ht = Math.round(ht);
        var anchor = opts.anchor || (ctx.mobile ? 'center' : 'bottom-left');
        var box = { w: wd, h: ht, left: anchor === 'center' ? Math.round((a.w - wd) / 2) : 0, top: anchor === 'center' ? Math.round((a.h - ht) / 2) : a.h - ht };
        layer.box = box;
        var s = layer.el.style;
        s.width = wd + 'px';
        s.height = ht + 'px';
        s.left = box.left + 'px';
        s.top = box.top + 'px';
        return box;
      }
      function layerFor(st, id) {
        if (st.layers[id]) return st.layers[id];
        var t = templates[id];
        if (!t) return null;
        var el = d.createElement('div');
        el.className = 'p24-story__layer';
        el.setAttribute('data-frame', id);
        el.appendChild(t.content.cloneNode(true));
        var img = el.querySelector('img');
        if (!img) return null;
        img.loading = 'eager';
        img.decoding = 'async';
        var clip = t.getAttribute('data-clip');
        if (clip) {
          el.setAttribute('data-flip-id', 'story-' + id);
          var play = d.createElement('a');
          play.className = 'p24-play';
          play.href = t.getAttribute('data-clip-href') || ('media/clips/' + clip + '.mp4');
          play.setAttribute('data-clip', clip);
          play.textContent = 'Play clip';
          play.setAttribute('aria-label', 'Play clip: ' + (t.getAttribute('data-caption') || clip));
          var grp = t.getAttribute('data-group');
          if (grp) el.setAttribute('data-group', grp);
          el.appendChild(play);
        }
        var wAttr = +img.getAttribute('width') || 4;
        var hAttr = +img.getAttribute('height') || 3;
        var layer = { id: id, el: el, img: img, ar: wAttr / hAttr, caption: t.getAttribute('data-caption') || '', ready: null, box: null };
        st.win.appendChild(el);
        fit(layer, st);
        layer.ready = img.decode ? img.decode().then(function () { return true; }, function () { return ctx.whenLoaded(img); }) : ctx.whenLoaded(img);
        st.layers[id] = layer;
        return layer;
      }
      function prefetch(block) {
        var st = stageFor(block);
        if (!st) return;
        var ids = [];
        var key = block ? keyOf(block) : null;
        if (key) ids.push(key);
        (block ? qsa(block, '[data-story-step]') : steps).forEach(function (s) { frames(s).forEach(function (f) { if (ids.indexOf(f) < 0) ids.push(f); }); });
        ids.reduce(function (p, id) {
          return p.then(function () { var l = layerFor(st, id); return l ? l.ready : null; });
        }, Promise.resolve());
      }

      function finishAnims(st) { st.anims.forEach(function (a) { try { a.finish(); } catch (e) { /* already done */ } }); st.anims = []; }

      function settle(st, layer, prev) {
        st.win.style.clipPath = insetOf(layer.box, areaSize(st));
        layer.el.style.clipPath = '';
        if (prev && prev !== layer) prev.el.classList.remove('is-on');
        layer.el.classList.remove('is-top');
      }

      function reshape(st, layer, dir) {
        var prev = st.cur;
        finishAnims(st);
        st.cur = layer;
        layer.el.classList.add('is-on');
        if (!motion || !prev || prev === layer || !st.win.animate) { settle(st, layer, prev); return; }
        var a = areaSize(st);
        layer.el.classList.add('is-top');
        var opt = { duration: WINDOW_MS, easing: EASE_WINDOW, fill: 'forwards' };
        var aw = st.win.animate([{ clipPath: insetOf(prev.box, a) }, { clipPath: insetOf(layer.box, a) }], opt);
        var al = layer.el.animate([{ opacity: 0, transform: 'translateY(' + (dir < 0 ? -16 : 16) + 'px)' }, { opacity: 1, transform: 'none' }], { duration: FADE_MS, easing: 'cubic-bezier(.2,0,0,1)', fill: 'forwards' });
        st.anims = [aw, al];
        aw.finished.then(function () {
          if (st.cur !== layer) return;
          settle(st, layer, prev);
          aw.cancel();
          al.cancel();
          st.anims = [];
        }, function () { /* finished early by an interruption: settle() ran there */ });
      }

      function decorate(layer, block) {
        var st = state.stage;
        var cap = st && st.el.querySelector('[data-story-caption]');
        if (cap) ctx.roll(cap, layer.caption);
        var fam = st && st.el.querySelector('[data-story-family]');
        if (fam && block && block.getAttribute('data-story-label')) ctx.roll(fam, block.getAttribute('data-story-label'));
        var row = stepFor(layer.id);
        if (row) (row.querySelector('[data-story-label]') || row).appendChild(label);
        else if (label.parentNode) label.parentNode.removeChild(label);
        steps.forEach(function (s) { s.classList.toggle('is-pictured', s === row); });
        var key = block ? block.getAttribute('data-story-block') : null;
        qsa(root, '[data-story-strip]').forEach(function (strip) { strip.classList.toggle('is-current', !key || strip.getAttribute('data-story-strip') === key); });
        qsa(root, '[data-story-thumb]').forEach(function (t) {
          var strip = t.closest('[data-story-strip]');
          var on = t.getAttribute('data-story-thumb') === layer.id && (!key || (!!strip && strip.getAttribute('data-story-strip') === key));
          t.classList.toggle('is-active', on);
          if (on) t.setAttribute('aria-current', 'true'); else t.removeAttribute('aria-current');
        });
        blocks.forEach(function (b) { b.classList.toggle('is-active', b === block); });
        if (typeof opts.onChange === 'function') opts.onChange({ frame: layer.id, step: row, block: block });
      }

      function goLive(st, layer) {
        if (!state.live) { state.live = true; root.setAttribute('data-story-live', ''); }
        if (!st.el.hasAttribute('data-story-ready')) {
          st.el.setAttribute('data-story-ready', '');
          qsa(st.el, '[data-story-static]').forEach(function (s) { s.hidden = true; });
        }
        fit(layer, st);
        if (st.cur && st.cur !== layer) fit(st.cur, st);
      }

      function show(frameId, block, dir) {
        var st = stageFor(block);
        if (!st || !frameId) return;
        var layer = layerFor(st, frameId);
        if (!layer) return;
        var token = ++state.token;
        layer.ready.then(function (ok) {
          if (token !== state.token || !ok) return;
          state.stage = st;
          state.frame = frameId;
          state.last = Date.now();
          goLive(st, layer);
          reshape(st, layer, dir || 1);
          decorate(layer, block);
        });
      }

      function candidate() {
        var r = root.getBoundingClientRect();
        if (r.bottom <= 0 || r.top >= vh()) return null;
        var line = vh() * lineFraction();
        var pick = null;
        markers.forEach(function (m) { if (m.el.getBoundingClientRect().top <= line) pick = m; });
        if (!pick) pick = markers[0] || null;
        return pick;
      }
      function sameMarker(a, b) { return !!a && !!b && a.el === b.el; }

      function apply(m, dir) {
        clearTimeout(state.pairTimer);
        state.marker = m;
        if (!m) return;
        var ids = m.step ? frames(m.step) : [keyOf(m.block)];
        show(ids[0], m.block, dir);
        if (ids.length > 1) {
          state.pairTimer = setTimeout(function () {
            if (sameMarker(state.marker, m)) show(ids[1], m.block, 1);
          }, WINDOW_MS + PAIR_HOLD_MS);
        }
      }

      function reconcile() {
        updateStuck();
        if (state.forced) return;
        var m = candidate();
        if (!m || sameMarker(m, state.marker)) { clearTimeout(state.dwellTimer); state.pending = null; return; }
        if (sameMarker(m, state.pending)) return;
        clearTimeout(state.dwellTimer);
        state.pending = m;
        state.dwellTimer = setTimeout(function () {
          state.pending = null;
          var now = candidate();
          if (!now || sameMarker(now, state.marker)) return;
          var wait = HOLD_MS - (Date.now() - state.last);
          if (wait > 0) { state.dwellTimer = setTimeout(function () { state.pending = null; reconcile(); }, wait); state.pending = now; return; }
          var dir = state.marker && (now.el.compareDocumentPosition(state.marker.el) & Node.DOCUMENT_POSITION_FOLLOWING) ? -1 : 1;
          apply(now, dir);
        }, DWELL_MS);
      }

      var stuck = false;
      function updateStuck() {
        var next = false;
        if (ctx.mobile && state.stage && blockOf(state.stage.el)) {
          var s = state.stage.el.getBoundingClientRect();
          var b = blockOf(state.stage.el).getBoundingClientRect();
          var top = parseFloat(w.getComputedStyle(state.stage.el).top) || 0;
          next = s.top <= top + 1 && b.bottom > s.bottom + 8;
        }
        if (next === stuck) return;
        stuck = next;
        d.documentElement.classList.toggle('story-stuck', stuck);
        d.dispatchEvent(new CustomEvent('p24:dock'));
      }

      function onScroll() {
        clearTimeout(state.settleTimer);
        state.forced = null;
        state.settleTimer = setTimeout(reconcile, SETTLE_MS);
      }
      function onResize() {
        clearTimeout(state.resizeTimer);
        state.resizeTimer = setTimeout(function () {
          stages.forEach(function (st) {
            finishAnims(st);
            Object.keys(st.layers).forEach(function (id) { fit(st.layers[id], st); });
            if (st.cur) st.win.style.clipPath = insetOf(st.cur.box, areaSize(st));
          });
          state.marker = null;
          reconcile();
        }, RESIZE_MS);
      }

      function onThumb(e) {
        var t = e.target.closest && e.target.closest('[data-story-thumb]');
        if (!t || !root.contains(t) || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
        var row = stepFor(t.getAttribute('data-story-thumb'));
        if (!row) return;
        e.preventDefault();
        var y = w.scrollY + row.getBoundingClientRect().top - vh() * lineFraction() + 4;
        w.scrollTo({ top: Math.max(0, y), behavior: motion ? 'smooth' : 'auto' });
      }

      if (!('IntersectionObserver' in w)) return { go: function () {}, destroy: function () {} };
      root.classList.add('p24-story');
      var wake = new IntersectionObserver(reconcile, { threshold: [0, 0.25, 0.5, 0.75, 1] });
      wake.observe(root);
      blocks.forEach(function (b) { wake.observe(b); });
      var pct = Math.round(lineFraction() * 100);
      var band = new IntersectionObserver(reconcile, { rootMargin: '-' + Math.max(0, pct - 5) + '% 0px -' + Math.max(0, 95 - pct) + '% 0px' });
      steps.forEach(function (s) { band.observe(s); });
      var pre = new IntersectionObserver(function (entries) {
        entries.forEach(function (e) { if (e.isIntersecting) { pre.unobserve(e.target); prefetch(e.target === root ? null : e.target); } });
      }, { rootMargin: '100% 0px' });
      (blocks.length ? blocks : [root]).forEach(function (b) { pre.observe(b); });
      observers.push(wake, band, pre);
      on(w, 'scroll', onScroll, { passive: true });
      if ('onscrollend' in w) on(w, 'scrollend', reconcile, { passive: true });
      on(w, 'resize', onResize, { passive: true });
      on(root, 'click', onThumb);
      ctx.onFinal(function () { stages.forEach(finishAnims); });

      var initial = candidate() || (blocks[0] ? { el: blocks[0], block: blocks[0], step: null } : (steps[0] ? { el: steps[0], block: null, step: steps[0] } : null));
      if (initial) apply(initial, 1);

      return {
        go: function (frameId) {
          var row = stepFor(frameId);
          state.forced = frameId;
          show(frameId, row ? blockOf(row) : (blocks[0] || null), 1);
        },
        destroy: function () {
          observers.forEach(function (o) { o.disconnect(); });
          offs.forEach(function (f) { f(); });
          [state.pairTimer, state.dwellTimer, state.settleTimer, state.resizeTimer].forEach(clearTimeout);
          stages.forEach(function (st) { finishAnims(st); if (st.area.parentNode) st.area.parentNode.removeChild(st.area); st.el.removeAttribute('data-story-ready'); });
          if (label.parentNode) label.parentNode.removeChild(label);
          qsa(root, '[data-story-static]').forEach(function (s) { s.hidden = false; });
          steps.forEach(function (s) { s.classList.remove('is-pictured'); });
          blocks.forEach(function (b) { b.classList.remove('is-active'); });
          root.removeAttribute('data-story-live');
          root.classList.remove('p24-story');
          if (stuck) { d.documentElement.classList.remove('story-stuck'); d.dispatchEvent(new CustomEvent('p24:dock')); }
        }
      };
    };
  }

  if (P24.component) P24.component('story', factory);
})(window, document);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var INTENT_MS = 150;
  var PREVIEW_STOP_S = 4;

  function factory(ctx) {
    return function slot(listRoot, opts) {
      opts = opts || {};
      var box = opts.slotEl;
      var noop = { destroy: function () {} };
      if (!listRoot || !box || !box.getClientRects().length) return noop;
      var rows = Array.prototype.slice.call(listRoot.querySelectorAll(opts.rows || '[data-slot-row]'));
      if (!rows.length) return noop;
      var mediaSel = opts.media || '[data-slot-media]';
      var g = ctx.gsap;
      var anim = ctx.motionOK && !!g;
      var previews = anim && !ctx.lite && w.matchMedia('(hover: hover) and (pointer: fine)').matches;
      var inner = box.querySelector('.p24-slot__inner');
      if (!inner) { inner = d.createElement('div'); inner.className = 'p24-slot__inner'; box.appendChild(inner); }
      var shownRow = null;
      var marked = null;
      var timer = 0;
      var video = null;
      var offs = [];
      function on(t, type, fn, o) { t.addEventListener(type, fn, o); offs.push(function () { t.removeEventListener(type, fn, o); }); }

      function pane(row) {
        var t = row.querySelector(mediaSel);
        var kind = t ? t.getAttribute('data-kind') : 'none';
        var fig = d.createElement('figure');
        fig.className = 'p24-slot__pane';
        fig.setAttribute('data-kind', kind);
        if (!t || kind === 'none') {
          var s = d.createElement('strong');
          s.textContent = t ? (t.getAttribute('data-title') || '') : '';
          fig.appendChild(s);
          fig.appendChild(d.createTextNode('Text only. No photograph or clip from these events is shown here.'));
          return fig;
        }
        var f = d.createElement(kind === 'clip' ? 'button' : 'a');
        f.className = 'p24-slot__frame';
        f.tabIndex = -1;
        if (kind === 'clip') {
          f.type = 'button';
          f.setAttribute('data-clip', t.getAttribute('data-clip'));
          f.setAttribute('data-flip-id', 'p24-slot');
          f.setAttribute('aria-label', 'Play clip');
        } else {
          f.href = t.getAttribute('href');
          f.setAttribute('data-slot-open', '');
        }
        var pic = t.querySelector('picture, img');
        if (pic) {
          pic = pic.cloneNode(true);
          var img = pic.tagName === 'IMG' ? pic : pic.querySelector('img');
          img.alt = '';
          img.loading = 'eager';
          var sz = Math.round(box.clientWidth || 0);
          if (sz > 0) {
            img.sizes = sz + 'px';
            Array.prototype.forEach.call(pic.querySelectorAll ? pic.querySelectorAll('source') : [], function (so) { so.sizes = sz + 'px'; });
          }
          f.appendChild(pic);
        }
        if (kind === 'clip') {
          var p = d.createElement('span');
          p.className = 'p24-play';
          p.textContent = 'Play clip';
          f.appendChild(p);
        }
        var cap = d.createElement('figcaption');
        cap.className = 'p24-cap p24-cap--wrap';
        cap.textContent = t.getAttribute('data-cap') || '';
        fig.appendChild(f);
        fig.appendChild(cap);
        return fig;
      }

      function stopVideo() {
        clearTimeout(timer);
        if (!video) return;
        video.pause();
        video.removeAttribute('src');
        video.load();
        video.remove();
        video = null;
      }
      function startVideo(row) {
        var t = row.querySelector(mediaSel);
        var f = inner.querySelector('.p24-slot__pane:not([data-leaving]) .p24-slot__frame');
        if (!f || !t || t.getAttribute('data-kind') !== 'clip') return;
        var v = video = d.createElement('video');
        v.className = 'p24-preview';
        v.muted = true;
        v.playsInline = true;
        v.setAttribute('muted', '');
        v.setAttribute('playsinline', '');
        v.setAttribute('aria-hidden', 'true');
        v.preload = 'auto';
        v.addEventListener('canplay', function () {
          if (video !== v) return;
          v.classList.add('is-on');
          var pr = v.play();
          if (pr && pr.catch) pr.catch(function () { /* stays on the poster */ });
        }, { once: true });
        v.addEventListener('timeupdate', function () { if (v.currentTime >= PREVIEW_STOP_S) v.pause(); });
        v.src = (t.getAttribute('href') || '').split('#')[0];
        f.insertBefore(v, f.querySelector('.p24-play'));
      }

      function place(row, instant) {
        var max = Math.max(0, box.offsetHeight - inner.offsetHeight);
        var y = row === rows[0] ? 0 : Math.max(0, Math.min(row.offsetTop - rows[0].offsetTop, max));
        if (anim && !instant) g.to(inner, { y: y, duration: 0.45, ease: ctx.ease.inOut, overwrite: 'auto' });
        else if (g) g.set(inner, { y: y });
        else inner.style.transform = 'translateY(' + y + 'px)';
      }

      function showRow(row, instant) {
        if (row === shownRow) return;
        stopVideo();
        shownRow = row;
        Array.prototype.forEach.call(inner.querySelectorAll('.p24-slot__pane[data-leaving]'), function (n) { n.remove(); });
        var old = inner.querySelector('.p24-slot__pane');
        var next = pane(row);
        if (old) { old.setAttribute('data-leaving', ''); inner.insertBefore(next, old); } else inner.appendChild(next);
        if (anim && !instant && old) {
          g.fromTo(next, { autoAlpha: 0 }, { autoAlpha: 1, duration: 0.25, ease: ctx.ease.ui, clearProps: 'opacity,visibility' });
          g.to(old, { autoAlpha: 0, duration: 0.25, ease: ctx.ease.ui, onComplete: function () { old.remove(); } });
        } else if (old) old.remove();
        place(row, instant);
      }
      function mark(row) {
        if (marked === row) return;
        if (marked) marked.classList.remove('is-active');
        marked = row;
        if (row) row.classList.add('is-active');
      }
      function rest() { mark(null); showRow(rows[0]); }

      showRow(rows[0], true);
      rows.forEach(function (row) {
        on(row, 'pointerenter', function (e) {
          if (e.pointerType === 'touch') return;
          mark(row);
          showRow(row);
          if (!previews || video) return;
          clearTimeout(timer);
          timer = setTimeout(function () { if (shownRow === row && marked === row) startVideo(row); }, INTENT_MS);
        });
        on(row, 'focusin', function () { mark(row); showRow(row); });
        on(row, 'focusout', function (e) { if (!e.relatedTarget || !row.contains(e.relatedTarget)) mark(null); });
      });
      on(listRoot, 'pointerleave', function (e) { if (e.pointerType !== 'touch') { stopVideo(); rest(); } });
      on(inner, 'click', function (e) {
        var a = e.target.closest('[data-slot-open]');
        if (!a || !ctx.viewer || e.button !== 0 || e.metaKey || e.ctrlKey) return;
        var t = shownRow && shownRow.querySelector(mediaSel + '[data-kind="still"]');
        if (!t) return;
        e.preventDefault();
        ctx.viewer.open(t, { from: a });
      });
      on(w, 'resize', function () { if (shownRow) place(shownRow, true); }, { passive: true });

      return {
        destroy: function () {
          stopVideo();
          offs.forEach(function (f) { f(); });
          mark(null);
          inner.textContent = '';
          if (g) g.set(inner, { clearProps: 'transform' });
        }
      };
    };
  }

  if (P24.component) P24.component('slot', factory);
})(window, document);

(function (w) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};

  function list(root, sel) { return Array.prototype.slice.call(root.querySelectorAll(sel)); }

  function bars(ctx, scope, stagger) {
    var g = ctx.gsap;
    var fills = list(scope, '[data-span-fill]');
    var marks = list(scope, '[data-span-mark]');
    if (scope.hasAttribute('data-span-fill')) fills = [scope];
    if (!fills.length) return;
    ctx.enter(scope, {
      prepare: function () { g.set(fills, { scaleX: 0, transformOrigin: '0% 50%' }); g.set(marks, { autoAlpha: 0 }); },
      play: function () {
        g.timeline()
          .to(fills, { scaleX: 1, duration: ctx.dur(0.6), ease: ctx.ease.out, stagger: stagger, clearProps: 'transform' })
          .to(marks, { autoAlpha: 1, duration: 0.2, ease: ctx.ease.ui, stagger: 0.03, clearProps: 'opacity,visibility' }, '-=0.25');
      },
      final: function () { g.set(fills.concat(marks), { clearProps: 'transform,opacity,visibility' }); }
    });
  }

  function line(ctx, root) {
    var g = ctx.gsap;
    var ln = root.querySelector('[data-span-line]');
    if (!ln) return;
    var stepsEls = list(root, '[data-span-step]');
    ctx.enter(root, {
      prepare: function () {
        g.set(ln, { scaleY: 0, transformOrigin: '50% 0%' });
        stepsEls.forEach(function (s) { s.classList.add('is-waiting'); });
      },
      play: function () {
        var top = ln.getBoundingClientRect().top;
        var hgt = Math.max(1, ln.offsetHeight);
        var at = stepsEls.map(function (s) { return Math.max(0, Math.min(1, (s.getBoundingClientRect().top - top) / hgt)); });
        g.to(ln, {
          scaleY: 1,
          duration: ctx.dur(0.8),
          ease: ctx.ease.out,
          clearProps: 'transform',
          onUpdate: function () {
            var p = g.getProperty(ln, 'scaleY');
            stepsEls.forEach(function (s, i) { if (p >= at[i]) s.classList.remove('is-waiting'); });
          },
          onComplete: function () { stepsEls.forEach(function (s) { s.classList.remove('is-waiting'); }); }
        });
      },
      final: function () { g.set(ln, { clearProps: 'transform' }); stepsEls.forEach(function (s) { s.classList.remove('is-waiting'); }); }
    });
  }

  function factory(ctx) {
    return function spans(root, opts) {
      if (!root || !ctx.motionOK || !ctx.gsap) return;
      opts = opts || {};
      if (opts.mode === 'line') { line(ctx, root); return; }
      var stagger = opts.stagger == null ? 0.08 : opts.stagger;
      if (ctx.mobile) {
        var items = list(root, '[data-span]');
        if (items.length) { items.forEach(function (it) { bars(ctx, it, 0); }); return; }
      }
      bars(ctx, root, stagger);
    };
  }

  if (P24.component) P24.component('spans', factory);
})(window);

(function (w, d) {
  'use strict';
  if (!w.P24 || typeof w.P24.register !== 'function') return;

  var PHRASES = [4, 3, 4, 2, 3, 4];
  var DESK = { ink: [0.5, 0.9, 1.4, 2.2, 2.85, 3.4], back: 3.65 };
  var PHONE = { ink: [0, 0.2], block: 0.54, hold: 0.8, inkStep: 0.3 };
  var DESK_IGI = true;
  var PHONE_IGI = true;
  var CAP_DELAY = 0.1;
  var CAP_IN_S = 0.15;
  var RISE_OPEN_S = 0.2;
  var BUILD_AT = 0.06;
  var ROLL_Y = 8;
  var INK_S = 0.3;
  var INK_STAGGER = 0.04;
  var HAIR_S = 0.25;
  var NAME_LATE_MS = 2000;
  var PHONE_GATE_MS = 1500;
  var SKIP_S = 0.25;

  function css(el, o) { Object.keys(o).forEach(function (k) { el.style[k] = o[k]; }); return el; }
  function wait(ms, v) { return new Promise(function (r) { setTimeout(function () { r(v); }, ms); }); }
  function textRect(node) { var r = d.createRange(); r.selectNodeContents(node); return r.getBoundingClientRect(); }

  function readCut(t) {
    var s = t.dataset;
    return {
      id: s.u1Cut, phrase: Number(s.phrase), desk: s.desk || null, short: s.short || '', what: s.what || '',
      srcset: s.srcset || '', ratio: Number(s.ratio) || 0, focus: s.focus || '50% 50%',
      phone: s.phone || '', focusPhone: s.focusPhone || '50% 50%', ready: false, layer: null
    };
  }

  function collect(root) {
    var figs = {
      lead: root.querySelector('.u1-fig--lead'),
      a: root.querySelector('.u1-fig--a'),
      b: root.querySelector('.u1-fig--b')
    };
    return {
      figs: figs,
      latin: root.querySelector('.u1-latin'),
      role: root.querySelector('.u1-role'),
      leadImg: figs.lead ? figs.lead.querySelector('picture img') : null,
      cuts: Array.prototype.map.call(root.querySelectorAll('template[data-u1-cut]'), readCut)
    };
  }

  function settle(el) {
    if (el.role) el.role.classList.remove('p24-ink-muted');
    if (el.latin) el.latin.removeAttribute('data-m1-hold');
  }

  function groupWords(words) {
    var total = PHRASES.reduce(function (a, b) { return a + b; }, 0);
    var out = [];
    var i = 0;
    if (words.length === total) {
      PHRASES.forEach(function (n) { out.push(words.slice(i, i + n)); i += n; });
      return out;
    }
    var per = Math.ceil(words.length / PHRASES.length);
    for (var j = 0; j < PHRASES.length; j++) out.push(words.slice(j * per, (j + 1) * per));
    return out;
  }

  function Reel(ctx, el) {
    var g = ctx.gsap;
    var phone = ctx.mobile;
    var INK = w.getComputedStyle(d.documentElement).getPropertyValue('--ink').trim() || '#16161a';
    var cuts = el.cuts.filter(function (c) {
      if (phone) return !!c.phone && (c.phrase !== 5 || PHONE_IGI);
      return !!(c.desk && c.srcset && (c.desk !== 'a' || DESK_IGI));
    });
    var S = { tl: null, q: null, name: null, words: null, all: [], groups: [], overs: {}, hairs: {}, shown: {},
      nodes: [], figs: [], done: false, fast: false, pauseAt: null, off: null, io: null, skipCb: null };
    var width0 = w.innerWidth;

    function cutFor(test) { for (var i = 0; i < cuts.length; i++) if (test(cuts[i])) return cuts[i]; return null; }
    function on(id) { return function () { return !!S.shown[id]; }; }
    function opacityOf(x) { return Number(g.getProperty(x, 'opacity')) || 0; }
    function relPos(fig) { if (S.figs.indexOf(fig) < 0) { S.figs.push(fig); fig.style.position = 'relative'; } }

    function splitRole() {
      if (ctx.SplitText) {
        S.words = ctx.SplitText.create(el.role, { type: 'words', wordsClass: 'u1-w', aria: 'auto' });
        S.all = S.words.words || [];
      }
      if (!S.all.length) S.all = [el.role];
      S.groups = groupWords(S.all);
    }

    function nameRise(tl) {
      var latin = el.latin;
      if (phone || !latin || !ctx.m1.holdName || ctx.internalNav) return;
      if (w.performance.now() > NAME_LATE_MS || w.getComputedStyle(latin).opacity !== '0') return;
      ctx.own(latin);
      g.set(latin, { autoAlpha: 1 });
      var fontsOK = !d.fonts || !d.fonts.check || d.fonts.check('600 1em Eczar', latin.textContent);
      if (fontsOK && ctx.SplitText) {
        var kerned = glyphLefts(latin);
        S.name = ctx.SplitText.create(latin, { type: 'lines,chars', mask: 'lines', linesClass: 'p24-line', charsClass: 'u1-ch', aria: 'auto' });
        keepKerning(S.name.chars, kerned);
        var chars = S.name.chars || [];
        tl.from(chars, { yPercent: 130, duration: 0.62, stagger: 0.018, ease: ctx.ease.out }, 0);
        clipMasks(tl, S.name.masks || [], 0.62 + 0.018 * Math.max(0, chars.length - 1));
      } else {
        tl.from(latin, { y: 24, autoAlpha: 0, duration: 0.7, ease: ctx.ease.out }, 0);
      }
    }

    function clipMasks(tl, masks, riseEnd) {
      if (!masks.length) return;
      var pad = parseFloat(w.getComputedStyle(masks[0]).paddingBottom) || 0;
      if (!pad) return;
      g.set(masks, { clipPath: 'inset(0px 0px ' + pad + 'px 0px)' });
      tl.to(masks, { clipPath: 'inset(0px 0px 0px 0px)', duration: RISE_OPEN_S, ease: 'none' }, Math.max(0, riseEnd - RISE_OPEN_S));
    }

    function glyphLefts(node) {
      var out = [];
      var r = d.createRange();
      var walker = d.createTreeWalker(node, NodeFilter.SHOW_TEXT);
      var tn;
      while ((tn = walker.nextNode())) {
        for (var i = 0; i < tn.length; i++) {
          if (/\s/.test(tn.data[i])) continue;
          r.setStart(tn, i);
          r.setEnd(tn, i + 1);
          out.push(r.getBoundingClientRect().left);
        }
      }
      return out;
    }
    function keepKerning(chars, lefts) {
      if (!chars || chars.length !== lefts.length) return;
      chars.forEach(function (ch, i) {
        var dx = lefts[i] - ch.getBoundingClientRect().left;
        if (Math.abs(dx) > 0.1) g.set(ch, { x: dx });
      });
    }

    function ink(tl, i, t) {
      var gr = S.groups[i];
      if (gr && gr.length) tl.to(gr, { color: INK, duration: ctx.dur(INK_S), stagger: INK_STAGGER, ease: ctx.ease.ui }, t);
    }

    function capLine(box, c) {
      var s = d.createElement('span');
      if (c) {
        var what = c.short.indexOf(c.what) === 0 ? c.what : '';
        if (what) {
          var b = d.createElement('span');
          b.className = 'u1-cap__what';
          b.textContent = what;
          s.appendChild(b);
        }
        s.appendChild(d.createTextNode(c.short.slice(what.length).replace(/^ /, ' ')));
      }
      css(s, { gridArea: '1 / 1', visibility: 'hidden', opacity: '0' });
      box.appendChild(s);
      return s;
    }

    function makeOver(key, list) {
      var fig = el.figs[key];
      var cap = fig && fig.querySelector('figcaption');
      if (!cap || !list.length) return;
      relPos(fig);
      var fr = fig.getBoundingClientRect();
      var cr = cap.getBoundingClientRect();
      var box = d.createElement('div');
      box.className = cap.className;
      box.setAttribute('aria-hidden', 'true');
      css(box, { position: 'absolute', left: (cr.left - fr.left) + 'px', top: (cr.top - fr.top) + 'px', width: cr.width + 'px',
        margin: '0', display: 'grid', overflow: 'hidden', background: 'var(--section-bg)', pointerEvents: 'none',
        visibility: 'hidden', opacity: '0', zIndex: '2' });
      var o = { box: box, lines: { orig: capLine(box, null) } };
      var clone = cap.cloneNode(true);
      while (clone.firstChild) o.lines.orig.appendChild(clone.firstChild);
      css(o.lines.orig, { visibility: 'inherit', opacity: '1' });
      list.forEach(function (c) { o.lines[c.id] = capLine(box, c); });
      fig.appendChild(box);
      S.nodes.push(box);
      S.overs[key] = o;
    }

    function makeHair(key) {
      var fig = el.figs[key];
      var cap = fig && fig.querySelector('figcaption');
      if (!cap) return;
      relPos(fig);
      var h = d.createElement('span');
      h.setAttribute('aria-hidden', 'true');
      css(h, { position: 'absolute', left: '0', top: '0', width: '0', height: '2px', background: 'var(--ink)',
        transformOrigin: '0 50%', pointerEvents: 'none', visibility: 'hidden', opacity: '0', zIndex: '3' });
      fig.appendChild(h);
      S.nodes.push(h);
      S.hairs[key] = { el: h, fig: fig, cap: cap, key: key, w: { orig: 1 }, dy: { orig: 0 } };
    }

    function placeHair(hr) {
      var fr = hr.fig.getBoundingClientRect();
      var r = textRect(hr.cap);
      if (!r.width) return;
      css(hr.el, { left: (r.left - fr.left) + 'px', top: (r.bottom - fr.top + 3) + 'px', width: r.width + 'px' });
      var o = S.overs[hr.key];
      if (o) Object.keys(o.lines).forEach(function (k) {
        var lr = textRect(o.lines[k]);
        hr.w[k] = (lr.width || r.width) / r.width;
        hr.dy[k] = lr.height ? lr.bottom - r.bottom : 0;
      });
    }

    function mount() {
      cuts.forEach(makeLayer);
      if (phone) {
        makeOver('lead', cuts);
        makeHair('lead');
        return;
      }
      makeOver('lead', cuts.filter(function (c) { return c.desk === 'lead'; }));
      makeOver('a', cuts.filter(function (c) { return c.desk === 'a'; }));
      ['lead', 'a', 'b'].forEach(makeHair);
    }

    function decode(img) {
      var p = img.decode ? img.decode() : ctx.whenLoaded(img);
      return p.then(function () { return !!img.naturalWidth; }, function () { return false; });
    }

    function makeLayer(c) {
      var fig = el.figs[phone ? 'lead' : c.desk];
      var frame = fig && fig.querySelector('.u1-frame');
      if (!frame) return;
      var box = d.createElement('div');
      box.setAttribute('aria-hidden', 'true');
      css(box, { position: 'absolute', inset: '0', overflow: 'hidden', zIndex: '1', visibility: 'hidden', opacity: '0' });
      var img = d.createElement('img');
      img.alt = '';
      img.decoding = 'async';
      img.setAttribute('fetchpriority', 'low');
      css(img, { display: 'block', width: '100%', height: '100%', objectFit: 'cover', objectPosition: phone ? c.focusPhone : c.focus });
      box.appendChild(img);
      frame.appendChild(box);
      S.nodes.push(box);
      c.layer = box;
      c.img = img;
      c.frame = frame;
    }

    function loadLayer(c) {
      if (!c.img || S.done) return Promise.resolve(false);
      if (phone) {
        c.img.src = c.phone;
      } else {
        var r = c.frame.getBoundingClientRect();
        c.img.sizes = Math.ceil(Math.max(r.width, r.height * c.ratio)) + 'px';
        c.img.srcset = c.srcset;
      }
      return decode(c.img).then(function (ok) { c.ready = ok && !S.done; return c.ready; });
    }

    function loadCuts() {
      if (ctx.lite || !cuts.length) return Promise.resolve(false);
      return ctx.whenLoaded(el.leadImg).then(function () {
        return Promise.all(cuts.map(loadLayer));
      }).then(function (all) { return all.every(Boolean); });
    }

    function cutIn(tl, c, t, sure) {
      if (!c.layer) return;
      if (sure) S.shown[c.id] = true;
      tl.set(c.layer, { autoAlpha: sure ? 1 : function () { S.shown[c.id] = c.ready && !S.fast; return S.shown[c.id] ? 1 : 0; } }, t);
    }
    function cutOut(tl, c, t) { if (c.layer) tl.set(c.layer, { autoAlpha: 0 }, t); }

    function roll(tl, key, from, to, id, t) {
      var o = S.overs[key];
      if (!o || !o.lines[from] || !o.lines[to]) return;
      var a = o.lines[from];
      var b = o.lines[to];
      var yes = on(id);
      var dur = ctx.dur(CAP_IN_S);
      if (from === 'orig') tl.set(o.box, { autoAlpha: function () { return yes() ? 1 : opacityOf(o.box); } }, t);
      tl.set(a, { y: 0, autoAlpha: function () { return yes() ? 0 : opacityOf(a); } }, t);
      tl.fromTo(b, { y: function () { return yes() ? ROLL_Y : 0; }, autoAlpha: function () { return yes() ? 0 : opacityOf(b); } },
        { y: 0, autoAlpha: function () { return yes() ? 1 : opacityOf(b); }, duration: dur, ease: ctx.ease.ui, immediateRender: false }, t + CAP_DELAY);
      if (to === 'orig') tl.set(o.box, { autoAlpha: function () { return yes() ? 0 : opacityOf(o.box); } }, t + CAP_DELAY + dur);
    }

    function hairDraw(tl, key, t, lineKey, id) {
      var hr = S.hairs[key];
      if (!hr) return;
      var yes = id ? on(id) : function () { return true; };
      tl.fromTo(hr.el, { scaleX: 0, y: function () { return hr.dy[lineKey] || 0; }, autoAlpha: function () { return yes() ? 1 : 0; } },
        { scaleX: function () { return yes() ? (hr.w[lineKey] || 1) : 0; }, duration: ctx.dur(HAIR_S), ease: ctx.ease.ui,
          immediateRender: false, onStart: function () { if (!hr.placed) { hr.placed = true; placeHair(hr); } } }, t);
    }
    function hairFit(tl, key, lineKey, id, t) {
      var hr = S.hairs[key];
      if (!hr) return;
      var yes = on(id);
      tl.to(hr.el, { scaleX: function () { return yes() ? (hr.w[lineKey] || 1) : Number(g.getProperty(hr.el, 'scaleX')); },
        y: function () { return yes() ? (hr.dy[lineKey] || 0) : Number(g.getProperty(hr.el, 'y')); },
        autoAlpha: function () { return yes() ? 1 : 0; }, duration: ctx.dur(INK_S), ease: ctx.ease.ui }, t);
    }
    function hairOff(tl, key, t) {
      var hr = S.hairs[key];
      if (hr) tl.to(hr.el, { autoAlpha: 0, duration: ctx.dur(0.2), ease: ctx.ease.ui }, t);
    }

    function buildDesk(tl) {
      var P = DESK.ink;
      var ff = cutFor(function (c) { return c.desk === 'lead'; });
      var igi = cutFor(function (c) { return c.desk === 'a'; });
      P.forEach(function (t, i) { ink(tl, i, t); });
      hairDraw(tl, 'lead', P[1], 'orig');
      hairDraw(tl, 'a', P[1], 'orig');
      hairOff(tl, 'a', P[2]);
      if (ff) {
        cutIn(tl, ff, P[2]);
        roll(tl, 'lead', 'orig', ff.id, ff.id, P[2]);
        hairFit(tl, 'lead', ff.id, ff.id, P[2] + CAP_DELAY);
        cutOut(tl, ff, P[3]);
        roll(tl, 'lead', ff.id, 'orig', ff.id, P[3]);
      } else {
        hairOff(tl, 'lead', P[2]);
      }
      hairOff(tl, 'lead', P[3]);
      if (igi) {
        cutIn(tl, igi, P[4]);
        roll(tl, 'a', 'orig', igi.id, igi.id, P[4]);
        hairDraw(tl, 'a', P[4] + CAP_DELAY, igi.id, igi.id);
        cutOut(tl, igi, DESK.back);
        roll(tl, 'a', igi.id, 'orig', igi.id, DESK.back);
      }
      hairDraw(tl, 'b', P[5], 'orig');
      hairOff(tl, 'a', DESK.back);
      hairOff(tl, 'b', DESK.back + 0.05);
    }

    function buildPhoneIntro(tl) {
      ink(tl, 0, PHONE.ink[0]);
      ink(tl, 1, PHONE.ink[1]);
      hairDraw(tl, 'lead', PHONE.ink[1], 'orig');
    }

    function phoneBlock(tl, at, withCuts) {
      var plan = [3, 4, 5, 6].map(function (p) { return cutFor(function (c) { return c.phrase === p; }); });
      if (!withCuts || !plan.some(Boolean)) {
        [2, 3, 4, 5].forEach(function (i, k) { ink(tl, i, at + k * PHONE.inkStep); });
        hairOff(tl, 'lead', at);
        return;
      }
      var t = at;
      var cur = null;
      var hairOn = true;
      function go(c) {
        if (c === cur) return;
        if (c) cutIn(tl, c, t, true);
        if (cur) cutOut(tl, cur, t);
        roll(tl, 'lead', cur ? cur.id : 'orig', c ? c.id : 'orig', (c || cur).id, t);
        if (!c) { hairOff(tl, 'lead', t); hairOn = false; }
        else if (hairOn) hairFit(tl, 'lead', c.id, c.id, t + CAP_DELAY);
        else { hairDraw(tl, 'lead', t + CAP_DELAY, c.id, c.id); hairOn = true; }
        cur = c;
      }
      plan.forEach(function (c, k) { ink(tl, k + 2, t); go(c); t += PHONE.hold; });
      go(null);
    }

    function resolveGate(ok) {
      if (S.pauseAt == null || S.done) return;
      var tl = S.tl;
      var at = Math.max(S.pauseAt, tl.time());
      tl.removePause(S.pauseAt);
      S.pauseAt = null;
      phoneBlock(tl, at, ok && !S.fast);
      if (tl.paused() && !S.fast) tl.play();
    }

    function skipTarget() {
      var p = {
        vars: {},
        duration: function () { return 1; },
        time: function () { return 0; },
        timeScale: function (v) { if (v === undefined) return 1; fastFinish(false); return p; },
        progress: function (v) { if (v === undefined) return 0; fastFinish(true); return p; },
        eventCallback: function (type, fn) {
          if (type !== 'onComplete') return null;
          if (arguments.length < 2) return S.skipCb;
          S.skipCb = fn;
          return p;
        }
      };
      return p;
    }

    function fastFinish(instant) {
      if (S.done || S.fast) return;
      S.fast = true;
      if (S.pauseAt != null) resolveGate(false);
      var tl = S.tl;
      if (instant || ctx.qa) { tl.progress(1); return; }
      tl.pause();
      var q = S.q = g.timeline({ onComplete: onDone });
      q.set(cuts.map(function (c) { return c.layer; }).filter(Boolean), { autoAlpha: 0 }, 0);
      Object.keys(S.overs).forEach(function (k) { q.set(S.overs[k].box, { autoAlpha: 0 }, 0); });
      q.to(S.all, { color: INK, duration: SKIP_S, ease: ctx.ease.ui, overwrite: 'auto' }, 0);
      q.to(Object.keys(S.hairs).map(function (k) { return S.hairs[k].el; }), { autoAlpha: 0, duration: 0.2, overwrite: 'auto' }, 0);
      if (S.name) q.to(S.name.chars, { yPercent: 0, duration: SKIP_S, ease: ctx.ease.out, overwrite: 'auto' }, 0);
      else if (el.latin) q.to(el.latin, { y: 0, autoAlpha: 1, duration: SKIP_S, overwrite: 'auto' }, 0);
    }

    function onDone() { if (!ctx.qa) finish(); }

    function finish() {
      if (S.done) return;
      S.done = true;
      S.fast = true;
      if (S.off) S.off();
      if (S.skipCb) S.skipCb();
      if (S.io) S.io.disconnect();
      w.removeEventListener('resize', onResize);
      if (S.tl) S.tl.kill();
      if (S.q) S.q.kill();
      if (S.name) S.name.revert();
      if (S.words) S.words.revert();
      if (el.latin) g.set(el.latin, { clearProps: 'opacity,visibility,transform' });
      S.nodes.forEach(function (n) { if (n.parentNode) n.parentNode.removeChild(n); });
      S.figs.forEach(function (f) { f.style.position = ''; });
      settle(el);
    }

    function onResize() { if (w.innerWidth !== width0) fastFinish(true); }

    function watchLead() {
      if (!phone || !('IntersectionObserver' in w) || !el.figs.lead) return;
      S.io = new IntersectionObserver(function (entries) {
        entries.forEach(function (e) { if (!e.isIntersecting) fastFinish(true); });
      });
      S.io.observe(el.figs.lead);
    }

    function build(tl) {
      if (S.done || S.fast || S.built) return;
      S.built = true;
      splitRole();
      mount();
      var loading = loadCuts();
      if (phone) {
        buildPhoneIntro(tl);
        S.pauseAt = PHONE.block;
        tl.addPause(PHONE.block);
        Promise.race([loading, wait(PHONE_GATE_MS, false)]).then(resolveGate);
      } else {
        buildDesk(tl);
      }
    }

    function start() {
      var tl = S.tl = g.timeline({ paused: true, onComplete: onDone });
      nameRise(tl);
      if (phone || !S.name) {
        build(tl);
      } else {
        tl.set({}, {}, 1);
        tl.call(function () { build(tl); }, null, BUILD_AT);
      }
      S.off = ctx.skipOnInput(skipTarget());
      ctx.setIntro({ timeline: tl });
      ctx.onFinal(function () { fastFinish(true); });
      w.addEventListener('resize', onResize, { passive: true });
      watchLead();
      tl.play(0);
    }

    return { start: start, destroy: function () { finish(); } };
  }

  w.P24.register('u1', {
    init: function (ctx) {
      var root = d.querySelector('section.u1');
      if (!root) return undefined;
      var el = collect(root);
      if (!ctx.motionOK || !ctx.gsap || !ctx.m1 || !ctx.m1.play || !el.role || !el.leadImg) {
        settle(el);
        return undefined;
      }
      var reel = new Reel(ctx, el);
      reel.start();
      return reel.destroy;
    }
  });
})(window, document);

(function (w, d) {
  'use strict';
  if (!w.P24 || !w.P24.register) return;

  var STORY_AFTER_MS = 4500;
  var LEAVE_MS = 8000;
  var PHONE_LINE_GAP = 96;            /* px from the stuck stage's bottom edge to the reading line: a row activates while
                                         its date and name are still in view below the stage, and stays readable
                                         there for most of the time it owns the photo */

  function px(v) { return parseFloat(v) || 0; }

  function phoneLine(root) {
    var st = Array.prototype.filter.call(root.querySelectorAll('.u2-bstage'), function (s) { return s.getClientRects().length; })[0];
    if (!st) return undefined;
    var top = px(w.getComputedStyle(st).top);
    var vh = w.innerHeight || d.documentElement.clientHeight;
    return Math.min(0.7, Math.max(0.4, (top + st.offsetHeight + PHONE_LINE_GAP) / vh));
  }

  function quietStrips(root) {
    var done = [];
    Array.prototype.forEach.call(root.querySelectorAll('.u2-bstage [data-story-strip]'), function (ul) {
      ul.setAttribute('aria-hidden', 'true');
      Array.prototype.forEach.call(ul.querySelectorAll('a'), function (a) { a.setAttribute('tabindex', '-1'); });
      done.push(ul);
    });
    return function () {
      done.forEach(function (ul) {
        ul.removeAttribute('aria-hidden');
        Array.prototype.forEach.call(ul.querySelectorAll('a'), function (a) { a.removeAttribute('tabindex'); });
      });
    };
  }

  w.P24.register('u2', {
    init: function (ctx) {
      var root = d.getElementById('what-she-hosts');
      if (!root) return undefined;
      var g = ctx.gsap;
      var anim = ctx.motionOK && !!g;
      var lastRow = null;
      var story = null;
      var io = null;
      var timer = 0;
      var leaveTimer = 0;
      var offs = [];

      if (anim) ctx.reveal(root.querySelector('.u2-title'), { type: 'lines' });
      if (ctx.mobile) offs.push(quietStrips(root));
      if (!ctx.story) return function () { offs.forEach(function (f) { f(); }); };

      var opts = {
        onChange: function (e) {
          if (!anim || !e.step || e.step === lastRow) { lastRow = e.step || lastRow; return; }
          lastRow = e.step;
          var label = e.step.querySelector('.p24-inphoto');
          if (label) g.fromTo(label, { autoAlpha: 0, x: -6 }, { autoAlpha: 1, x: 0, duration: 0.25, ease: ctx.ease.ui, overwrite: true, clearProps: 'opacity,visibility,transform' });
        }
      };
      if (ctx.mobile) {
        var line = phoneLine(root);
        if (line) opts.readingLine = line;
      }

      function create() {
        if (story) return;
        if (io) { io.disconnect(); io = null; }
        clearTimeout(timer);
        story = ctx.story(root, opts);
      }
      if ('IntersectionObserver' in w) {
        io = new IntersectionObserver(function (entries) {
          if (entries.some(function (e) { return e.isIntersecting; })) create();
        });
        io.observe(root);
        timer = setTimeout(create, STORY_AFTER_MS);
      } else {
        create();
      }

      if (anim) {
        var stages = ctx.mobile ? root.querySelectorAll('.u2-bstage') : root.querySelectorAll('.u2-stage');
        Array.prototype.forEach.call(stages, function (st) {
          if (!st.getClientRects().length) return;
          var watch = st.closest(ctx.mobile ? '.u2-block' : '.u2-stagecol') || st.parentElement;
          ctx.enter(watch, {
            rootMargin: '0px 0px -10% 0px',
            prepare: function () { g.set(st, { clipPath: 'inset(100% 0% 0% 0%)' }); },
            play: function () {
              g.to(st, { clipPath: 'inset(0% 0% 0% 0%)', duration: ctx.dur(0.8), ease: ctx.ease.out, clearProps: 'clipPath' });
            },
            final: function () { g.set(st, { clearProps: 'clipPath' }); }
          });
        });
      }

      function onLeave(e) {
        var a = e.target.closest ? e.target.closest('a[data-vt="family-hero"]') : null;
        if (!a || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
        root.classList.add('u2-leaving');
        clearTimeout(leaveTimer);
        leaveTimer = setTimeout(function () { root.classList.remove('u2-leaving'); }, LEAVE_MS);
      }
      function onShow() { root.classList.remove('u2-leaving'); }
      root.addEventListener('click', onLeave, true);
      w.addEventListener('pageshow', onShow);
      offs.push(function () {
        root.removeEventListener('click', onLeave, true);
        w.removeEventListener('pageshow', onShow);
        clearTimeout(leaveTimer);
        root.classList.remove('u2-leaving');
      });

      return function () {
        if (io) io.disconnect();
        clearTimeout(timer);
        if (story) story.destroy();
        offs.forEach(function (f) { f(); });
      };
    }
  });
})(window, document);

(function (w, d) {
  'use strict';
  if (!w.P24 || !w.P24.register) return;

  w.P24.register('u3', {
    init: function (ctx) {
      var root = d.getElementById('asked-back');
      if (!root) return undefined;
      var list = root.querySelector('.u3-list');
      if (ctx.motionOK) ctx.reveal(root.querySelector('#u3-h'), { type: 'lines' });
      if (ctx.spans && list) ctx.spans(list, { mode: 'bars' });
      var slot = ctx.slot && list ? ctx.slot(list, { slotEl: root.querySelector('.u3-slot'), rows: '[data-slot-row]', media: '[data-slot-media]' }) : null;
      return function () { if (slot) slot.destroy(); };
    }
  });
})(window, document);

(function (w, d) {
  'use strict';
  if (!w.P24 || !w.P24.register) return;

  w.P24.register('home', {
    init: function (ctx) {
      if (!ctx.motionOK) return undefined;
      var abroad = d.getElementById('abroad');
      var em = d.getElementById('for-event-managers');
      if (abroad) {
        ctx.reveal(abroad.querySelector('.home-h2'), { type: 'lines' });
        ctx.reveal(abroad.querySelector('.home-abroad__list'), { type: 'group', stagger: 0.06 });
      }
      if (em) {
        ctx.reveal(em.querySelector('.home-h2'), { type: 'lines' });
        ctx.reveal(em.querySelector('.home-em__list'), { type: 'group', stagger: 0.08 });
      }
      return undefined;
    }
  });
})(window, document);
