window.P24 = window.P24 || {};
window.P24.lazyComponents = ["viewer"];
/* Prototype 24 · js/p24-work.js — generated by tools/assemble.cjs from tools/pages.json; do not edit. */

(function (w, d) {
  'use strict';

  var h = d.documentElement;
  var MQ_MOTION = '(prefers-reduced-motion: no-preference)';
  var MQ_REDUCE = '(prefers-reduced-motion: reduce)';
  var MQ_MOBILE = '(max-width: 760px)';
  var EASE = Object.freeze({ out: 'expo.out', inOut: 'power3.inOut', ui: 'power2.out', window: 'cubic-bezier(.65,0,.35,1)', page: 'cubic-bezier(.16,1,.3,1)' });
  var FLIP_SRC = 'vendor/Flip.min.js';
  var MOBILE_FACTOR = 0.85;
  var SKIP_TO_END_S = 0.25;

  var P24 = w.P24 = w.P24 || {};
  var units = [];
  var components = [];
  var finals = [];
  var errors = P24.errors = P24.errors || [];
  var qa = h.classList.contains('qa');

  function mq(q) { return w.matchMedia(q).matches; }
  function toArray(x) {
    if (!x) return [];
    if (x.nodeType === 1) return [x];
    return Array.prototype.slice.call(x);
  }
  function timeout(ms, value) { return new Promise(function (resolve) { setTimeout(function () { resolve(value); }, ms); }); }
  function report(id, err) {
    errors.push({ unit: id, message: String(err && err.message || err) });
    setTimeout(function () { throw err; }, 0);
  }

  function own(els) { toArray(els).forEach(function (el) { el.classList.add('m-owned'); }); }

  function fontsReady(ms) {
    if (!d.fonts || !d.fonts.load) return Promise.resolve(true);
    return Promise.race([
      d.fonts.load('600 1em Eczar').then(function () { return true; }, function () { return false; }),
      timeout(ms == null ? 500 : ms, false)
    ]);
  }
  function whenLoaded(img) {
    if (!img) return Promise.resolve(false);
    if (img.complete && img.naturalWidth) return Promise.resolve(true);
    return new Promise(function (resolve) {
      img.addEventListener('load', function () { resolve(true); }, { once: true });
      img.addEventListener('error', function () { resolve(false); }, { once: true });
    });
  }
  function decodeOne(img) {
    if (!img) return Promise.resolve();
    if (img.decode) return img.decode();
    return whenLoaded(img);
  }
  function decodeAll(imgs, ms) {
    return Promise.race([
      Promise.all(toArray(imgs).map(decodeOne)).then(function () { return true; }, function () { return false; }),
      timeout(ms == null ? 600 : ms, false)
    ]);
  }
  function lite() {
    var c = w.navigator.connection;
    if (!c) return false;
    return !!c.saveData || /^(slow-2g|2g|3g)$/.test(c.effectiveType || '');
  }

  var flipPromise = null;
  function loadFlip() {
    if (w.Flip && w.gsap) { w.gsap.registerPlugin(w.Flip); return Promise.resolve(w.Flip); }
    if (flipPromise) return flipPromise;
    flipPromise = new Promise(function (resolve, reject) {
      var s = d.createElement('script');
      s.src = FLIP_SRC;
      s.async = true;
      s.onload = function () {
        if (!w.Flip || !w.gsap) { reject(new Error('Flip failed to load')); return; }
        w.gsap.registerPlugin(w.Flip);
        resolve(w.Flip);
      };
      s.onerror = function () { flipPromise = null; reject(new Error('Flip failed to load')); };
      d.head.appendChild(s);
    });
    return flipPromise;
  }

  function onFinal(fn) { if (typeof fn === 'function') finals.push(fn); }

  function enter(el, o) {
    if (!el || !o || typeof o.play !== 'function' || !('IntersectionObserver' in w)) return;
    var state = 'unknown';
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (e) {
        if (state === 'unknown') {
          var below = e.boundingClientRect.top >= (w.innerHeight || h.clientHeight);
          if (!below) { state = 'static'; io.disconnect(); return; }
          state = 'waiting';
          if (o.prepare) o.prepare(el);
          onFinal(function () { if (state === 'waiting') { state = 'done'; io.disconnect(); finish(); } });
          return;
        }
        if (state === 'waiting' && e.isIntersecting) { state = 'done'; io.disconnect(); o.play(el); }
      });
    }, { rootMargin: o.rootMargin || '0px 0px -15% 0px' });
    var jumpTimer = 0;
    function onJump() {
      clearTimeout(jumpTimer);
      jumpTimer = setTimeout(function () {
        if (state !== 'waiting') { w.removeEventListener('scroll', onJump); return; }
        if (el.getBoundingClientRect().bottom <= 0) { state = 'done'; io.disconnect(); w.removeEventListener('scroll', onJump); finish(); }
      }, 150);
    }
    w.addEventListener('scroll', onJump, { passive: true });
    function finish() {
      if (o.final) { o.final(el); return; }
      el.style.opacity = ''; el.style.transform = ''; el.style.clipPath = ''; el.style.visibility = '';
    }
    io.observe(el);
  }

  function runFinals() {
    var g = w.gsap;
    if (g && g.globalTimeline) g.globalTimeline.getChildren(true, true, true).forEach(function (t) { if (t.progress() < 1) t.progress(1); });
    if (d.getAnimations) d.getAnimations().forEach(function (a) { try { if (a.effect && a.effect.getTiming().iterations !== Infinity) a.finish(); } catch (err) { /* not finishable */ } });
    finals.slice().forEach(function (fn) { try { fn(); } catch (err) { report('final', err); } });
  }
  w.addEventListener('beforeprint', runFinals);
  d.addEventListener('beforematch', runFinals, true);

  var MOD_KEY = /^(Shift|Control|Alt|Meta|F\d{1,2})$/;
  function skipOnInput(tl) {
    if (!tl) return function () {};
    var coarse = mq('(pointer: coarse)');
    var startY = w.scrollY;
    var down = null;
    var opt = { passive: true, capture: true };
    var done = false;
    var list = [['keydown', onKey]];
    if (coarse) list.push(['pointerdown', onDown], ['pointerup', onUp]);
    else list.push(['wheel', fire], ['pointerdown', fire], ['scroll', onScroll]);
    function off() {
      if (done) return;
      done = true;
      list.forEach(function (p) { w.removeEventListener(p[0], p[1], opt); });
    }
    function fire() {
      off();
      if (qa) { tl.progress(1); return; }
      var rem = tl.duration() - tl.time();
      if (rem > 0) tl.timeScale(Math.max(tl.timeScale(), rem / SKIP_TO_END_S));
    }
    function onKey(e) { if (!MOD_KEY.test(e.key || '')) fire(); }
    function onScroll() { if (Math.abs(w.scrollY - startY) > 8) fire(); }
    function onDown(e) { down = { x: e.clientX, y: e.clientY, t: e.timeStamp }; }
    function onUp(e) {
      if (!down) return;
      var near = Math.abs(e.clientX - down.x) <= 10 && Math.abs(e.clientY - down.y) <= 10;
      var quick = e.timeStamp - down.t <= 300;
      down = null;
      if (near && quick) fire();
    }
    list.forEach(function (p) { w.addEventListener(p[0], p[1], opt); });
    var prev = tl.eventCallback('onComplete');
    var params = tl.vars && tl.vars.onCompleteParams;
    tl.eventCallback('onComplete', function () { off(); if (prev) prev.apply(tl, params || []); });
    return off;
  }

  var LAZY = {
    player: { sel: 'a[data-clip], button[data-clip]', methods: ['open', 'close', 'isOpen', 'manifest', 'rail', 'hoverPreview'] },
    viewer: { sel: 'a[data-view]', methods: ['open', 'close'] }
  };
  var lazyNames = (P24.lazyComponents || []).filter(function (n) { return !!LAZY[n]; });
  var lazyLoads = {};
  var lazyReady = {};
  function findComponent(name) {
    for (var i = 0; i < components.length; i++) if (components[i].name === name) return components[i];
    return null;
  }
  function loadComponent(name) {
    if (lazyLoads[name]) return lazyLoads[name];
    lazyLoads[name] = new Promise(function (resolve, reject) {
      var s = d.createElement('script');
      s.src = 'js/components/' + name + '.js';
      s.async = true;
      s.onload = function () {
        var c = findComponent(name);
        if (!c) { reject(new Error('component ' + name + ' did not register')); return; }
        var api = c.factory(P24.ctx || makeCtx(h.classList.contains('js-motion')));
        if (P24.ctx) P24.ctx[name] = api;
        resolve(api);
      };
      s.onerror = function () { lazyLoads[name] = null; reject(new Error('component ' + name + ' failed to load')); };
      d.head.appendChild(s);
    });
    return lazyLoads[name];
  }
  function proxy(name) {
    var p = { lazy: true };
    LAZY[name].methods.forEach(function (m) {
      p[m] = function () {
        var a = arguments;
        return loadComponent(name).then(function (api) { return api[m].apply(api, a); });
      };
    });
    return p;
  }
  lazyNames.forEach(function (name) {
    var sel = LAZY[name].sel;
    d.addEventListener('click', function (e) {
      if (lazyReady[name]) return;
      var t = e.target.closest && e.target.closest(sel);
      if (!t || e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
      e.preventDefault();
      loadComponent(name).then(function (api) { api.open(t); }, function () { if (t.href) w.location.href = t.href; });
    });
    var warm = function (e) {
      if (lazyReady[name] || !e.target.closest || !e.target.closest(sel)) return;
      loadComponent(name).catch(function () { /* retried on click */ });
    };
    d.addEventListener('pointerover', warm, { passive: true });
    d.addEventListener('focusin', warm);
    d.addEventListener('touchstart', warm, { passive: true });
  });
  if (lazyNames.length) {
    w.addEventListener('load', function () {
      setTimeout(function () { lazyNames.forEach(function (n) { loadComponent(n).catch(function () { /* on demand */ }); }); }, 4000);
    }, { once: true });
  }

  function makeCtx(motionOK) {
    var mobile = mq(MQ_MOBILE);
    var ctx = {
      gsap: w.gsap || null,
      SplitText: w.SplitText || null,
      motionOK: motionOK,
      mobile: mobile,
      coarse: mq('(pointer: coarse)'),
      qa: qa,
      lite: lite(),
      internalNav: h.classList.contains('vt-nav'),
      m1: { play: !h.classList.contains('m1-skip'), holdName: h.classList.contains('m1-type') },
      ease: EASE,
      dur: function (s) { return mq(MQ_MOBILE) ? s * MOBILE_FACTOR : s; },
      enter: enter,
      loadFlip: loadFlip,
      fontsReady: fontsReady,
      decodeAll: decodeAll,
      whenLoaded: whenLoaded,
      own: own,
      onFinal: onFinal,
      skipOnInput: skipOnInput,
      setIntro: function (intro) { P24.intro = intro || null; },
      vt: {
        internalNav: h.classList.contains('vt-nav'),
        supported: !!(P24._vt && P24._vt.supported),
        name: function (el, n) { if (P24._vt) P24._vt.name(el, n); }
      }
    };
    ctx.reveal = function (els, opts) { return P24._reveal ? P24._reveal(ctx, els, opts || {}) : undefined; };
    ctx.heading = function (el, opts) { return P24._type ? P24._type.heading(ctx, el, opts || {}) : undefined; };
    ctx.roll = function (el, text) {
      if (P24._type) return P24._type.roll(ctx, el, text);
      if (el) el.textContent = text;
      return undefined;
    };
    components.forEach(function (c) {
      try { ctx[c.name] = c.factory(ctx); } catch (err) { report('component:' + c.name, err); }
    });
    lazyNames.forEach(function (n) { if (!ctx[n]) ctx[n] = proxy(n); });
    return ctx;
  }

  function runUnits(motionOK) {
    var ctx = makeCtx(motionOK);
    P24.ctx = ctx;
    var cleanups = [];
    units.forEach(function (u) {
      try {
        var c = u.mod.init(ctx);
        if (typeof c === 'function') cleanups.push(c);
      } catch (err) {
        report(u.id, err);
        h.classList.remove('js-motion');
      }
    });
    return function () { cleanups.forEach(function (c) { try { c(); } catch (err) { report('cleanup', err); } }); };
  }

  P24.register = function (id, mod) {
    if (!id || !mod || typeof mod.init !== 'function') throw new Error('P24.register(id, { init }) expects an init function');
    if (units.some(function (u) { return u.id === id; })) throw new Error('P24.register: duplicate id ' + id);
    units.push({ id: id, mod: mod });
  };
  P24.component = function (name, factory) {
    if (!name || typeof factory !== 'function') throw new Error('P24.component(name, factory) expects a factory');
    if (components.some(function (c) { return c.name === name; })) throw new Error('P24.component: duplicate ' + name);
    components.push({ name: name, factory: factory });
    if (LAZY[name]) lazyReady[name] = true;
  };

  function boot() {
    if (P24.booted) return;
    P24.booted = true;
    var g = w.gsap;
    if (!g) { h.classList.remove('js-motion'); runUnits(false); return; }
    if (w.SplitText) g.registerPlugin(w.SplitText);
    g.config({ autoSleep: 60, nullTargetWarn: false });
    g.defaults({ ease: EASE.out, duration: 0.6 });
    var mm = g.matchMedia();
    P24.mm = mm;
    mm.add({ ok: MQ_MOTION, reduce: MQ_REDUCE }, function (c) {
      var ok = !!c.conditions.ok;
      h.classList.toggle('js-motion', ok);
      return runUnits(ok);
    });
  }

  P24.ease = EASE;
  P24.loadFlip = loadFlip;
  P24.finish = runFinals;

  if (qa) {
    w.__p24 = {
      seek: function (t) {
        var i = P24.intro;
        if (!i || !i.timeline) return false;
        i.timeline.pause();
        i.timeline.seek(Number(t) || 0, false);
        return true;
      },
      state: function () {
        return {
          booted: !!P24.booted,
          motion: h.classList.contains('js-motion'),
          classes: h.className,
          intro: !!P24.intro,
          vtLog: (P24.vtLog || []).slice(),
          errors: errors.slice()
        };
      },
      finish: runFinals
    };
  }

  if (d.readyState === 'loading') d.addEventListener('DOMContentLoaded', boot, { once: true });
  else setTimeout(boot, 0);
})(window, document);

(function (w) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};

  function list(x) {
    if (!x) return [];
    if (x.nodeType === 1) return [x];
    return Array.prototype.slice.call(x);
  }

  function lines(ctx, el, opts) {
    if (ctx.heading) { ctx.heading(el, { rootMargin: opts.rootMargin }); return; }
    var g = ctx.gsap;
    var ST = ctx.SplitText;
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () { g.set(el, { autoAlpha: 0 }); },
      play: function () {
        g.set(el, { autoAlpha: 1 });
        if (!ST) { g.from(el, { y: ctx.mobile ? 12 : 20, autoAlpha: 0, duration: ctx.dur(0.7) }); return; }
        var split = ST.create(el, { type: 'lines', mask: 'lines', linesClass: 'p24-line', aria: 'auto' });
        g.from(split.lines, {
          yPercent: 110,
          duration: ctx.dur(0.7),
          stagger: 0.08,
          ease: ctx.ease.out,
          onComplete: function () { split.revert(); }
        });
      },
      final: function () { g.set(el, { clearProps: 'opacity,visibility' }); }
    });
  }

  function photo(ctx, el, opts) {
    var g = ctx.gsap;
    var frame = el.classList.contains('p24-frame') ? el : el.querySelector('.p24-frame') || el;
    var img = frame.querySelector('img, video');
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () {
        g.set(frame, { clipPath: 'inset(100% 0% 0% 0%)' });
        if (img) g.set(img, { scale: 1.06, transformOrigin: '50% 100%' });
      },
      play: function () {
        var open = function () {
          var d = ctx.dur(0.8);
          g.to(frame, { clipPath: 'inset(0% 0% 0% 0%)', duration: d, ease: ctx.ease.out, clearProps: 'clipPath' });
          if (img) g.to(img, { scale: 1, duration: d, ease: ctx.ease.out, clearProps: 'transform' });
        };
        if (!img || img.tagName !== 'IMG' || !ctx.decodeAll) { open(); return; }
        if (img.loading === 'lazy') img.loading = 'eager';
        ctx.decodeAll([img], 900).then(function (ok) {
          if (ok) { open(); return; }
          g.set(frame, { clearProps: 'clipPath' });
          g.set(img, { clearProps: 'transform' });
        });
      },
      final: function () {
        g.set(frame, { clearProps: 'clipPath' });
        if (img) g.set(img, { clearProps: 'transform' });
      }
    });
  }

  function group(ctx, el, opts) {
    var g = ctx.gsap;
    var kids = Array.prototype.slice.call(el.children);
    if (!kids.length) return;
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () { g.set(kids, { y: ctx.mobile ? 12 : 16, autoAlpha: 0 }); },
      play: function () {
        g.to(kids, {
          y: 0,
          autoAlpha: 1,
          duration: ctx.dur(0.7),
          stagger: opts.stagger == null ? 0.06 : opts.stagger,
          ease: ctx.ease.out,
          clearProps: 'transform,opacity,visibility'
        });
      },
      final: function () { g.set(kids, { clearProps: 'transform,opacity,visibility' }); }
    });
  }

  P24._reveal = function (ctx, els, opts) {
    if (!ctx.motionOK || !ctx.gsap) return;
    var type = opts.type || 'group';
    list(els).forEach(function (el) {
      if (type === 'lines') lines(ctx, el, opts);
      else if (type === 'photo') photo(ctx, el, opts);
      else group(ctx, el, opts);
    });
  };
})(window);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var ROLL_TRAVEL = 8;

  function hasDeva(el) { return !!(el.closest('[lang="hi"]') || el.querySelector('[lang="hi"]')); }

  function rise(ctx, el, done) {
    var g = ctx.gsap;
    var ST = ctx.SplitText;
    var dur = ctx.mobile ? 0.6 : 0.7;
    g.set(el, { autoAlpha: 1 });
    if (!ST || hasDeva(el)) {
      g.from(el, { y: ctx.mobile ? 12 : 20, autoAlpha: 0, duration: dur, ease: ctx.ease.out, clearProps: 'transform,opacity,visibility', onComplete: done });
      return;
    }
    var tween = null;
    var split = ST.create(el, {
      type: 'lines',
      mask: 'lines',
      linesClass: 'p24-line',
      aria: 'auto'
    });
    tween = g.from(split.lines, {
      yPercent: 110,
      duration: dur,
      stagger: 0.08,
      ease: ctx.ease.out,
      onComplete: function () { split.revert(); if (done) done(); }
    });
    return split;
  }

  function heading(ctx, el, opts) {
    if (!el || !ctx.motionOK || !ctx.gsap) return;
    var g = ctx.gsap;
    if (opts.now) {
      if (ctx.internalNav) return;
      if (w.getComputedStyle(el).opacity !== '0') return;
      ctx.own(el);
      rise(ctx, el);
      return;
    }
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () { g.set(el, { autoAlpha: 0 }); },
      play: function () { rise(ctx, el); },
      final: function () { g.set(el, { clearProps: 'opacity,visibility' }); }
    });
  }

  function roll(ctx, el, text) {
    if (!el) return;
    text = text == null ? '' : String(text);
    if (el._p24roll) { el._p24roll.progress(1); el._p24roll = null; }
    var oldText = el.textContent;
    if (oldText === text) return;
    var g = ctx.gsap;
    if (!ctx.motionOK || !g || !el.isConnected || !oldText) { el.textContent = text; return; }
    el.classList.add('p24-roll');
    el.textContent = '';
    var next = d.createElement('span');
    next.className = 'p24-roll__new';
    next.textContent = text;
    var ghost = d.createElement('span');
    ghost.className = 'p24-roll__old';
    ghost.setAttribute('aria-hidden', 'true');
    ghost.textContent = oldText;
    el.appendChild(next);
    el.appendChild(ghost);
    var dur = ctx.dur(0.3);
    el._p24roll = g.timeline({
      onComplete: function () { el.textContent = text; el.classList.remove('p24-roll'); el._p24roll = null; }
    })
      .to(ghost, { y: -ROLL_TRAVEL, autoAlpha: 0, duration: dur * 0.7, ease: 'power2.in' }, 0)
      .from(next, { y: ROLL_TRAVEL, autoAlpha: 0, duration: dur, ease: ctx.ease.ui }, dur * 0.3);
  }

  P24._type = { heading: heading, roll: roll };
})(window, document);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var lastLink = null;
  var NAMES = { 'cta-panel': 1, 'family-hero': 1 };

  function visible(el) {
    if (!el) return false;
    var r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0 && r.bottom > 0 && r.top < w.innerHeight;
  }

  function sourceFor(link, name) {
    if (name === 'cta-panel') return link;
    var sel = link.getAttribute('data-vt-source');
    if (sel) { var s = d.querySelector(sel); if (visible(s)) return s; }
    var node = link.parentElement;
    while (node && node !== d.body) {
      var stages = node.querySelectorAll('[data-story-stage]');
      for (var i = 0; i < stages.length; i++) {
        var win = stages[i].querySelector('.p24-story__window') || stages[i];
        if (visible(win)) return win;
      }
      node = node.parentElement;
    }
    return null;
  }

  function showKeyFrame(link, win) {
    var block = link.closest('[data-story-block]');
    if (!block || !win || !win.classList.contains('p24-story__window')) return;
    var key = block.getAttribute('data-story-key');
    if (!key) { var st = block.querySelector('[data-story-step]'); key = st ? (st.getAttribute('data-story-step') || '').split(/\s+/)[0] : ''; }
    var layer = key ? win.querySelector('.p24-story__layer[data-frame="' + key + '"]') : null;
    if (!layer || !layer.style.width) return;
    var img = layer.querySelector('img');
    if (img && !img.complete) return;
    var all = win.querySelectorAll('.p24-story__layer');
    for (var i = 0; i < all.length; i++) {
      if (all[i].getAnimations) all[i].getAnimations().forEach(function (an) { an.cancel(); });
      if (all[i] !== layer) all[i].classList.remove('is-on', 'is-top');
    }
    if (win.getAnimations) win.getAnimations().forEach(function (an) { an.cancel(); });
    layer.classList.add('is-on');
    layer.style.clipPath = '';
    var area = win.parentElement || win;
    var l = parseFloat(layer.style.left) || 0, t = parseFloat(layer.style.top) || 0;
    var lw = parseFloat(layer.style.width) || 0, lh = parseFloat(layer.style.height) || 0;
    win.style.clipPath = 'inset(' + t + 'px ' + Math.max(0, area.clientWidth - l - lw) + 'px ' + Math.max(0, area.clientHeight - t - lh) + 'px ' + l + 'px)';
  }

  function name(el, n) {
    if (!el || !n) return;
    var prev = d.querySelectorAll('[data-vt-named]');
    for (var i = 0; i < prev.length; i++) {
      if (prev[i].style.viewTransitionName === n) { prev[i].style.viewTransitionName = ''; prev[i].removeAttribute('data-vt-named'); }
    }
    el.style.viewTransitionName = n;
    el.setAttribute('data-vt-named', '');
  }
  function clearAll() {
    var named = d.querySelectorAll('[data-vt-named]');
    for (var i = 0; i < named.length; i++) { named[i].style.viewTransitionName = ''; named[i].removeAttribute('data-vt-named'); }
  }

  d.addEventListener('click', function (e) {
    var a = e.target && e.target.closest ? e.target.closest('a[href]') : null;
    lastLink = a && a.hasAttribute('data-vt') ? a : null;
  }, true);

  w.addEventListener('pageswap', function (e) {
    var vt = e.viewTransition;
    try { w.sessionStorage.removeItem('p24-vt'); } catch (err) { /* storage off: pairs are skipped */ }
    if (!vt) return;
    try {
      clearAll();
      var link = lastLink;
      lastLink = null;
      var entry = e.activation && e.activation.entry;
      if (!link || !entry || link.href !== entry.url) return;
      var n = link.getAttribute('data-vt');
      if (!NAMES[n]) return;
      var src = sourceFor(link, n);
      if (!visible(src)) return;
      if (n === 'family-hero') showKeyFrame(link, src);
      name(src, n);
      w.sessionStorage.setItem('p24-vt', n);
      if (d.documentElement.classList.contains('qa')) {
        var r = src.getBoundingClientRect();
        w.sessionStorage.setItem('p24-vtlog', JSON.stringify({ name: n, source: src.tagName.toLowerCase() + '.' + String(src.className).split(' ')[0], rect: [Math.round(r.left), Math.round(r.top), Math.round(r.width), Math.round(r.height)], url: entry.url }));
      }
    } catch (err) {
      vt.skipTransition();
    }
  });

  w.addEventListener('pageshow', function (e) { if (e.persisted) { clearAll(); lastLink = null; } });

  P24._vt = {
    name: name,
    clear: clearAll,
    internalNav: function () { return d.documentElement.classList.contains('vt-nav'); },
    supported: typeof d.startViewTransition === 'function' && !!w.CSS && CSS.supports('view-transition-name: none')
  };
})(window, document);

(function (w, d) {
  'use strict';
  var h = d.documentElement;
  var body = d.body;
  var hasIO = 'IntersectionObserver' in w;
  function each(sel, fn) { Array.prototype.forEach.call(d.querySelectorAll(sel), fn); }

  var page = body.getAttribute('data-page');
  each('[data-nav]', function (a) {
    if (page && a.getAttribute('data-nav') === page) a.setAttribute('aria-current', 'page');
  });

  var menuBtn = d.querySelector('[data-menu-open]');
  var menu = d.getElementById('p24-menu');
  if (menuBtn && menu && typeof menu.showModal === 'function') {
    var closeBtn = menu.querySelector('[data-menu-close]');
    var setOpen = function (open) {
      if (open && !menu.open) menu.showModal();
      if (!open && menu.open) menu.close();
      menuBtn.setAttribute('aria-expanded', String(open));
    };
    menuBtn.addEventListener('click', function () { setOpen(true); });
    if (closeBtn) closeBtn.addEventListener('click', function () { setOpen(false); });
    menu.addEventListener('close', function () {
      menuBtn.setAttribute('aria-expanded', 'false');
      menuBtn.focus({ preventScroll: true });
    });
    menu.addEventListener('click', function (e) {
      var a = e.target.closest('a');
      if (a && a.getAttribute('href').charAt(0) === '#') setOpen(false);
    });
    var closedOnHide = false;
    var reset = function () {
      menuBtn.setAttribute('aria-expanded', 'false');
      menuBtn.textContent = 'Menu';
      if (menu.open) menu.close();
    };
    w.addEventListener('pagehide', function () { if (menu.open) { closedOnHide = true; reset(); } });
    w.addEventListener('pageshow', function (e) {
      if (!e.persisted) return;
      var was = closedOnHide || menu.open;
      closedOnHide = false;
      reset();
      if (was) menuBtn.focus({ preventScroll: true });
    });
    var mqWide = w.matchMedia('(min-width: 761px)');
    var onWide = function () { if (mqWide.matches) setOpen(false); };
    if (mqWide.addEventListener) mqWide.addEventListener('change', onWide);
  } else if (menuBtn) {
    menuBtn.addEventListener('click', function () { var f = d.getElementById('p24-footer-pages'); if (f) f.scrollIntoView(); });
  }

  var dock = d.querySelector('[data-dock]');
  if (dock && !body.hasAttribute('data-no-dock')) {
    var sentinels = d.querySelectorAll('[data-dock-sentinel]');
    var footerCta = d.querySelector('[data-footer-cta]');
    var state = { sentinel: sentinels.length > 0, footer: false, typing: false };
    d.addEventListener('p24:dock', function () { render(); });
    var links = dock.querySelectorAll('a, button');
    var render = function () {
      var show = !state.sentinel && !state.footer && !state.typing && !h.classList.contains('story-stuck');
      if (show) dock.setAttribute('data-show', ''); else dock.removeAttribute('data-show');
      h.classList.toggle('dock-on', show);
      dock.setAttribute('aria-hidden', String(!show));
      Array.prototype.forEach.call(links, function (l) { l.tabIndex = show ? 0 : -1; });
    };
    if (hasIO && sentinels.length) {
      var seen = new Set();
      var ioS = new IntersectionObserver(function (entries) {
        entries.forEach(function (e) {
          if (e.isIntersecting && e.intersectionRatio >= 0.99) seen.add(e.target); else seen.delete(e.target);
        });
        state.sentinel = seen.size > 0;
        render();
      }, { threshold: [0, 0.99, 1] });
      Array.prototype.forEach.call(sentinels, function (s) { ioS.observe(s); });
    }
    if (hasIO && footerCta) {
      new IntersectionObserver(function (entries) {
        state.footer = entries[0].isIntersecting;
        render();
      }).observe(footerCta);
    }
    d.addEventListener('focusin', function (e) {
      state.typing = !!(e.target.closest && e.target.closest('input, select, textarea'));
      render();
    });
    render();
  }

  each('[data-replay-opening]', function (a) {
    a.addEventListener('click', function (e) {
      if (e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
      e.preventDefault();
      if ('scrollRestoration' in w.history) w.history.scrollRestoration = 'manual';
      w.scrollTo(0, 0);
      w.location.reload();
    });
  });

  if (h.classList.contains('qa')) {
    var qaBox = d.createElement('pre');
    qaBox.className = 'p24-qa';
    qaBox.setAttribute('aria-hidden', 'true');
    var draw = function () {
      var P24 = w.P24 || {};
      var NL = String.fromCharCode(10);
      qaBox.textContent = 'P24 QA · ' + h.className + NL + (P24.vtLog || []).map(function (x) { return JSON.stringify(x); }).join(NL);
    };
    draw();
    body.appendChild(qaBox);
    setTimeout(draw, 1200);
  }
})(window, document);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var h = d.documentElement;
  var MANIFEST = 'media/manifest.json';
  var AUDIO_CHIP = '[AUDIO — AWAITING REVIEW]';
  var TRANSCRIPT_CHIP = '[TRANSCRIPT — TO BE PREPARED AND APPROVED]';
  var PREVIEW_DELAY_MS = 150;
  var PREVIEW_STOP_S = 4;
  var SLIDE_PX = 40;
  var READY_MS = 400;
  var CONTROLS_MS = 1500;

  var manifestPromise = null;
  var dlg = null;
  var ui = {};
  var current = null;
  var busy = false;
  var previewStops = [];
  var ctlTimer = 0;

  d.addEventListener('play', function (e) {
    var v = e.target;
    Array.prototype.forEach.call(d.querySelectorAll('video'), function (o) { if (o !== v && !o.paused) o.pause(); });
  }, true);

  function getManifest() {
    if (!manifestPromise) {
      manifestPromise = fetch(MANIFEST, { credentials: 'same-origin' })
        .then(function (r) { if (!r.ok) throw new Error('manifest ' + r.status); return r.json(); })
        .catch(function (err) { manifestPromise = null; throw err; });
    }
    return manifestPromise;
  }
  function clipList(m) { return Array.isArray(m.clips) ? m.clips : Object.keys(m.clips || {}).map(function (k) { return m.clips[k]; }); }
  function findClip(m, id) {
    var list = clipList(m);
    for (var i = 0; i < list.length; i++) if (list[i].id === id) return list[i];
    return null;
  }

  function mobile() { return w.matchMedia('(max-width: 760px)').matches; }
  function scrimAlpha() { return mobile() ? 1 : 0.96; }
  function motionOK() { return h.classList.contains('js-motion') && !!w.gsap; }
  function approved(c) { return /^approved\b/i.test(c.audioStatus || '') && !!c.srcAudio; }
  function lite() { var c = w.navigator.connection; return !!(c && (c.saveData || /^(slow-2g|2g|3g)$/.test(c.effectiveType || ''))); }

  function el(tag, cls, text) {
    var n = d.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  }
  function btn(cls, text) {
    var b = el('button', 'p24-player__ctl ' + (cls || ''), text);
    b.type = 'button';
    return b;
  }

  function groupName(trigger, opts) {
    if (opts && opts.group) return opts.group;
    var g = trigger.closest('[data-group]');
    return g ? g.getAttribute('data-group') : null;
  }
  function groupMembers(name) {
    if (!name) return [];
    var seen = {};
    var out = [];
    Array.prototype.forEach.call(d.querySelectorAll('[data-clip]'), function (t) {
      var gEl = t.closest('[data-group]');
      if (!gEl || gEl.getAttribute('data-group') !== name) return;
      var row = t.closest('li');
      if (row && !row.getClientRects().length) return;
      var id = t.getAttribute('data-clip');
      if (seen[id]) return;
      seen[id] = true;
      out.push(t);
    });
    return out;
  }

  function build() {
    if (dlg) return;
    dlg = el('dialog', 'p24-player');
    dlg.setAttribute('aria-labelledby', 'p24-player-title');

    var bar = el('div', 'p24-player__bar');
    ui.close = btn('p24-player__ctl--close', 'Close');
    ui.sound = el('span', 'p24-player__sound');
    ui.captions = btn('', 'Captions');
    ui.captions.setAttribute('aria-pressed', 'true');
    bar.appendChild(ui.close);
    bar.appendChild(ui.sound);
    bar.appendChild(ui.captions);

    var body = el('div', 'p24-player__body');
    ui.media = el('div', 'p24-player__media');
    ui.video = el('video');
    ui.video.muted = true;
    ui.video.setAttribute('muted', '');
    ui.video.playsInline = true;
    ui.video.setAttribute('playsinline', '');
    ui.video.controls = true;
    ui.video.preload = 'metadata';
    ui.video.setAttribute('controlslist', 'nodownload noplaybackrate noremoteplayback');
    ui.video.setAttribute('disablepictureinpicture', '');
    ui.track = el('track');
    ui.track.kind = 'captions';
    ui.track.srclang = 'en';
    ui.track.label = 'English';
    ui.video.appendChild(ui.track);
    ui.media.appendChild(ui.video);

    var meta = el('div', 'p24-player__meta');
    ui.title = el('h2', 'p24-player__title');
    ui.title.id = 'p24-player-title';
    ui.facts = el('dl', 'p24-player__facts');
    ui.notes = el('div', 'p24-player__notes');
    var cta = el('a', 'p24-link-arrow', 'Request availability →');
    cta.href = 'enquire.html#availability';
    cta.setAttribute('data-vt', 'cta-panel');
    meta.appendChild(ui.title);
    meta.appendChild(ui.facts);
    meta.appendChild(ui.notes);
    meta.appendChild(cta);

    ui.nav = el('div', 'p24-player__nav');
    ui.prev = btn('p24-player__step', '← Previous clip');
    ui.next = btn('p24-player__step', 'Next clip →');
    ui.nav.appendChild(ui.prev);
    ui.nav.appendChild(ui.next);
    meta.appendChild(ui.nav);

    body.appendChild(ui.media);
    body.appendChild(meta);
    dlg.appendChild(bar);
    dlg.appendChild(body);
    d.body.appendChild(dlg);

    ui.close.addEventListener('click', close);
    ui.prev.addEventListener('click', function () { step(-1); });
    ui.next.addEventListener('click', function () { step(1); });
    dlg.addEventListener('cancel', function (e) { e.preventDefault(); close(); });
    dlg.addEventListener('keydown', onKey);
    ui.captions.addEventListener('click', function () {
      var on = ui.captions.getAttribute('aria-pressed') !== 'true';
      ui.captions.setAttribute('aria-pressed', String(on));
      captionsMode(on);
    });
  }

  function onKey(e) {
    if (e.key !== 'ArrowLeft' && e.key !== 'ArrowRight') return;
    var a = d.activeElement;
    if (a && (/^(VIDEO|INPUT|SELECT|TEXTAREA)$/.test(a.tagName) || a.getAttribute('role') === 'slider')) return;
    if (!current || !current.group.length) return;
    e.preventDefault();
    step(e.key === 'ArrowLeft' ? -1 : 1);
  }

  function fact(label, value) {
    var row = el('div');
    row.appendChild(el('dt', null, label));
    row.appendChild(el('dd', null, value));
    return row;
  }

  function resetTrack(c) {
    var old = ui.track;
    if (old && old.track) old.track.mode = 'disabled';
    if (old && old.parentNode) old.parentNode.removeChild(old);
    ui.track = el('track');
    ui.track.kind = 'captions';
    ui.track.srclang = 'en';
    ui.track.label = 'English';
    ui.track.default = true;
    if (c.vtt) ui.track.src = c.vtt;
    ui.video.appendChild(ui.track);
  }
  function captionsMode(on) { if (ui.track && ui.track.track) ui.track.track.mode = on ? 'showing' : 'hidden'; }
  function controlsOff() {
    var v = ui.video;
    clearTimeout(ctlTimer);
    v.controls = false;
    v.addEventListener('playing', controlsOn, { once: true });
    ctlTimer = setTimeout(controlsOn, CONTROLS_MS);
  }
  function controlsOn() { clearTimeout(ctlTimer); if (ui.video) ui.video.controls = true; }
  function posterReady(c) {
    if (!c.poster || typeof Image === 'undefined') return Promise.resolve();
    var img = new Image();
    img.src = c.poster;
    var dec = img.decode ? img.decode().catch(function () { /* shows when it loads */ }) : Promise.resolve();
    return Promise.race([dec, new Promise(function (r) { setTimeout(r, READY_MS); })]);
  }

  function fill(c, animateTitle) {
    fillMeta(c, animateTitle);
    fillMedia(c);
  }
  function fillMeta(c, animateTitle) {
    var title = c.event || c.title || 'Clip';
    if (animateTitle && P24.ctx && P24.ctx.roll) P24.ctx.roll(ui.title, title);
    else ui.title.textContent = title;
    ui.facts.textContent = '';
    ui.facts.appendChild(fact('Client', c.client || 'Client not named'));
    if (c.place) ui.facts.appendChild(fact('Place', c.place));
    if (c.dateLabel || c.date) ui.facts.appendChild(fact('Date', c.dateLabel || c.date));

    ui.notes.textContent = '';
    if (/placeholder/i.test(c.captionsStatus || '') && c.hasAudio) ui.notes.appendChild(el('span', 'p24-ph', TRANSCRIPT_CHIP));

    ui.sound.textContent = '';
    if (approved(c)) {
      var s = btn('', 'Sound on');
      s.setAttribute('aria-pressed', 'false');
      s.addEventListener('click', function () { soundOn(c, s); });
      ui.sound.appendChild(s);
    } else if (c.hasAudio) {
      var dis = btn('', 'Sound on');
      dis.disabled = true;
      ui.sound.appendChild(dis);
      ui.sound.appendChild(d.createTextNode(' '));
      ui.sound.appendChild(el('span', 'p24-ph', AUDIO_CHIP));
    } else {
      ui.sound.appendChild(el('span', 'p24-player__nosound', 'No sound'));
    }

    ui.captions.hidden = !c.vtt;
  }
  function fillMedia(c) {
    var v = ui.video;
    controlsOff();
    v.poster = c.poster || '';
    if (c.w && c.h) { v.width = c.w; v.height = c.h; v.style.setProperty('--clip-w', c.w + 'px'); }
    v.setAttribute('aria-label', c.alt || c.posterAlt || '');
    resetTrack(c);
    v.src = c.src;
    if (c.inPoint) v.addEventListener('loadedmetadata', function () { try { v.currentTime = c.inPoint; } catch (e) { /* not seekable yet */ } }, { once: true });
    var capsOn = !/placeholder/i.test(c.captionsStatus || '');
    ui.captions.setAttribute('aria-pressed', String(capsOn));
    captionsMode(capsOn);
  }

  function soundOn(c, button) {
    var v = ui.video;
    var on = button.getAttribute('aria-pressed') !== 'true';
    var t = v.currentTime;
    v.src = on ? c.srcAudio : c.src;
    v.addEventListener('loadedmetadata', function () {
      try { v.currentTime = t; } catch (e) { /* not seekable yet */ }
      v.muted = !on;
      var p = v.play();
      if (p && p.catch) p.catch(function () { /* stays paused; the native controls remain */ });
    }, { once: true });
    button.setAttribute('aria-pressed', String(on));
    button.textContent = on ? 'Sound off' : 'Sound on';
  }

  function flipSource(trigger) {
    return trigger.closest('[data-flip-id]') || trigger.querySelector('[data-flip-id]') || trigger;
  }
  function play() {
    var p = ui.video.play();
    if (p && p.catch) p.catch(function () { controlsOn(); /* autoplay refused: the poster and native controls remain */ });
  }

  function updateNav(m) {
    var grp = current.group;
    var i = current.index;
    var show = grp.length > 1;
    ui.nav.hidden = !show;
    if (!show) return;
    var prevT = grp[(i - 1 + grp.length) % grp.length];
    var nextT = grp[(i + 1) % grp.length];
    var pc = findClip(m, prevT.getAttribute('data-clip'));
    var nc = findClip(m, nextT.getAttribute('data-clip'));
    ui.prev.setAttribute('aria-label', 'Previous clip: ' + (pc ? pc.event || pc.title || pc.id : ''));
    ui.next.setAttribute('aria-label', 'Next clip: ' + (nc ? nc.event || nc.title || nc.id : ''));
  }

  function step(dir) {
    if (!current || busy || current.group.length < 2) return;
    var grp = current.group;
    var i = (current.index + dir + grp.length) % grp.length;
    var trigger = grp[i];
    busy = true;
    getManifest().then(function (m) {
      var c = findClip(m, trigger.getAttribute('data-clip'));
      if (!c) { busy = false; return; }
      var g = w.gsap;
      var swap = function () {
        ui.video.pause();
        current.clip = c;
        current.trigger = trigger;
        current.returnFocus = null;
        current.source = flipSource(trigger);
        current.index = i;
        fill(c, motionOK());
        updateNav(m);
        play();
      };
      posterReady(c).then(function () {
        if (!current) { busy = false; return; }
        if (!motionOK()) { swap(); busy = false; return; }
        g.timeline({ onComplete: function () { busy = false; } })
          .to(ui.media, { x: -dir * SLIDE_PX, autoAlpha: 0, duration: 0.18, ease: 'power2.in' })
          .call(swap)
          .fromTo(ui.media, { x: dir * SLIDE_PX, autoAlpha: 0 }, { x: 0, autoAlpha: 1, duration: 0.27, ease: P24.ease ? P24.ease.inOut : 'power3.inOut', clearProps: 'transform,opacity,visibility' });
      });
    }, function () { busy = false; });
  }

  function show(c, trigger, m, grpName, opts) {
    build();
    previewStops.forEach(function (f) { f(); });
    var source = (opts && opts.flipFrom) || flipSource(trigger);
    var grp = groupMembers(grpName);
    var idx = -1;
    for (var k = 0; k < grp.length; k++) if (grp[k].getAttribute('data-clip') === c.id) idx = k;
    current = { clip: c, trigger: trigger, source: source, group: idx > -1 ? grp : [], index: Math.max(0, idx), returnFocus: (opts && opts.returnFocus) || null };
    fill(c, false);
    updateNav(m);
    ui.media.setAttribute('data-flip-id', source.getAttribute('data-flip-id') || ('clip-' + c.id));
    var g = w.gsap;

    if (motionOK() && w.Flip) {
      var state = w.Flip.getState(source);
      dlg.setAttribute('data-phase', 'opening');
      dlg.showModal();
      play();
      g.fromTo(dlg, { backgroundColor: 'rgba(252,251,249,0)' }, { backgroundColor: 'rgba(252,251,249,' + scrimAlpha() + ')', duration: 0.3, ease: 'power2.out' });
      w.Flip.from(state, {
        targets: ui.media,
        scale: true,
        duration: 0.6,
        ease: 'power3.inOut',
        onComplete: function () { dlg.setAttribute('data-phase', 'open'); busy = false; }
      });
      return;
    }
    dlg.setAttribute('data-phase', 'open');
    dlg.showModal();
    play();
    if (g) g.fromTo(dlg, { opacity: 0 }, { opacity: 1, duration: 0.15, ease: 'none', clearProps: 'opacity', onComplete: function () { busy = false; } });
    else busy = false;
  }

  function open(trigger, opts) {
    if (!trigger || busy || (dlg && dlg.open)) return Promise.resolve(false);
    var id = (opts && opts.clip) || trigger.getAttribute('data-clip');
    if (!id) return Promise.resolve(false);
    busy = true;
    var needFlip = motionOK() && !w.Flip;
    return Promise.all([getManifest(), needFlip ? P24.loadFlip().catch(function () { return null; }) : null])
      .then(function (res) {
        var c = findClip(res[0], id);
        if (!c) throw new Error('No clip "' + id + '" in ' + MANIFEST);
        show(c, trigger, res[0], groupName(trigger, opts), opts);
        return true;
      })
      .catch(function (err) {
        busy = false;
        if (trigger.href) w.location.href = trigger.href;
        setTimeout(function () { throw err; }, 0);
        return false;
      });
  }

  function finishClose() {
    var c = current;
    dlg.close();
    dlg.removeAttribute('data-phase');
    if (w.gsap) w.gsap.set([ui.media, dlg], { clearProps: 'all' });
    ui.video.pause();
    ui.video.removeAttribute('src');
    ui.video.load();
    controlsOn();
    current = null;
    busy = false;
    var back = c && (c.returnFocus && c.returnFocus.isConnected ? c.returnFocus : c.trigger);
    if (back && back.isConnected) back.focus({ preventScroll: true });
  }

  function close() {
    if (!dlg || !dlg.open || !current || busy) return;
    busy = true;
    ui.video.pause();
    clearTimeout(ctlTimer);
    ui.video.controls = false;
    ui.video.removeAttribute('src');
    ui.video.load();
    var g = w.gsap;
    var src = current.source;
    var r = src && src.isConnected ? src.getBoundingClientRect() : null;
    var onScreen = r && r.width > 0 && r.bottom > 0 && r.top < w.innerHeight;
    if (motionOK() && w.Flip && onScreen) {
      dlg.setAttribute('data-phase', 'opening');
      g.to(dlg, { backgroundColor: 'rgba(252,251,249,0)', duration: 0.45, ease: 'power2.out' });
      w.Flip.fit(ui.media, src, { scale: true, duration: 0.45, ease: 'power3.inOut', onComplete: finishClose });
      return;
    }
    if (g) g.to(dlg, { opacity: 0, duration: 0.15, ease: 'none', onComplete: finishClose });
    else finishClose();
  }

  function rail(video, list) {
    if (!video || !list) return function () {};
    var items = Array.prototype.slice.call(list.querySelectorAll('[data-in]'));
    var active = null;
    var label = el('span', 'p24-rail__now', 'Now showing');
    items.forEach(function (it) {
      if (!it.querySelector('.p24-rail__bar')) {
        var b = el('span', 'p24-rail__bar');
        b.setAttribute('aria-hidden', 'true');
        it.appendChild(b);
      }
    });
    function range(it) { return [parseFloat(it.getAttribute('data-in')) || 0, parseFloat(it.getAttribute('data-out')) || 0]; }
    function barOf(it) { return it.querySelector('.p24-rail__bar'); }
    function jump(it, p) {
      var b = barOf(it);
      b.style.transition = 'none';
      b.style.transform = 'scaleX(' + p + ')';
      void b.offsetWidth;
      b.style.transition = '';
    }
    function setActive(it) {
      if (active === it) return;
      if (active) { active.removeAttribute('aria-current'); jump(active, 0); }
      active = it;
      if (!it) { if (label.parentNode) label.remove(); return; }
      it.setAttribute('aria-current', 'true');
      (it.querySelector('[data-rail-label]') || it).appendChild(label);
      var r = range(it);
      jump(it, Math.max(0, Math.min(1, (video.currentTime - r[0]) / Math.max(0.1, r[1] - r[0]))));
    }
    function onTime() {
      var t = video.currentTime;
      var hit = null;
      items.forEach(function (it) { var r = range(it); if (t >= r[0] && t < r[1]) hit = it; });
      setActive(hit);
      if (!hit) return;
      var r = range(hit);
      barOf(hit).style.transform = 'scaleX(' + Math.max(0, Math.min(1, (t - r[0]) / Math.max(0.1, r[1] - r[0]))) + ')';
    }
    function onSeek() { if (active) { var r = range(active); jump(active, Math.max(0, Math.min(1, (video.currentTime - r[0]) / Math.max(0.1, r[1] - r[0])))); } onTime(); }
    function onClick(e) {
      var it = e.target.closest('[data-in]');
      if (!it || !list.contains(it) || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
      e.preventDefault();
      var r = range(it);
      try { video.currentTime = r[0] + 0.01; } catch (err) { /* not seekable yet */ }
      setActive(it);
      var p = video.play();
      if (p && p.catch) p.catch(function () { /* stays paused */ });
    }
    video.addEventListener('timeupdate', onTime);
    video.addEventListener('seeking', onSeek);
    list.addEventListener('click', onClick);
    return function () {
      video.removeEventListener('timeupdate', onTime);
      video.removeEventListener('seeking', onSeek);
      list.removeEventListener('click', onClick);
      setActive(null);
    };
  }

  function hoverPreview(root, opts) {
    var sel = (opts && opts.selector) || '[data-clip]';
    if (!root || !motionOK() || lite() || !w.matchMedia('(hover: hover) and (pointer: fine)').matches) return function () {};
    var timer = 0;
    var token = 0;
    var pending = null;
    var live = null;
    function stop() {
      clearTimeout(timer);
      pending = null;
      token++;
      if (!live) return;
      var v = live.video;
      live = null;
      if (!v) return;
      v.pause();
      v.removeAttribute('src');
      v.load();
      v.remove();
    }
    function start(card) {
      stop();
      var mine = token;
      var frame = card.querySelector('[data-flip-id]') || card.closest('[data-flip-id]') || card;
      var src = card.getAttribute('data-preview-src') || (/\.mp4(#.*)?$/.test(card.getAttribute('href') || '') ? card.getAttribute('href') : null);
      var ended = function (v) {
        if (!live || live.video !== v) return;
        stop();
        live = { card: card, video: null };
      };
      var go = function (url, from) {
        if (!url) return;
        var v = el('video', 'p24-preview');
        v.muted = true;
        v.playsInline = true;
        v.setAttribute('muted', '');
        v.setAttribute('playsinline', '');
        v.setAttribute('aria-hidden', 'true');
        v.preload = 'auto';
        v.addEventListener('loadedmetadata', function () {
          if (from > 0) { try { v.currentTime = from; } catch (e) { /* not seekable: plays from 0 */ } }
        }, { once: true });
        v.addEventListener('canplay', function () {
          if (!live || live.video !== v) return;
          v.classList.add('is-on');
          var p = v.play();
          if (p && p.catch) p.catch(function () { /* stays on the poster */ });
        }, { once: true });
        v.addEventListener('timeupdate', function () { if (v.currentTime >= (from || 0) + PREVIEW_STOP_S) ended(v); });
        v.addEventListener('ended', function () { ended(v); });
        v.src = url.split('#')[0];
        frame.appendChild(v);
        live = { card: card, video: v };
      };
      var attrIn = parseFloat(card.getAttribute('data-preview-in'));
      if (src && !isNaN(attrIn)) { go(src, attrIn); return; }
      getManifest().then(function (m) {
        var c = findClip(m, card.getAttribute('data-clip'));
        if (mine !== token) return;
        var from = !isNaN(attrIn) ? attrIn : (c && (c.previewIn || c.inPoint)) || 0;
        go(src || (c && c.src), from);
      }, function () { if (src && mine === token) go(src, 0); });
    }
    function onEnter(e) {
      var card = e.target.closest && e.target.closest(sel);
      if (!card || !root.contains(card) || e.pointerType !== 'mouse') return;
      if ((live && live.card === card) || pending === card) return;
      clearTimeout(timer);
      pending = card;
      timer = setTimeout(function () { pending = null; start(card); }, PREVIEW_DELAY_MS);
    }
    function onLeave(e) {
      var card = e.target.closest && e.target.closest(sel);
      if (!card) return;
      if (e.relatedTarget && card.contains(e.relatedTarget)) return;
      stop();
    }
    root.addEventListener('pointerover', onEnter);
    root.addEventListener('pointerout', onLeave);
    previewStops.push(stop);
    return function () {
      previewStops = previewStops.filter(function (f) { return f !== stop; });
      root.removeEventListener('pointerover', onEnter);
      root.removeEventListener('pointerout', onLeave);
      stop();
    };
  }

  d.addEventListener('click', function (e) {
    var t = e.target.closest && e.target.closest('a[data-clip], button[data-clip]');
    if (!t || e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
    e.preventDefault();
    open(t);
  });
  var warmed = false;
  function warm(e) {
    if (warmed || !e.target.closest || !e.target.closest('[data-clip]')) return;
    warmed = true;
    getManifest().catch(function () { /* retried on open */ });
    if (motionOK()) P24.loadFlip().catch(function () { /* open() falls back to a fade */ });
  }
  d.addEventListener('pointerover', warm, { passive: true });
  d.addEventListener('focusin', warm);
  d.addEventListener('touchstart', warm, { passive: true });

  var api = {
    open: open,
    close: close,
    isOpen: function () { return !!(dlg && dlg.open); },
    manifest: getManifest,
    rail: rail,
    hoverPreview: hoverPreview
  };
  P24.player = api;
  if (P24.component) P24.component('player', function () { return api; });
})(window, document);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var DWELL_MS = 150;
  var HOLD_MS = 700;
  var PAIR_HOLD_MS = 900;
  var WINDOW_MS = 500;
  var FADE_MS = 320;
  var SETTLE_MS = 120;
  var RESIZE_MS = 150;
  var EASE_WINDOW = 'cubic-bezier(.65,0,.35,1)';

  function qsa(root, sel) { return Array.prototype.slice.call(root.querySelectorAll(sel)); }
  function shown(el) { return !!el && el.getClientRects().length > 0; }
  function frames(step) { return (step.getAttribute('data-story-step') || '').split(/\s+/).filter(Boolean); }
  function insetOf(box, area) {
    return 'inset(' + box.top + 'px ' + Math.max(0, area.w - box.left - box.w) + 'px ' + Math.max(0, area.h - box.top - box.h) + 'px ' + box.left + 'px)';
  }

  function factory(ctx) {
    return function story(root, opts) {
      if (!root) return { go: function () {}, destroy: function () {} };
      opts = opts || {};
      var motion = ctx.motionOK;
      var blocks = qsa(root, '[data-story-block]');
      var steps = qsa(root, '[data-story-step]');
      var templates = {};
      qsa(root, 'template[data-story-frame]').forEach(function (t) { templates[t.getAttribute('data-story-frame')] = t; });
      var stages = [];
      var label = d.createElement('span');
      label.className = 'p24-inphoto';
      label.textContent = 'In the photo';
      var state = { marker: null, pending: null, frame: null, stage: null, last: 0, token: 0, pairTimer: 0, dwellTimer: 0, settleTimer: 0, resizeTimer: 0, live: false, forced: null };
      var observers = [];
      var offs = [];
      var markers = blocks.map(function (b) { return { el: b, block: b, step: null }; })
        .concat(steps.map(function (s) { return { el: s, block: s.closest('[data-story-block]'), step: s }; }))
        .sort(function (a, b) { return a.el.compareDocumentPosition(b.el) & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1; });

      function on(t, type, fn, o) { t.addEventListener(type, fn, o); offs.push(function () { t.removeEventListener(type, fn, o); }); }
      function vh() { return w.innerHeight || d.documentElement.clientHeight; }
      function lineFraction() {
        if (typeof opts.readingLine === 'number') return opts.readingLine;
        return ctx.mobile ? 0.6 : 0.5;
      }
      function blockOf(el) { return el.closest('[data-story-block]'); }
      function keyOf(block) {
        var k = block.getAttribute('data-story-key');
        if (k) return k;
        var s = block.querySelector('[data-story-step]');
        return s ? frames(s)[0] : null;
      }
      function stepFor(frameId) {
        for (var i = 0; i < steps.length; i++) if (frames(steps[i]).indexOf(frameId) > -1) return steps[i];
        return null;
      }

      function stageRec(el) {
        for (var i = 0; i < stages.length; i++) if (stages[i].el === el) return stages[i];
        var area = el.querySelector('.p24-story__area');
        if (!area) {
          area = d.createElement('div');
          area.className = 'p24-story__area';
          var win = d.createElement('div');
          win.className = 'p24-story__window';
          area.appendChild(win);
          var stat = el.querySelector('[data-story-static]');
          if (stat && stat.parentNode === el) el.insertBefore(area, stat.nextSibling); else el.insertBefore(area, el.firstChild);
        }
        var rec = { el: el, area: area, win: area.querySelector('.p24-story__window'), layers: {}, cur: null, anims: [] };
        stages.push(rec);
        return rec;
      }
      function stageFor(block) {
        var own = block ? qsa(block, '[data-story-stage]').filter(shown)[0] : null;
        if (own) return stageRec(own);
        var shared = qsa(root, '[data-story-stage]').filter(function (s) { return !blockOf(s) && shown(s); })[0];
        return shared ? stageRec(shared) : null;
      }
      function areaSize(st) { return { w: st.area.clientWidth, h: st.area.clientHeight }; }
      function fit(layer, st) {
        var a = areaSize(st);
        var ar = layer.ar;
        var wd = a.w;
        var ht = a.w / ar;
        if (ht > a.h) { ht = a.h; wd = a.h * ar; }
        wd = Math.round(wd);
        ht = Math.round(ht);
        var anchor = opts.anchor || (ctx.mobile ? 'center' : 'bottom-left');
        var box = { w: wd, h: ht, left: anchor === 'center' ? Math.round((a.w - wd) / 2) : 0, top: anchor === 'center' ? Math.round((a.h - ht) / 2) : a.h - ht };
        layer.box = box;
        var s = layer.el.style;
        s.width = wd + 'px';
        s.height = ht + 'px';
        s.left = box.left + 'px';
        s.top = box.top + 'px';
        return box;
      }
      function layerFor(st, id) {
        if (st.layers[id]) return st.layers[id];
        var t = templates[id];
        if (!t) return null;
        var el = d.createElement('div');
        el.className = 'p24-story__layer';
        el.setAttribute('data-frame', id);
        el.appendChild(t.content.cloneNode(true));
        var img = el.querySelector('img');
        if (!img) return null;
        img.loading = 'eager';
        img.decoding = 'async';
        var clip = t.getAttribute('data-clip');
        if (clip) {
          el.setAttribute('data-flip-id', 'story-' + id);
          var play = d.createElement('a');
          play.className = 'p24-play';
          play.href = t.getAttribute('data-clip-href') || ('media/clips/' + clip + '.mp4');
          play.setAttribute('data-clip', clip);
          play.textContent = 'Play clip';
          play.setAttribute('aria-label', 'Play clip: ' + (t.getAttribute('data-caption') || clip));
          var grp = t.getAttribute('data-group');
          if (grp) el.setAttribute('data-group', grp);
          el.appendChild(play);
        }
        var wAttr = +img.getAttribute('width') || 4;
        var hAttr = +img.getAttribute('height') || 3;
        var layer = { id: id, el: el, img: img, ar: wAttr / hAttr, caption: t.getAttribute('data-caption') || '', ready: null, box: null };
        st.win.appendChild(el);
        fit(layer, st);
        layer.ready = img.decode ? img.decode().then(function () { return true; }, function () { return ctx.whenLoaded(img); }) : ctx.whenLoaded(img);
        st.layers[id] = layer;
        return layer;
      }
      function prefetch(block) {
        var st = stageFor(block);
        if (!st) return;
        var ids = [];
        var key = block ? keyOf(block) : null;
        if (key) ids.push(key);
        (block ? qsa(block, '[data-story-step]') : steps).forEach(function (s) { frames(s).forEach(function (f) { if (ids.indexOf(f) < 0) ids.push(f); }); });
        ids.reduce(function (p, id) {
          return p.then(function () { var l = layerFor(st, id); return l ? l.ready : null; });
        }, Promise.resolve());
      }

      function finishAnims(st) { st.anims.forEach(function (a) { try { a.finish(); } catch (e) { /* already done */ } }); st.anims = []; }

      function settle(st, layer, prev) {
        st.win.style.clipPath = insetOf(layer.box, areaSize(st));
        layer.el.style.clipPath = '';
        if (prev && prev !== layer) prev.el.classList.remove('is-on');
        layer.el.classList.remove('is-top');
      }

      function reshape(st, layer, dir) {
        var prev = st.cur;
        finishAnims(st);
        st.cur = layer;
        layer.el.classList.add('is-on');
        if (!motion || !prev || prev === layer || !st.win.animate) { settle(st, layer, prev); return; }
        var a = areaSize(st);
        layer.el.classList.add('is-top');
        var opt = { duration: WINDOW_MS, easing: EASE_WINDOW, fill: 'forwards' };
        var aw = st.win.animate([{ clipPath: insetOf(prev.box, a) }, { clipPath: insetOf(layer.box, a) }], opt);
        var al = layer.el.animate([{ opacity: 0, transform: 'translateY(' + (dir < 0 ? -16 : 16) + 'px)' }, { opacity: 1, transform: 'none' }], { duration: FADE_MS, easing: 'cubic-bezier(.2,0,0,1)', fill: 'forwards' });
        st.anims = [aw, al];
        aw.finished.then(function () {
          if (st.cur !== layer) return;
          settle(st, layer, prev);
          aw.cancel();
          al.cancel();
          st.anims = [];
        }, function () { /* finished early by an interruption: settle() ran there */ });
      }

      function decorate(layer, block) {
        var st = state.stage;
        var cap = st && st.el.querySelector('[data-story-caption]');
        if (cap) ctx.roll(cap, layer.caption);
        var fam = st && st.el.querySelector('[data-story-family]');
        if (fam && block && block.getAttribute('data-story-label')) ctx.roll(fam, block.getAttribute('data-story-label'));
        var row = stepFor(layer.id);
        if (row) (row.querySelector('[data-story-label]') || row).appendChild(label);
        else if (label.parentNode) label.parentNode.removeChild(label);
        steps.forEach(function (s) { s.classList.toggle('is-pictured', s === row); });
        var key = block ? block.getAttribute('data-story-block') : null;
        qsa(root, '[data-story-strip]').forEach(function (strip) { strip.classList.toggle('is-current', !key || strip.getAttribute('data-story-strip') === key); });
        qsa(root, '[data-story-thumb]').forEach(function (t) {
          var strip = t.closest('[data-story-strip]');
          var on = t.getAttribute('data-story-thumb') === layer.id && (!key || (!!strip && strip.getAttribute('data-story-strip') === key));
          t.classList.toggle('is-active', on);
          if (on) t.setAttribute('aria-current', 'true'); else t.removeAttribute('aria-current');
        });
        blocks.forEach(function (b) { b.classList.toggle('is-active', b === block); });
        if (typeof opts.onChange === 'function') opts.onChange({ frame: layer.id, step: row, block: block });
      }

      function goLive(st, layer) {
        if (!state.live) { state.live = true; root.setAttribute('data-story-live', ''); }
        if (!st.el.hasAttribute('data-story-ready')) {
          st.el.setAttribute('data-story-ready', '');
          qsa(st.el, '[data-story-static]').forEach(function (s) { s.hidden = true; });
        }
        fit(layer, st);
        if (st.cur && st.cur !== layer) fit(st.cur, st);
      }

      function show(frameId, block, dir) {
        var st = stageFor(block);
        if (!st || !frameId) return;
        var layer = layerFor(st, frameId);
        if (!layer) return;
        var token = ++state.token;
        layer.ready.then(function (ok) {
          if (token !== state.token || !ok) return;
          state.stage = st;
          state.frame = frameId;
          state.last = Date.now();
          goLive(st, layer);
          reshape(st, layer, dir || 1);
          decorate(layer, block);
        });
      }

      function candidate() {
        var r = root.getBoundingClientRect();
        if (r.bottom <= 0 || r.top >= vh()) return null;
        var line = vh() * lineFraction();
        var pick = null;
        markers.forEach(function (m) { if (m.el.getBoundingClientRect().top <= line) pick = m; });
        if (!pick) pick = markers[0] || null;
        return pick;
      }
      function sameMarker(a, b) { return !!a && !!b && a.el === b.el; }

      function apply(m, dir) {
        clearTimeout(state.pairTimer);
        state.marker = m;
        if (!m) return;
        var ids = m.step ? frames(m.step) : [keyOf(m.block)];
        show(ids[0], m.block, dir);
        if (ids.length > 1) {
          state.pairTimer = setTimeout(function () {
            if (sameMarker(state.marker, m)) show(ids[1], m.block, 1);
          }, WINDOW_MS + PAIR_HOLD_MS);
        }
      }

      function reconcile() {
        updateStuck();
        if (state.forced) return;
        var m = candidate();
        if (!m || sameMarker(m, state.marker)) { clearTimeout(state.dwellTimer); state.pending = null; return; }
        if (sameMarker(m, state.pending)) return;
        clearTimeout(state.dwellTimer);
        state.pending = m;
        state.dwellTimer = setTimeout(function () {
          state.pending = null;
          var now = candidate();
          if (!now || sameMarker(now, state.marker)) return;
          var wait = HOLD_MS - (Date.now() - state.last);
          if (wait > 0) { state.dwellTimer = setTimeout(function () { state.pending = null; reconcile(); }, wait); state.pending = now; return; }
          var dir = state.marker && (now.el.compareDocumentPosition(state.marker.el) & Node.DOCUMENT_POSITION_FOLLOWING) ? -1 : 1;
          apply(now, dir);
        }, DWELL_MS);
      }

      var stuck = false;
      function updateStuck() {
        var next = false;
        if (ctx.mobile && state.stage && blockOf(state.stage.el)) {
          var s = state.stage.el.getBoundingClientRect();
          var b = blockOf(state.stage.el).getBoundingClientRect();
          var top = parseFloat(w.getComputedStyle(state.stage.el).top) || 0;
          next = s.top <= top + 1 && b.bottom > s.bottom + 8;
        }
        if (next === stuck) return;
        stuck = next;
        d.documentElement.classList.toggle('story-stuck', stuck);
        d.dispatchEvent(new CustomEvent('p24:dock'));
      }

      function onScroll() {
        clearTimeout(state.settleTimer);
        state.forced = null;
        state.settleTimer = setTimeout(reconcile, SETTLE_MS);
      }
      function onResize() {
        clearTimeout(state.resizeTimer);
        state.resizeTimer = setTimeout(function () {
          stages.forEach(function (st) {
            finishAnims(st);
            Object.keys(st.layers).forEach(function (id) { fit(st.layers[id], st); });
            if (st.cur) st.win.style.clipPath = insetOf(st.cur.box, areaSize(st));
          });
          state.marker = null;
          reconcile();
        }, RESIZE_MS);
      }

      function onThumb(e) {
        var t = e.target.closest && e.target.closest('[data-story-thumb]');
        if (!t || !root.contains(t) || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
        var row = stepFor(t.getAttribute('data-story-thumb'));
        if (!row) return;
        e.preventDefault();
        var y = w.scrollY + row.getBoundingClientRect().top - vh() * lineFraction() + 4;
        w.scrollTo({ top: Math.max(0, y), behavior: motion ? 'smooth' : 'auto' });
      }

      if (!('IntersectionObserver' in w)) return { go: function () {}, destroy: function () {} };
      root.classList.add('p24-story');
      var wake = new IntersectionObserver(reconcile, { threshold: [0, 0.25, 0.5, 0.75, 1] });
      wake.observe(root);
      blocks.forEach(function (b) { wake.observe(b); });
      var pct = Math.round(lineFraction() * 100);
      var band = new IntersectionObserver(reconcile, { rootMargin: '-' + Math.max(0, pct - 5) + '% 0px -' + Math.max(0, 95 - pct) + '% 0px' });
      steps.forEach(function (s) { band.observe(s); });
      var pre = new IntersectionObserver(function (entries) {
        entries.forEach(function (e) { if (e.isIntersecting) { pre.unobserve(e.target); prefetch(e.target === root ? null : e.target); } });
      }, { rootMargin: '100% 0px' });
      (blocks.length ? blocks : [root]).forEach(function (b) { pre.observe(b); });
      observers.push(wake, band, pre);
      on(w, 'scroll', onScroll, { passive: true });
      if ('onscrollend' in w) on(w, 'scrollend', reconcile, { passive: true });
      on(w, 'resize', onResize, { passive: true });
      on(root, 'click', onThumb);
      ctx.onFinal(function () { stages.forEach(finishAnims); });

      var initial = candidate() || (blocks[0] ? { el: blocks[0], block: blocks[0], step: null } : (steps[0] ? { el: steps[0], block: null, step: steps[0] } : null));
      if (initial) apply(initial, 1);

      return {
        go: function (frameId) {
          var row = stepFor(frameId);
          state.forced = frameId;
          show(frameId, row ? blockOf(row) : (blocks[0] || null), 1);
        },
        destroy: function () {
          observers.forEach(function (o) { o.disconnect(); });
          offs.forEach(function (f) { f(); });
          [state.pairTimer, state.dwellTimer, state.settleTimer, state.resizeTimer].forEach(clearTimeout);
          stages.forEach(function (st) { finishAnims(st); if (st.area.parentNode) st.area.parentNode.removeChild(st.area); st.el.removeAttribute('data-story-ready'); });
          if (label.parentNode) label.parentNode.removeChild(label);
          qsa(root, '[data-story-static]').forEach(function (s) { s.hidden = false; });
          steps.forEach(function (s) { s.classList.remove('is-pictured'); });
          blocks.forEach(function (b) { b.classList.remove('is-active'); });
          root.removeAttribute('data-story-live');
          root.classList.remove('p24-story');
          if (stuck) { d.documentElement.classList.remove('story-stuck'); d.dispatchEvent(new CustomEvent('p24:dock')); }
        }
      };
    };
  }

  if (P24.component) P24.component('story', factory);
})(window, document);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var INTENT_MS = 150;
  var PREVIEW_STOP_S = 4;

  function factory(ctx) {
    return function slot(listRoot, opts) {
      opts = opts || {};
      var box = opts.slotEl;
      var noop = { destroy: function () {} };
      if (!listRoot || !box || !box.getClientRects().length) return noop;
      var rows = Array.prototype.slice.call(listRoot.querySelectorAll(opts.rows || '[data-slot-row]'));
      if (!rows.length) return noop;
      var mediaSel = opts.media || '[data-slot-media]';
      var g = ctx.gsap;
      var anim = ctx.motionOK && !!g;
      var previews = anim && !ctx.lite && w.matchMedia('(hover: hover) and (pointer: fine)').matches;
      var inner = box.querySelector('.p24-slot__inner');
      if (!inner) { inner = d.createElement('div'); inner.className = 'p24-slot__inner'; box.appendChild(inner); }
      var shownRow = null;
      var marked = null;
      var timer = 0;
      var video = null;
      var offs = [];
      function on(t, type, fn, o) { t.addEventListener(type, fn, o); offs.push(function () { t.removeEventListener(type, fn, o); }); }

      function pane(row) {
        var t = row.querySelector(mediaSel);
        var kind = t ? t.getAttribute('data-kind') : 'none';
        var fig = d.createElement('figure');
        fig.className = 'p24-slot__pane';
        fig.setAttribute('data-kind', kind);
        if (!t || kind === 'none') {
          var s = d.createElement('strong');
          s.textContent = t ? (t.getAttribute('data-title') || '') : '';
          fig.appendChild(s);
          fig.appendChild(d.createTextNode('Text only. No photograph or clip from these events is shown here.'));
          return fig;
        }
        var f = d.createElement(kind === 'clip' ? 'button' : 'a');
        f.className = 'p24-slot__frame';
        f.tabIndex = -1;
        if (kind === 'clip') {
          f.type = 'button';
          f.setAttribute('data-clip', t.getAttribute('data-clip'));
          f.setAttribute('data-flip-id', 'p24-slot');
          f.setAttribute('aria-label', 'Play clip');
        } else {
          f.href = t.getAttribute('href');
          f.setAttribute('data-slot-open', '');
        }
        var pic = t.querySelector('picture, img');
        if (pic) {
          pic = pic.cloneNode(true);
          var img = pic.tagName === 'IMG' ? pic : pic.querySelector('img');
          img.alt = '';
          img.loading = 'eager';
          var sz = Math.round(box.clientWidth || 0);
          if (sz > 0) {
            img.sizes = sz + 'px';
            Array.prototype.forEach.call(pic.querySelectorAll ? pic.querySelectorAll('source') : [], function (so) { so.sizes = sz + 'px'; });
          }
          f.appendChild(pic);
        }
        if (kind === 'clip') {
          var p = d.createElement('span');
          p.className = 'p24-play';
          p.textContent = 'Play clip';
          f.appendChild(p);
        }
        var cap = d.createElement('figcaption');
        cap.className = 'p24-cap p24-cap--wrap';
        cap.textContent = t.getAttribute('data-cap') || '';
        fig.appendChild(f);
        fig.appendChild(cap);
        return fig;
      }

      function stopVideo() {
        clearTimeout(timer);
        if (!video) return;
        video.pause();
        video.removeAttribute('src');
        video.load();
        video.remove();
        video = null;
      }
      function startVideo(row) {
        var t = row.querySelector(mediaSel);
        var f = inner.querySelector('.p24-slot__pane:not([data-leaving]) .p24-slot__frame');
        if (!f || !t || t.getAttribute('data-kind') !== 'clip') return;
        var v = video = d.createElement('video');
        v.className = 'p24-preview';
        v.muted = true;
        v.playsInline = true;
        v.setAttribute('muted', '');
        v.setAttribute('playsinline', '');
        v.setAttribute('aria-hidden', 'true');
        v.preload = 'auto';
        v.addEventListener('canplay', function () {
          if (video !== v) return;
          v.classList.add('is-on');
          var pr = v.play();
          if (pr && pr.catch) pr.catch(function () { /* stays on the poster */ });
        }, { once: true });
        v.addEventListener('timeupdate', function () { if (v.currentTime >= PREVIEW_STOP_S) v.pause(); });
        v.src = (t.getAttribute('href') || '').split('#')[0];
        f.insertBefore(v, f.querySelector('.p24-play'));
      }

      function place(row, instant) {
        var max = Math.max(0, box.offsetHeight - inner.offsetHeight);
        var y = row === rows[0] ? 0 : Math.max(0, Math.min(row.offsetTop - rows[0].offsetTop, max));
        if (anim && !instant) g.to(inner, { y: y, duration: 0.45, ease: ctx.ease.inOut, overwrite: 'auto' });
        else if (g) g.set(inner, { y: y });
        else inner.style.transform = 'translateY(' + y + 'px)';
      }

      function showRow(row, instant) {
        if (row === shownRow) return;
        stopVideo();
        shownRow = row;
        Array.prototype.forEach.call(inner.querySelectorAll('.p24-slot__pane[data-leaving]'), function (n) { n.remove(); });
        var old = inner.querySelector('.p24-slot__pane');
        var next = pane(row);
        if (old) { old.setAttribute('data-leaving', ''); inner.insertBefore(next, old); } else inner.appendChild(next);
        if (anim && !instant && old) {
          g.fromTo(next, { autoAlpha: 0 }, { autoAlpha: 1, duration: 0.25, ease: ctx.ease.ui, clearProps: 'opacity,visibility' });
          g.to(old, { autoAlpha: 0, duration: 0.25, ease: ctx.ease.ui, onComplete: function () { old.remove(); } });
        } else if (old) old.remove();
        place(row, instant);
      }
      function mark(row) {
        if (marked === row) return;
        if (marked) marked.classList.remove('is-active');
        marked = row;
        if (row) row.classList.add('is-active');
      }
      function rest() { mark(null); showRow(rows[0]); }

      showRow(rows[0], true);
      rows.forEach(function (row) {
        on(row, 'pointerenter', function (e) {
          if (e.pointerType === 'touch') return;
          mark(row);
          showRow(row);
          if (!previews || video) return;
          clearTimeout(timer);
          timer = setTimeout(function () { if (shownRow === row && marked === row) startVideo(row); }, INTENT_MS);
        });
        on(row, 'focusin', function () { mark(row); showRow(row); });
        on(row, 'focusout', function (e) { if (!e.relatedTarget || !row.contains(e.relatedTarget)) mark(null); });
      });
      on(listRoot, 'pointerleave', function (e) { if (e.pointerType !== 'touch') { stopVideo(); rest(); } });
      on(inner, 'click', function (e) {
        var a = e.target.closest('[data-slot-open]');
        if (!a || !ctx.viewer || e.button !== 0 || e.metaKey || e.ctrlKey) return;
        var t = shownRow && shownRow.querySelector(mediaSel + '[data-kind="still"]');
        if (!t) return;
        e.preventDefault();
        ctx.viewer.open(t, { from: a });
      });
      on(w, 'resize', function () { if (shownRow) place(shownRow, true); }, { passive: true });

      return {
        destroy: function () {
          stopVideo();
          offs.forEach(function (f) { f(); });
          mark(null);
          inner.textContent = '';
          if (g) g.set(inner, { clearProps: 'transform' });
        }
      };
    };
  }

  if (P24.component) P24.component('slot', factory);
})(window, document);

(function (w) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};

  function list(root, sel) { return Array.prototype.slice.call(root.querySelectorAll(sel)); }

  function bars(ctx, scope, stagger) {
    var g = ctx.gsap;
    var fills = list(scope, '[data-span-fill]');
    var marks = list(scope, '[data-span-mark]');
    if (scope.hasAttribute('data-span-fill')) fills = [scope];
    if (!fills.length) return;
    ctx.enter(scope, {
      prepare: function () { g.set(fills, { scaleX: 0, transformOrigin: '0% 50%' }); g.set(marks, { autoAlpha: 0 }); },
      play: function () {
        g.timeline()
          .to(fills, { scaleX: 1, duration: ctx.dur(0.6), ease: ctx.ease.out, stagger: stagger, clearProps: 'transform' })
          .to(marks, { autoAlpha: 1, duration: 0.2, ease: ctx.ease.ui, stagger: 0.03, clearProps: 'opacity,visibility' }, '-=0.25');
      },
      final: function () { g.set(fills.concat(marks), { clearProps: 'transform,opacity,visibility' }); }
    });
  }

  function line(ctx, root) {
    var g = ctx.gsap;
    var ln = root.querySelector('[data-span-line]');
    if (!ln) return;
    var stepsEls = list(root, '[data-span-step]');
    ctx.enter(root, {
      prepare: function () {
        g.set(ln, { scaleY: 0, transformOrigin: '50% 0%' });
        stepsEls.forEach(function (s) { s.classList.add('is-waiting'); });
      },
      play: function () {
        var top = ln.getBoundingClientRect().top;
        var hgt = Math.max(1, ln.offsetHeight);
        var at = stepsEls.map(function (s) { return Math.max(0, Math.min(1, (s.getBoundingClientRect().top - top) / hgt)); });
        g.to(ln, {
          scaleY: 1,
          duration: ctx.dur(0.8),
          ease: ctx.ease.out,
          clearProps: 'transform',
          onUpdate: function () {
            var p = g.getProperty(ln, 'scaleY');
            stepsEls.forEach(function (s, i) { if (p >= at[i]) s.classList.remove('is-waiting'); });
          },
          onComplete: function () { stepsEls.forEach(function (s) { s.classList.remove('is-waiting'); }); }
        });
      },
      final: function () { g.set(ln, { clearProps: 'transform' }); stepsEls.forEach(function (s) { s.classList.remove('is-waiting'); }); }
    });
  }

  function factory(ctx) {
    return function spans(root, opts) {
      if (!root || !ctx.motionOK || !ctx.gsap) return;
      opts = opts || {};
      if (opts.mode === 'line') { line(ctx, root); return; }
      var stagger = opts.stagger == null ? 0.08 : opts.stagger;
      if (ctx.mobile) {
        var items = list(root, '[data-span]');
        if (items.length) { items.forEach(function (it) { bars(ctx, it, 0); }); return; }
      }
      bars(ctx, root, stagger);
    };
  }

  if (P24.component) P24.component('spans', factory);
})(window);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var FLIP_CAP = 40;
  var LEAVE_S = 0.2;
  var MOVE_S = 0.45;
  var ARRIVE_S = 0.3;
  var GHOST_S = 0.16;
  var OVERLAP_S = 0.06;
  var TRAVEL = 12;
  var RESIZE_MS = 200;

  function arr(x) { return Array.prototype.slice.call(x || []); }
  function shown(el) { return !!el && el.getClientRects().length > 0; }
  function same(a, b) { return ['family', 'format', 'region', 'again', 'year'].every(function (k) { return (a[k] || '') === (b[k] || ''); }); }

  P24.register('work', {
    init: function (ctx) {
      var head = d.getElementById('work-head');
      var rec = d.getElementById('record');
      var abroad = d.getElementById('abroad');
      if (!head && !rec && !abroad) return undefined;
      var g = ctx.gsap;
      var anim = !!(ctx.motionOK && g);
      var offs = [];
      function on(t, type, fn, o) { t.addEventListener(type, fn, o); offs.push(function () { t.removeEventListener(type, fn, o); }); }

      if (head) ctx.heading(head.querySelector('[data-page-title]'), { now: true });
      [rec, abroad].forEach(function (s) { var h2 = s && s.querySelector('.p24-h2'); if (h2) ctx.heading(h2); });
      if (abroad) ctx.reveal(abroad.querySelector('.work-signs'), { type: 'group' });

      var W = w.P24W;
      var form = rec && rec.querySelector('[data-work-filter]');
      if (!rec || !W || !form) return function () { offs.forEach(function (f) { f(); }); };

      var html = d.documentElement;
      var list = rec.querySelector('[data-work-list]');
      var rows = arr(list.querySelectorAll('.work-row'));
      var years = arr(list.querySelectorAll('.work-year'));
      var spans = list.querySelector('.work-spans');
      var readout = form.querySelector('[data-work-readout]');
      var more = list.querySelector('[data-work-more]');
      var older = d.getElementById('work-older');
      var slots = [];
      var running = [];
      var resizeT = 0;

      var NOJS_HASH = /^#(only|family)-/;
      function url(s) {
        var q = new URLSearchParams();
        W.keys.forEach(function (k) { if (s[k]) q.set(k, s[k]); });
        var hash = w.location.hash;
        if (/^#only-/.test(hash)) hash = '#record';
        else if (/^#family-/.test(hash)) hash = '';
        var qs = q.toString();
        return w.location.pathname + (qs ? '?' + qs : '') + hash;
      }
      function writeUrl(s) { try { w.history.replaceState(w.history.state, '', url(s)); } catch (err) { /* file: or sandboxed */ } }
      if (NOJS_HASH.test(w.location.hash)) writeUrl(W.state);

      function buildSlots() {
        slots.forEach(function (s) { s.destroy(); });
        slots = [];
        if (!ctx.slot) return;
        var match = '.work-row[data-slot-row]' + W.sel(W.state);
        years.forEach(function (y) {
          var col = y.querySelector('.work-year__slot');
          if (!col) return;
          var any = shown(y) && !!y.querySelector(match);
          col.toggleAttribute('data-empty', !any);
          if (!any) return;
          slots.push(ctx.slot(y.querySelector('.work-rows'), { slotEl: col.querySelector('.p24-slot'), rows: match, media: '[data-slot-media]' }));
        });
      }
      buildSlots();
      on(w, 'resize', function () { clearTimeout(resizeT); resizeT = setTimeout(buildSlots, RESIZE_MS); }, { passive: true });

      if (spans && ctx.spans && shown(spans)) ctx.spans(spans, { mode: 'bars' });
      function drawSpans() {
        if (!anim || !spans) return;
        var fills = arr(spans.querySelectorAll('[data-span-fill]'));
        var marks = arr(spans.querySelectorAll('[data-span-mark]'));
        running.push(g.timeline()
          .fromTo(fills, { scaleX: 0, transformOrigin: '0% 50%' }, { scaleX: 1, duration: ctx.dur(0.6), ease: ctx.ease.out, stagger: 0.08, clearProps: 'transform' })
          .fromTo(marks, { autoAlpha: 0 }, { autoAlpha: 1, duration: 0.2, ease: ctx.ease.ui, stagger: 0.03, clearProps: 'opacity,visibility' }, '-=0.25'));
      }

      function pressedIn(group) { return form.querySelector('button[data-f="' + group + '"][aria-pressed="true"] .work-opt__bar'); }
      function slideBar(fromBar, group) {
        var toBar = pressedIn(group);
        if (!anim || !fromBar || !toBar || fromBar === toBar) return;
        var a = fromBar.getBoundingClientRect();
        var b = toBar.getBoundingClientRect();
        if (!b.width) return;
        running.push(g.fromTo(toBar, { x: a.left - b.left, y: a.top - b.top, scaleX: a.width / b.width },
          { x: 0, y: 0, scaleX: 1, duration: ctx.dur(0.35), ease: ctx.ease.inOut, clearProps: 'transform' }));
      }

      function finishRunning() {
        running.forEach(function (t) { if (t && t.progress() < 1) t.progress(1); });
        running = [];
      }
      function matches(r, s) { var m = W.sel(s); return !m || r.matches('.work-row' + m); }
      function near(el, vh) { var b = el.getBoundingClientRect(); return b.bottom > -vh && b.top < vh * 2; }
      function listInView() { var b = list.getBoundingClientRect(); return b.bottom > 0 && b.top < w.innerHeight; }

      function settle(prev, next) {
        W.paint(true);
        if (next.again && !prev.again) drawSpans();
        buildSlots();
      }

      var wanted = W.state;
      var token = 0;
      function setState(next) {
        if (same(wanted, next)) return;
        finishRunning();
        var prev = W.state;
        wanted = next;
        var my = ++token;
        var bars = { family: pressedIn('family'), region: pressedIn('region') };
        writeUrl(next);
        if (W.any(next)) html.classList.add('work-all');
        ctx.roll(readout, W.label(next));
        if (!anim || !listInView()) {
          W.apply(next);
          settle(prev, next);
          slideBar(bars.family, 'family');
          slideBar(bars.region, 'region');
          return;
        }
        W.state = next;
        W.paint(true);
        slideBar(bars.family, 'family');
        slideBar(bars.region, 'region');
        W.state = prev;
        ctx.loadFlip().then(function (Flip) { if (my === token) run(prev, next, Flip); }, function () { if (my === token) run(prev, next, null); });
      }

      function ghostLayer(els) {
        var layer = d.createElement('div');
        layer.className = 'work-ghosts';
        layer.setAttribute('aria-hidden', 'true');
        layer.inert = true;
        var lr = list.getBoundingClientRect();
        els.forEach(function (el) {
          var b = el.getBoundingClientRect();
          var c = el.cloneNode(true);
          c.classList.remove('work-row', 'is-active');
          c.classList.add('work-ghost');
          c.removeAttribute('id');
          arr(c.querySelectorAll('[id],[data-flip-id],[data-clip],[data-view],[data-slot-media]')).forEach(function (n) {
            ['id', 'data-flip-id', 'data-clip', 'data-view', 'data-slot-media'].forEach(function (a) { n.removeAttribute(a); });
          });
          c.style.cssText = 'position:absolute;margin:0;left:' + (b.left - lr.left) + 'px;top:' + (b.top - lr.top) + 'px;width:' + b.width + 'px';
          layer.appendChild(c);
        });
        list.appendChild(layer);
        return layer;
      }
      function inView(el, vh) { var b = el.getBoundingClientRect(); return b.height > 0 && b.bottom > 0 && b.top < vh; }

      function crossfade(prev, next, heads, vh) {
        var goingRows = rows.filter(function (r) { return shown(r) && inView(r, vh); });
        var goingHeads = heads.filter(function (h) { return shown(h) && inView(h, vh); });
        var ghosts = ghostLayer(goingRows.concat(goingHeads).slice(0, FLIP_CAP));
        W.apply(next);
        var arriving = rows.filter(function (r) { return shown(r) && near(r, vh); })
          .concat(heads.filter(function (h) { return shown(h) && near(h, vh); }))
          .slice(0, FLIP_CAP);
        var tl = g.timeline({ onComplete: function () { ghosts.remove(); }, onInterrupt: function () { ghosts.remove(); } });
        running.push(tl);
        tl.to(ghosts, { autoAlpha: 0, duration: GHOST_S, ease: ctx.ease.ui }, 0);
        if (arriving.length) {
          tl.fromTo(arriving, { autoAlpha: 0, y: TRAVEL }, {
            autoAlpha: 1, y: 0, duration: ctx.dur(ARRIVE_S), ease: ctx.ease.out, stagger: 0.012, clearProps: 'transform,opacity,visibility'
          }, OVERLAP_S);
        }
        settle(prev, next);
      }

      function run(prev, next, Flip) {
        var vh = w.innerHeight;
        var before = rows.filter(shown);
        var leaving = before.filter(function (r) { return !matches(r, next) && near(r, vh); });
        var heads = years.map(function (y) { return y.querySelector('.work-year__h'); });
        var keptOnScreen = before.some(function (r) { return matches(r, next) && inView(r, vh); });
        if (leaving.length && !keptOnScreen) { crossfade(prev, next, heads, vh); return; }
        var tl = g.timeline();
        running.push(tl);
        if (leaving.length) tl.to(leaving, { autoAlpha: 0, duration: LEAVE_S, ease: ctx.ease.ui });
        tl.add(function () {
          var staying = before.filter(function (r) { return matches(r, next) && near(r, vh); })
            .concat(heads.filter(function (h) { return shown(h) && near(h, vh); }))
            .slice(0, FLIP_CAP);
          var state = Flip && staying.length ? Flip.getState(staying) : null;
          W.apply(next);
          g.set(leaving, { clearProps: 'opacity,visibility' });
          if (state) {
            running.push(Flip.from(state, { targets: staying, duration: ctx.dur(MOVE_S), ease: ctx.ease.inOut, stagger: 0.01, absolute: false, simple: true }));
          }
          var arriving = rows.filter(function (r) { return shown(r) && near(r, vh) && staying.indexOf(r) < 0; })
            .concat(heads.filter(function (h) { return shown(h) && near(h, vh) && staying.indexOf(h) < 0; }))
            .slice(0, FLIP_CAP);
          if (arriving.length) {
            running.push(g.fromTo(arriving, { autoAlpha: 0, y: TRAVEL }, {
              autoAlpha: 1, y: 0, duration: ctx.dur(ARRIVE_S), delay: state ? 0.12 : 0, ease: ctx.ease.out, stagger: 0.012, clearProps: 'transform,opacity,visibility'
            }));
          }
          settle(prev, next);
        });
      }

      function read() {
        var s = {};
        W.keys.forEach(function (k) { s[k] = wanted[k] || ''; });
        return s;
      }
      on(form, 'click', function (e) {
        var b = e.target.closest('button[data-f]');
        if (!b) return;
        var s = read();
        var k = b.getAttribute('data-f');
        s[k] = k === 'again' ? (s.again ? '' : '1') : b.getAttribute('data-v');
        setState(s);
      });
      on(form, 'change', function (e) {
        var x = e.target.closest('select[data-f]');
        if (!x) return;
        var s = read();
        s[x.getAttribute('data-f')] = x.value;
        setState(s);
      });
      var toggle = form.querySelector('[data-work-toggle]');
      var panel = form.querySelector('.work-filter__panel');
      if (toggle && panel) {
        on(toggle, 'click', function () {
          var open = !form.classList.contains('is-open');
          form.classList.toggle('is-open', open);
          toggle.setAttribute('aria-expanded', String(open));
          if (open && anim) running.push(g.fromTo(panel, { clipPath: 'inset(0% 0% 100% 0%)' }, { clipPath: 'inset(0% 0% 0% 0%)', duration: ctx.dur(0.45), ease: ctx.ease.inOut, clearProps: 'clipPath' }));
          if (open) warm();
        });
      }

      var warm = function () { ctx.loadFlip().catch(function () { /* loaded again on the change */ }); };
      on(form, 'pointerover', warm, { once: true, passive: true });
      on(form, 'focusin', warm, { once: true });

      on(rec, 'click', function (e) {
        var c = e.target.closest('[data-work-clear]');
        if (!c) return;
        var s = {};
        W.keys.forEach(function (k) { s[k] = ''; });
        setState(s);
        if (!form.contains(c)) { var f = form.querySelector('button[data-f="family"][data-v=""]'); if (f) f.focus(); }
      });

      if (more && older) {
        on(more, 'click', function (e) {
          if (e.button !== 0 || e.metaKey || e.ctrlKey) return;
          e.preventDefault();
          html.classList.add('work-all');
          more.setAttribute('aria-expanded', 'true');
          var openedYear = older.querySelector('.work-year__h');
          if (openedYear) { openedYear.setAttribute('tabindex', '-1'); openedYear.focus({ preventScroll: true }); }
          if (anim && older.getBoundingClientRect().top < w.innerHeight) {
            running.push(g.fromTo(older, { clipPath: 'inset(0% 0% 100% 0%)' }, { clipPath: 'inset(0% 0% 0% 0%)', duration: ctx.dur(0.7), ease: ctx.ease.inOut, clearProps: 'clipPath' }));
          }
          buildSlots();
        });
      }

      on(d, 'click', function (e) {
        var a = e.target.closest && e.target.closest('a[href*="?"]');
        if (!a || e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
        var u;
        try { u = new URL(a.href, w.location.href); } catch (err) { return; }
        if (u.pathname !== w.location.pathname || !/^#(record|only-[\w-]+)$/.test(u.hash)) return;
        e.preventDefault();
        var s = W.parse(u.search, u.hash);
        if (!same(s, wanted)) {
          finishRunning();
          var prev = W.state;
          wanted = s;
          token++;
          writeUrl(s);
          if (W.any(s)) html.classList.add('work-all');
          ctx.roll(readout, W.label(s));
          W.apply(s);
          settle(prev, s);
        }
        rec.scrollIntoView({ behavior: anim ? 'smooth' : 'auto', block: 'start' });
      });

      return function () {
        finishRunning();
        clearTimeout(resizeT);
        slots.forEach(function (s) { s.destroy(); });
        offs.forEach(function (f) { f(); });
      };
    }
  });
})(window, document);

(function (w, d) {
  'use strict';
  if (!w.P24 || !w.P24.register) return;

  var REVEAL_S = 0.8;
  var RULE_IN_S = 0.55;
  var RULE_OUT_S = 0.3;

  function shown(el) { return !!el && el.getClientRects().length > 0; }

  w.P24.register('work-stories', { init: function (ctx) {
    var root = d.getElementById('by-format');
    if (!root || !ctx.story) return;
    var g = ctx.gsap;
    var motion = ctx.motionOK && !!g;
    var activeBlock = null;
    var tweens = [];

    var title = root.querySelector('#wfmt-h');
    if (title && ctx.heading) ctx.heading(title);

    function drawRule(block) {
      if (block === activeBlock) return;
      var prev = activeBlock;
      activeBlock = block;
      if (!motion) return; /* CSS shows the active block's hairline at rest */
      var outRule = prev && prev.querySelector('.wfmt-rule');
      var inRule = block && block.querySelector('.wfmt-rule');
      if (outRule) {
        g.killTweensOf(outRule);
        tweens.push(g.to(outRule, { scaleY: 0, transformOrigin: '50% 100%', duration: ctx.dur(RULE_OUT_S), ease: ctx.ease.ui }));
      }
      if (inRule) {
        g.killTweensOf(inRule);
        tweens.push(g.fromTo(inRule, { scaleY: 0, transformOrigin: '50% 0%' },
          { scaleY: 1, duration: ctx.dur(RULE_IN_S), ease: ctx.ease.out }));
      }
    }

    var story = ctx.story(root, {
      onChange: function (e) { if (e && e.block) drawRule(e.block); }
    });

    function leadStage() {
      var block1 = root.querySelector('[data-story-block="1"]');
      var own = block1 && block1.querySelector('[data-story-stage]');
      if (shown(own)) return own;
      var shared = root.querySelector('.wfmt-stage');
      return shown(shared) ? shared : null;
    }

    var stage = leadStage();
    if (motion && stage) {
      var parts = function () {
        return Array.prototype.slice.call(stage.querySelectorAll('.p24-story__area, [data-story-static]'));
      };
      ctx.enter(stage, {
        prepare: function () {
          ctx.own(stage);
          g.set(parts(), { clipPath: 'inset(100% 0% 0% 0%)' });
        },
        play: function () {
          tweens.push(g.to(parts(), {
            clipPath: 'inset(0% 0% 0% 0%)',
            duration: ctx.dur(REVEAL_S),
            ease: ctx.ease.out,
            clearProps: 'clipPath'
          }));
        },
        final: function () { g.set(parts(), { clearProps: 'clipPath' }); }
      });
    }

    return function () {
      tweens.forEach(function (t) { t.kill(); });
      tweens = [];
      Array.prototype.forEach.call(root.querySelectorAll('.wfmt-rule'), function (r) { r.style.transform = ''; });
      story.destroy();
    };
  } });
})(window, document);
