window.P24 = window.P24 || {};
window.P24.lazyComponents = ["viewer"];
/* Prototype 24 · js/p24-about.js — generated by tools/assemble.cjs from tools/pages.json; do not edit. */

(function (w, d) {
  'use strict';

  var h = d.documentElement;
  var MQ_MOTION = '(prefers-reduced-motion: no-preference)';
  var MQ_REDUCE = '(prefers-reduced-motion: reduce)';
  var MQ_MOBILE = '(max-width: 760px)';
  var EASE = Object.freeze({ out: 'expo.out', inOut: 'power3.inOut', ui: 'power2.out', window: 'cubic-bezier(.65,0,.35,1)', page: 'cubic-bezier(.16,1,.3,1)' });
  var FLIP_SRC = 'vendor/Flip.min.js';
  var MOBILE_FACTOR = 0.85;
  var SKIP_TO_END_S = 0.25;

  var P24 = w.P24 = w.P24 || {};
  var units = [];
  var components = [];
  var finals = [];
  var errors = P24.errors = P24.errors || [];
  var qa = h.classList.contains('qa');

  function mq(q) { return w.matchMedia(q).matches; }
  function toArray(x) {
    if (!x) return [];
    if (x.nodeType === 1) return [x];
    return Array.prototype.slice.call(x);
  }
  function timeout(ms, value) { return new Promise(function (resolve) { setTimeout(function () { resolve(value); }, ms); }); }
  function report(id, err) {
    errors.push({ unit: id, message: String(err && err.message || err) });
    setTimeout(function () { throw err; }, 0);
  }

  function own(els) { toArray(els).forEach(function (el) { el.classList.add('m-owned'); }); }

  function fontsReady(ms) {
    if (!d.fonts || !d.fonts.load) return Promise.resolve(true);
    return Promise.race([
      d.fonts.load('600 1em Eczar').then(function () { return true; }, function () { return false; }),
      timeout(ms == null ? 500 : ms, false)
    ]);
  }
  function whenLoaded(img) {
    if (!img) return Promise.resolve(false);
    if (img.complete && img.naturalWidth) return Promise.resolve(true);
    return new Promise(function (resolve) {
      img.addEventListener('load', function () { resolve(true); }, { once: true });
      img.addEventListener('error', function () { resolve(false); }, { once: true });
    });
  }
  function decodeOne(img) {
    if (!img) return Promise.resolve();
    if (img.decode) return img.decode();
    return whenLoaded(img);
  }
  function decodeAll(imgs, ms) {
    return Promise.race([
      Promise.all(toArray(imgs).map(decodeOne)).then(function () { return true; }, function () { return false; }),
      timeout(ms == null ? 600 : ms, false)
    ]);
  }
  function lite() {
    var c = w.navigator.connection;
    if (!c) return false;
    return !!c.saveData || /^(slow-2g|2g|3g)$/.test(c.effectiveType || '');
  }

  var flipPromise = null;
  function loadFlip() {
    if (w.Flip && w.gsap) { w.gsap.registerPlugin(w.Flip); return Promise.resolve(w.Flip); }
    if (flipPromise) return flipPromise;
    flipPromise = new Promise(function (resolve, reject) {
      var s = d.createElement('script');
      s.src = FLIP_SRC;
      s.async = true;
      s.onload = function () {
        if (!w.Flip || !w.gsap) { reject(new Error('Flip failed to load')); return; }
        w.gsap.registerPlugin(w.Flip);
        resolve(w.Flip);
      };
      s.onerror = function () { flipPromise = null; reject(new Error('Flip failed to load')); };
      d.head.appendChild(s);
    });
    return flipPromise;
  }

  function onFinal(fn) { if (typeof fn === 'function') finals.push(fn); }

  function enter(el, o) {
    if (!el || !o || typeof o.play !== 'function' || !('IntersectionObserver' in w)) return;
    var state = 'unknown';
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (e) {
        if (state === 'unknown') {
          var below = e.boundingClientRect.top >= (w.innerHeight || h.clientHeight);
          if (!below) { state = 'static'; io.disconnect(); return; }
          state = 'waiting';
          if (o.prepare) o.prepare(el);
          onFinal(function () { if (state === 'waiting') { state = 'done'; io.disconnect(); finish(); } });
          return;
        }
        if (state === 'waiting' && e.isIntersecting) { state = 'done'; io.disconnect(); o.play(el); }
      });
    }, { rootMargin: o.rootMargin || '0px 0px -15% 0px' });
    var jumpTimer = 0;
    function onJump() {
      clearTimeout(jumpTimer);
      jumpTimer = setTimeout(function () {
        if (state !== 'waiting') { w.removeEventListener('scroll', onJump); return; }
        if (el.getBoundingClientRect().bottom <= 0) { state = 'done'; io.disconnect(); w.removeEventListener('scroll', onJump); finish(); }
      }, 150);
    }
    w.addEventListener('scroll', onJump, { passive: true });
    function finish() {
      if (o.final) { o.final(el); return; }
      el.style.opacity = ''; el.style.transform = ''; el.style.clipPath = ''; el.style.visibility = '';
    }
    io.observe(el);
  }

  function runFinals() {
    var g = w.gsap;
    if (g && g.globalTimeline) g.globalTimeline.getChildren(true, true, true).forEach(function (t) { if (t.progress() < 1) t.progress(1); });
    if (d.getAnimations) d.getAnimations().forEach(function (a) { try { if (a.effect && a.effect.getTiming().iterations !== Infinity) a.finish(); } catch (err) { /* not finishable */ } });
    finals.slice().forEach(function (fn) { try { fn(); } catch (err) { report('final', err); } });
  }
  w.addEventListener('beforeprint', runFinals);
  d.addEventListener('beforematch', runFinals, true);

  var MOD_KEY = /^(Shift|Control|Alt|Meta|F\d{1,2})$/;
  function skipOnInput(tl) {
    if (!tl) return function () {};
    var coarse = mq('(pointer: coarse)');
    var startY = w.scrollY;
    var down = null;
    var opt = { passive: true, capture: true };
    var done = false;
    var list = [['keydown', onKey]];
    if (coarse) list.push(['pointerdown', onDown], ['pointerup', onUp]);
    else list.push(['wheel', fire], ['pointerdown', fire], ['scroll', onScroll]);
    function off() {
      if (done) return;
      done = true;
      list.forEach(function (p) { w.removeEventListener(p[0], p[1], opt); });
    }
    function fire() {
      off();
      if (qa) { tl.progress(1); return; }
      var rem = tl.duration() - tl.time();
      if (rem > 0) tl.timeScale(Math.max(tl.timeScale(), rem / SKIP_TO_END_S));
    }
    function onKey(e) { if (!MOD_KEY.test(e.key || '')) fire(); }
    function onScroll() { if (Math.abs(w.scrollY - startY) > 8) fire(); }
    function onDown(e) { down = { x: e.clientX, y: e.clientY, t: e.timeStamp }; }
    function onUp(e) {
      if (!down) return;
      var near = Math.abs(e.clientX - down.x) <= 10 && Math.abs(e.clientY - down.y) <= 10;
      var quick = e.timeStamp - down.t <= 300;
      down = null;
      if (near && quick) fire();
    }
    list.forEach(function (p) { w.addEventListener(p[0], p[1], opt); });
    var prev = tl.eventCallback('onComplete');
    var params = tl.vars && tl.vars.onCompleteParams;
    tl.eventCallback('onComplete', function () { off(); if (prev) prev.apply(tl, params || []); });
    return off;
  }

  var LAZY = {
    player: { sel: 'a[data-clip], button[data-clip]', methods: ['open', 'close', 'isOpen', 'manifest', 'rail', 'hoverPreview'] },
    viewer: { sel: 'a[data-view]', methods: ['open', 'close'] }
  };
  var lazyNames = (P24.lazyComponents || []).filter(function (n) { return !!LAZY[n]; });
  var lazyLoads = {};
  var lazyReady = {};
  function findComponent(name) {
    for (var i = 0; i < components.length; i++) if (components[i].name === name) return components[i];
    return null;
  }
  function loadComponent(name) {
    if (lazyLoads[name]) return lazyLoads[name];
    lazyLoads[name] = new Promise(function (resolve, reject) {
      var s = d.createElement('script');
      s.src = 'js/components/' + name + '.js';
      s.async = true;
      s.onload = function () {
        var c = findComponent(name);
        if (!c) { reject(new Error('component ' + name + ' did not register')); return; }
        var api = c.factory(P24.ctx || makeCtx(h.classList.contains('js-motion')));
        if (P24.ctx) P24.ctx[name] = api;
        resolve(api);
      };
      s.onerror = function () { lazyLoads[name] = null; reject(new Error('component ' + name + ' failed to load')); };
      d.head.appendChild(s);
    });
    return lazyLoads[name];
  }
  function proxy(name) {
    var p = { lazy: true };
    LAZY[name].methods.forEach(function (m) {
      p[m] = function () {
        var a = arguments;
        return loadComponent(name).then(function (api) { return api[m].apply(api, a); });
      };
    });
    return p;
  }
  lazyNames.forEach(function (name) {
    var sel = LAZY[name].sel;
    d.addEventListener('click', function (e) {
      if (lazyReady[name]) return;
      var t = e.target.closest && e.target.closest(sel);
      if (!t || e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
      e.preventDefault();
      loadComponent(name).then(function (api) { api.open(t); }, function () { if (t.href) w.location.href = t.href; });
    });
    var warm = function (e) {
      if (lazyReady[name] || !e.target.closest || !e.target.closest(sel)) return;
      loadComponent(name).catch(function () { /* retried on click */ });
    };
    d.addEventListener('pointerover', warm, { passive: true });
    d.addEventListener('focusin', warm);
    d.addEventListener('touchstart', warm, { passive: true });
  });
  if (lazyNames.length) {
    w.addEventListener('load', function () {
      setTimeout(function () { lazyNames.forEach(function (n) { loadComponent(n).catch(function () { /* on demand */ }); }); }, 4000);
    }, { once: true });
  }

  function makeCtx(motionOK) {
    var mobile = mq(MQ_MOBILE);
    var ctx = {
      gsap: w.gsap || null,
      SplitText: w.SplitText || null,
      motionOK: motionOK,
      mobile: mobile,
      coarse: mq('(pointer: coarse)'),
      qa: qa,
      lite: lite(),
      internalNav: h.classList.contains('vt-nav'),
      m1: { play: !h.classList.contains('m1-skip'), holdName: h.classList.contains('m1-type') },
      ease: EASE,
      dur: function (s) { return mq(MQ_MOBILE) ? s * MOBILE_FACTOR : s; },
      enter: enter,
      loadFlip: loadFlip,
      fontsReady: fontsReady,
      decodeAll: decodeAll,
      whenLoaded: whenLoaded,
      own: own,
      onFinal: onFinal,
      skipOnInput: skipOnInput,
      setIntro: function (intro) { P24.intro = intro || null; },
      vt: {
        internalNav: h.classList.contains('vt-nav'),
        supported: !!(P24._vt && P24._vt.supported),
        name: function (el, n) { if (P24._vt) P24._vt.name(el, n); }
      }
    };
    ctx.reveal = function (els, opts) { return P24._reveal ? P24._reveal(ctx, els, opts || {}) : undefined; };
    ctx.heading = function (el, opts) { return P24._type ? P24._type.heading(ctx, el, opts || {}) : undefined; };
    ctx.roll = function (el, text) {
      if (P24._type) return P24._type.roll(ctx, el, text);
      if (el) el.textContent = text;
      return undefined;
    };
    components.forEach(function (c) {
      try { ctx[c.name] = c.factory(ctx); } catch (err) { report('component:' + c.name, err); }
    });
    lazyNames.forEach(function (n) { if (!ctx[n]) ctx[n] = proxy(n); });
    return ctx;
  }

  function runUnits(motionOK) {
    var ctx = makeCtx(motionOK);
    P24.ctx = ctx;
    var cleanups = [];
    units.forEach(function (u) {
      try {
        var c = u.mod.init(ctx);
        if (typeof c === 'function') cleanups.push(c);
      } catch (err) {
        report(u.id, err);
        h.classList.remove('js-motion');
      }
    });
    return function () { cleanups.forEach(function (c) { try { c(); } catch (err) { report('cleanup', err); } }); };
  }

  P24.register = function (id, mod) {
    if (!id || !mod || typeof mod.init !== 'function') throw new Error('P24.register(id, { init }) expects an init function');
    if (units.some(function (u) { return u.id === id; })) throw new Error('P24.register: duplicate id ' + id);
    units.push({ id: id, mod: mod });
  };
  P24.component = function (name, factory) {
    if (!name || typeof factory !== 'function') throw new Error('P24.component(name, factory) expects a factory');
    if (components.some(function (c) { return c.name === name; })) throw new Error('P24.component: duplicate ' + name);
    components.push({ name: name, factory: factory });
    if (LAZY[name]) lazyReady[name] = true;
  };

  function boot() {
    if (P24.booted) return;
    P24.booted = true;
    var g = w.gsap;
    if (!g) { h.classList.remove('js-motion'); runUnits(false); return; }
    if (w.SplitText) g.registerPlugin(w.SplitText);
    g.config({ autoSleep: 60, nullTargetWarn: false });
    g.defaults({ ease: EASE.out, duration: 0.6 });
    var mm = g.matchMedia();
    P24.mm = mm;
    mm.add({ ok: MQ_MOTION, reduce: MQ_REDUCE }, function (c) {
      var ok = !!c.conditions.ok;
      h.classList.toggle('js-motion', ok);
      return runUnits(ok);
    });
  }

  P24.ease = EASE;
  P24.loadFlip = loadFlip;
  P24.finish = runFinals;

  if (qa) {
    w.__p24 = {
      seek: function (t) {
        var i = P24.intro;
        if (!i || !i.timeline) return false;
        i.timeline.pause();
        i.timeline.seek(Number(t) || 0, false);
        return true;
      },
      state: function () {
        return {
          booted: !!P24.booted,
          motion: h.classList.contains('js-motion'),
          classes: h.className,
          intro: !!P24.intro,
          vtLog: (P24.vtLog || []).slice(),
          errors: errors.slice()
        };
      },
      finish: runFinals
    };
  }

  if (d.readyState === 'loading') d.addEventListener('DOMContentLoaded', boot, { once: true });
  else setTimeout(boot, 0);
})(window, document);

(function (w) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};

  function list(x) {
    if (!x) return [];
    if (x.nodeType === 1) return [x];
    return Array.prototype.slice.call(x);
  }

  function lines(ctx, el, opts) {
    if (ctx.heading) { ctx.heading(el, { rootMargin: opts.rootMargin }); return; }
    var g = ctx.gsap;
    var ST = ctx.SplitText;
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () { g.set(el, { autoAlpha: 0 }); },
      play: function () {
        g.set(el, { autoAlpha: 1 });
        if (!ST) { g.from(el, { y: ctx.mobile ? 12 : 20, autoAlpha: 0, duration: ctx.dur(0.7) }); return; }
        var split = ST.create(el, { type: 'lines', mask: 'lines', linesClass: 'p24-line', aria: 'auto' });
        g.from(split.lines, {
          yPercent: 110,
          duration: ctx.dur(0.7),
          stagger: 0.08,
          ease: ctx.ease.out,
          onComplete: function () { split.revert(); }
        });
      },
      final: function () { g.set(el, { clearProps: 'opacity,visibility' }); }
    });
  }

  function photo(ctx, el, opts) {
    var g = ctx.gsap;
    var frame = el.classList.contains('p24-frame') ? el : el.querySelector('.p24-frame') || el;
    var img = frame.querySelector('img, video');
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () {
        g.set(frame, { clipPath: 'inset(100% 0% 0% 0%)' });
        if (img) g.set(img, { scale: 1.06, transformOrigin: '50% 100%' });
      },
      play: function () {
        var open = function () {
          var d = ctx.dur(0.8);
          g.to(frame, { clipPath: 'inset(0% 0% 0% 0%)', duration: d, ease: ctx.ease.out, clearProps: 'clipPath' });
          if (img) g.to(img, { scale: 1, duration: d, ease: ctx.ease.out, clearProps: 'transform' });
        };
        if (!img || img.tagName !== 'IMG' || !ctx.decodeAll) { open(); return; }
        if (img.loading === 'lazy') img.loading = 'eager';
        ctx.decodeAll([img], 900).then(function (ok) {
          if (ok) { open(); return; }
          g.set(frame, { clearProps: 'clipPath' });
          g.set(img, { clearProps: 'transform' });
        });
      },
      final: function () {
        g.set(frame, { clearProps: 'clipPath' });
        if (img) g.set(img, { clearProps: 'transform' });
      }
    });
  }

  function group(ctx, el, opts) {
    var g = ctx.gsap;
    var kids = Array.prototype.slice.call(el.children);
    if (!kids.length) return;
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () { g.set(kids, { y: ctx.mobile ? 12 : 16, autoAlpha: 0 }); },
      play: function () {
        g.to(kids, {
          y: 0,
          autoAlpha: 1,
          duration: ctx.dur(0.7),
          stagger: opts.stagger == null ? 0.06 : opts.stagger,
          ease: ctx.ease.out,
          clearProps: 'transform,opacity,visibility'
        });
      },
      final: function () { g.set(kids, { clearProps: 'transform,opacity,visibility' }); }
    });
  }

  P24._reveal = function (ctx, els, opts) {
    if (!ctx.motionOK || !ctx.gsap) return;
    var type = opts.type || 'group';
    list(els).forEach(function (el) {
      if (type === 'lines') lines(ctx, el, opts);
      else if (type === 'photo') photo(ctx, el, opts);
      else group(ctx, el, opts);
    });
  };
})(window);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var ROLL_TRAVEL = 8;

  function hasDeva(el) { return !!(el.closest('[lang="hi"]') || el.querySelector('[lang="hi"]')); }

  function rise(ctx, el, done) {
    var g = ctx.gsap;
    var ST = ctx.SplitText;
    var dur = ctx.mobile ? 0.6 : 0.7;
    g.set(el, { autoAlpha: 1 });
    if (!ST || hasDeva(el)) {
      g.from(el, { y: ctx.mobile ? 12 : 20, autoAlpha: 0, duration: dur, ease: ctx.ease.out, clearProps: 'transform,opacity,visibility', onComplete: done });
      return;
    }
    var tween = null;
    var split = ST.create(el, {
      type: 'lines',
      mask: 'lines',
      linesClass: 'p24-line',
      aria: 'auto'
    });
    tween = g.from(split.lines, {
      yPercent: 110,
      duration: dur,
      stagger: 0.08,
      ease: ctx.ease.out,
      onComplete: function () { split.revert(); if (done) done(); }
    });
    return split;
  }

  function heading(ctx, el, opts) {
    if (!el || !ctx.motionOK || !ctx.gsap) return;
    var g = ctx.gsap;
    if (opts.now) {
      if (ctx.internalNav) return;
      if (w.getComputedStyle(el).opacity !== '0') return;
      ctx.own(el);
      rise(ctx, el);
      return;
    }
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () { g.set(el, { autoAlpha: 0 }); },
      play: function () { rise(ctx, el); },
      final: function () { g.set(el, { clearProps: 'opacity,visibility' }); }
    });
  }

  function roll(ctx, el, text) {
    if (!el) return;
    text = text == null ? '' : String(text);
    if (el._p24roll) { el._p24roll.progress(1); el._p24roll = null; }
    var oldText = el.textContent;
    if (oldText === text) return;
    var g = ctx.gsap;
    if (!ctx.motionOK || !g || !el.isConnected || !oldText) { el.textContent = text; return; }
    el.classList.add('p24-roll');
    el.textContent = '';
    var next = d.createElement('span');
    next.className = 'p24-roll__new';
    next.textContent = text;
    var ghost = d.createElement('span');
    ghost.className = 'p24-roll__old';
    ghost.setAttribute('aria-hidden', 'true');
    ghost.textContent = oldText;
    el.appendChild(next);
    el.appendChild(ghost);
    var dur = ctx.dur(0.3);
    el._p24roll = g.timeline({
      onComplete: function () { el.textContent = text; el.classList.remove('p24-roll'); el._p24roll = null; }
    })
      .to(ghost, { y: -ROLL_TRAVEL, autoAlpha: 0, duration: dur * 0.7, ease: 'power2.in' }, 0)
      .from(next, { y: ROLL_TRAVEL, autoAlpha: 0, duration: dur, ease: ctx.ease.ui }, dur * 0.3);
  }

  P24._type = { heading: heading, roll: roll };
})(window, document);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var lastLink = null;
  var NAMES = { 'cta-panel': 1, 'family-hero': 1 };

  function visible(el) {
    if (!el) return false;
    var r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0 && r.bottom > 0 && r.top < w.innerHeight;
  }

  function sourceFor(link, name) {
    if (name === 'cta-panel') return link;
    var sel = link.getAttribute('data-vt-source');
    if (sel) { var s = d.querySelector(sel); if (visible(s)) return s; }
    var node = link.parentElement;
    while (node && node !== d.body) {
      var stages = node.querySelectorAll('[data-story-stage]');
      for (var i = 0; i < stages.length; i++) {
        var win = stages[i].querySelector('.p24-story__window') || stages[i];
        if (visible(win)) return win;
      }
      node = node.parentElement;
    }
    return null;
  }

  function showKeyFrame(link, win) {
    var block = link.closest('[data-story-block]');
    if (!block || !win || !win.classList.contains('p24-story__window')) return;
    var key = block.getAttribute('data-story-key');
    if (!key) { var st = block.querySelector('[data-story-step]'); key = st ? (st.getAttribute('data-story-step') || '').split(/\s+/)[0] : ''; }
    var layer = key ? win.querySelector('.p24-story__layer[data-frame="' + key + '"]') : null;
    if (!layer || !layer.style.width) return;
    var img = layer.querySelector('img');
    if (img && !img.complete) return;
    var all = win.querySelectorAll('.p24-story__layer');
    for (var i = 0; i < all.length; i++) {
      if (all[i].getAnimations) all[i].getAnimations().forEach(function (an) { an.cancel(); });
      if (all[i] !== layer) all[i].classList.remove('is-on', 'is-top');
    }
    if (win.getAnimations) win.getAnimations().forEach(function (an) { an.cancel(); });
    layer.classList.add('is-on');
    layer.style.clipPath = '';
    var area = win.parentElement || win;
    var l = parseFloat(layer.style.left) || 0, t = parseFloat(layer.style.top) || 0;
    var lw = parseFloat(layer.style.width) || 0, lh = parseFloat(layer.style.height) || 0;
    win.style.clipPath = 'inset(' + t + 'px ' + Math.max(0, area.clientWidth - l - lw) + 'px ' + Math.max(0, area.clientHeight - t - lh) + 'px ' + l + 'px)';
  }

  function name(el, n) {
    if (!el || !n) return;
    var prev = d.querySelectorAll('[data-vt-named]');
    for (var i = 0; i < prev.length; i++) {
      if (prev[i].style.viewTransitionName === n) { prev[i].style.viewTransitionName = ''; prev[i].removeAttribute('data-vt-named'); }
    }
    el.style.viewTransitionName = n;
    el.setAttribute('data-vt-named', '');
  }
  function clearAll() {
    var named = d.querySelectorAll('[data-vt-named]');
    for (var i = 0; i < named.length; i++) { named[i].style.viewTransitionName = ''; named[i].removeAttribute('data-vt-named'); }
  }

  d.addEventListener('click', function (e) {
    var a = e.target && e.target.closest ? e.target.closest('a[href]') : null;
    lastLink = a && a.hasAttribute('data-vt') ? a : null;
  }, true);

  w.addEventListener('pageswap', function (e) {
    var vt = e.viewTransition;
    try { w.sessionStorage.removeItem('p24-vt'); } catch (err) { /* storage off: pairs are skipped */ }
    if (!vt) return;
    try {
      clearAll();
      var link = lastLink;
      lastLink = null;
      var entry = e.activation && e.activation.entry;
      if (!link || !entry || link.href !== entry.url) return;
      var n = link.getAttribute('data-vt');
      if (!NAMES[n]) return;
      var src = sourceFor(link, n);
      if (!visible(src)) return;
      if (n === 'family-hero') showKeyFrame(link, src);
      name(src, n);
      w.sessionStorage.setItem('p24-vt', n);
      if (d.documentElement.classList.contains('qa')) {
        var r = src.getBoundingClientRect();
        w.sessionStorage.setItem('p24-vtlog', JSON.stringify({ name: n, source: src.tagName.toLowerCase() + '.' + String(src.className).split(' ')[0], rect: [Math.round(r.left), Math.round(r.top), Math.round(r.width), Math.round(r.height)], url: entry.url }));
      }
    } catch (err) {
      vt.skipTransition();
    }
  });

  w.addEventListener('pageshow', function (e) { if (e.persisted) { clearAll(); lastLink = null; } });

  P24._vt = {
    name: name,
    clear: clearAll,
    internalNav: function () { return d.documentElement.classList.contains('vt-nav'); },
    supported: typeof d.startViewTransition === 'function' && !!w.CSS && CSS.supports('view-transition-name: none')
  };
})(window, document);

(function (w, d) {
  'use strict';
  var h = d.documentElement;
  var body = d.body;
  var hasIO = 'IntersectionObserver' in w;
  function each(sel, fn) { Array.prototype.forEach.call(d.querySelectorAll(sel), fn); }

  var page = body.getAttribute('data-page');
  each('[data-nav]', function (a) {
    if (page && a.getAttribute('data-nav') === page) a.setAttribute('aria-current', 'page');
  });

  var menuBtn = d.querySelector('[data-menu-open]');
  var menu = d.getElementById('p24-menu');
  if (menuBtn && menu && typeof menu.showModal === 'function') {
    var closeBtn = menu.querySelector('[data-menu-close]');
    var setOpen = function (open) {
      if (open && !menu.open) menu.showModal();
      if (!open && menu.open) menu.close();
      menuBtn.setAttribute('aria-expanded', String(open));
    };
    menuBtn.addEventListener('click', function () { setOpen(true); });
    if (closeBtn) closeBtn.addEventListener('click', function () { setOpen(false); });
    menu.addEventListener('close', function () {
      menuBtn.setAttribute('aria-expanded', 'false');
      menuBtn.focus({ preventScroll: true });
    });
    menu.addEventListener('click', function (e) {
      var a = e.target.closest('a');
      if (a && a.getAttribute('href').charAt(0) === '#') setOpen(false);
    });
    var closedOnHide = false;
    var reset = function () {
      menuBtn.setAttribute('aria-expanded', 'false');
      menuBtn.textContent = 'Menu';
      if (menu.open) menu.close();
    };
    w.addEventListener('pagehide', function () { if (menu.open) { closedOnHide = true; reset(); } });
    w.addEventListener('pageshow', function (e) {
      if (!e.persisted) return;
      var was = closedOnHide || menu.open;
      closedOnHide = false;
      reset();
      if (was) menuBtn.focus({ preventScroll: true });
    });
    var mqWide = w.matchMedia('(min-width: 761px)');
    var onWide = function () { if (mqWide.matches) setOpen(false); };
    if (mqWide.addEventListener) mqWide.addEventListener('change', onWide);
  } else if (menuBtn) {
    menuBtn.addEventListener('click', function () { var f = d.getElementById('p24-footer-pages'); if (f) f.scrollIntoView(); });
  }

  var dock = d.querySelector('[data-dock]');
  if (dock && !body.hasAttribute('data-no-dock')) {
    var sentinels = d.querySelectorAll('[data-dock-sentinel]');
    var footerCta = d.querySelector('[data-footer-cta]');
    var state = { sentinel: sentinels.length > 0, footer: false, typing: false };
    d.addEventListener('p24:dock', function () { render(); });
    var links = dock.querySelectorAll('a, button');
    var render = function () {
      var show = !state.sentinel && !state.footer && !state.typing && !h.classList.contains('story-stuck');
      if (show) dock.setAttribute('data-show', ''); else dock.removeAttribute('data-show');
      h.classList.toggle('dock-on', show);
      dock.setAttribute('aria-hidden', String(!show));
      Array.prototype.forEach.call(links, function (l) { l.tabIndex = show ? 0 : -1; });
    };
    if (hasIO && sentinels.length) {
      var seen = new Set();
      var ioS = new IntersectionObserver(function (entries) {
        entries.forEach(function (e) {
          if (e.isIntersecting && e.intersectionRatio >= 0.99) seen.add(e.target); else seen.delete(e.target);
        });
        state.sentinel = seen.size > 0;
        render();
      }, { threshold: [0, 0.99, 1] });
      Array.prototype.forEach.call(sentinels, function (s) { ioS.observe(s); });
    }
    if (hasIO && footerCta) {
      new IntersectionObserver(function (entries) {
        state.footer = entries[0].isIntersecting;
        render();
      }).observe(footerCta);
    }
    d.addEventListener('focusin', function (e) {
      state.typing = !!(e.target.closest && e.target.closest('input, select, textarea'));
      render();
    });
    render();
  }

  each('[data-replay-opening]', function (a) {
    a.addEventListener('click', function (e) {
      if (e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
      e.preventDefault();
      if ('scrollRestoration' in w.history) w.history.scrollRestoration = 'manual';
      w.scrollTo(0, 0);
      w.location.reload();
    });
  });

  if (h.classList.contains('qa')) {
    var qaBox = d.createElement('pre');
    qaBox.className = 'p24-qa';
    qaBox.setAttribute('aria-hidden', 'true');
    var draw = function () {
      var P24 = w.P24 || {};
      var NL = String.fromCharCode(10);
      qaBox.textContent = 'P24 QA · ' + h.className + NL + (P24.vtLog || []).map(function (x) { return JSON.stringify(x); }).join(NL);
    };
    draw();
    body.appendChild(qaBox);
    setTimeout(draw, 1200);
  }
})(window, document);

(function (w, d) {
  'use strict';
  var P24 = w.P24;
  if (!P24 || !P24.register) return;

  var ROW_STAGGER = 0.09;
  var COL_STAGGER = 0.08;
  var ROOT_MARGIN = '0px 0px -12% 0px';
  var DECODE_WAIT_MS = 700;

  function all(root, sel) { return Array.prototype.slice.call(root.querySelectorAll(sel)); }

  function hairlines(ctx, root) {
    var g = ctx.gsap;
    all(root, '.about-how__rule').forEach(function (rule) {
      ctx.enter(rule, {
        rootMargin: ROOT_MARGIN,
        prepare: function () { g.set(rule, { scaleX: 0 }); },
        play: function () {
          g.to(rule, { scaleX: 1, duration: ctx.dur(0.7), ease: ctx.ease.out, clearProps: 'transform' });
        },
        final: function () { g.set(rule, { clearProps: 'transform' }); }
      });
    });
  }

  function galleryItem(ctx, fig) {
    var g = ctx.gsap;
    var frame = fig.querySelector('.about-range__frame');
    var img = frame && frame.querySelector('img');
    if (!frame) return;
    var pos = Number(fig.getAttribute('data-about-item')) || 0;
    var settle = !ctx.mobile && img;
    ctx.enter(fig, {
      rootMargin: ROOT_MARGIN,
      prepare: function () {
        g.set(frame, { clipPath: 'inset(100% 0% 0% 0%)' });
        if (settle) g.set(img, { scale: 1.06, transformOrigin: '50% 100%' });
      },
      play: function () {
        var dur = ctx.dur(0.8);
        var delay = ctx.mobile ? (pos % 2) * COL_STAGGER : pos * ROW_STAGGER;
        ctx.decodeAll(img ? [img] : [], DECODE_WAIT_MS).then(function () {
          g.to(frame, { clipPath: 'inset(0% 0% 0% 0%)', duration: dur, delay: delay, ease: ctx.ease.out, clearProps: 'clipPath' });
          if (settle) g.to(img, { scale: 1, duration: dur, delay: delay, ease: ctx.ease.out, clearProps: 'transform' });
        });
      },
      final: function () {
        g.set(frame, { clearProps: 'clipPath' });
        if (img) g.set(img, { clearProps: 'transform' });
      }
    });
  }

  P24.register('about', {
    init: function (ctx) {
      var head = d.querySelector('[data-about]');
      if (!head) return;
      if (!ctx.motionOK || !ctx.gsap) return;

      var h1 = head.querySelector('[data-page-title]');
      if (h1) ctx.heading(h1, { now: true });

      var main = d.getElementById('main') || d.body;
      all(main, '[data-about-h2]').forEach(function (h2) { ctx.heading(h2); });

      var how = d.getElementById('how-she-works');
      if (how) {
        hairlines(ctx, how);
        ctx.reveal(all(how, '[data-about-pair]'), { type: 'photo', rootMargin: ROOT_MARGIN });
      }

      var gallery = d.querySelector('[data-about-gallery]');
      if (gallery) all(gallery, '.about-range__item').forEach(function (fig) { galleryItem(ctx, fig); });
    }
  });
})(window, document);
