window.P24 = window.P24 || {};
window.P24.lazyComponents = [];
/* Prototype 24 · js/p24-enquire.js — generated by tools/assemble.cjs from tools/pages.json; do not edit. */

(function (w, d) {
  'use strict';

  var h = d.documentElement;
  var MQ_MOTION = '(prefers-reduced-motion: no-preference)';
  var MQ_REDUCE = '(prefers-reduced-motion: reduce)';
  var MQ_MOBILE = '(max-width: 760px)';
  var EASE = Object.freeze({ out: 'expo.out', inOut: 'power3.inOut', ui: 'power2.out', window: 'cubic-bezier(.65,0,.35,1)', page: 'cubic-bezier(.16,1,.3,1)' });
  var FLIP_SRC = 'vendor/Flip.min.js';
  var MOBILE_FACTOR = 0.85;
  var SKIP_TO_END_S = 0.25;

  var P24 = w.P24 = w.P24 || {};
  var units = [];
  var components = [];
  var finals = [];
  var errors = P24.errors = P24.errors || [];
  var qa = h.classList.contains('qa');

  function mq(q) { return w.matchMedia(q).matches; }
  function toArray(x) {
    if (!x) return [];
    if (x.nodeType === 1) return [x];
    return Array.prototype.slice.call(x);
  }
  function timeout(ms, value) { return new Promise(function (resolve) { setTimeout(function () { resolve(value); }, ms); }); }
  function report(id, err) {
    errors.push({ unit: id, message: String(err && err.message || err) });
    setTimeout(function () { throw err; }, 0);
  }

  function own(els) { toArray(els).forEach(function (el) { el.classList.add('m-owned'); }); }

  function fontsReady(ms) {
    if (!d.fonts || !d.fonts.load) return Promise.resolve(true);
    return Promise.race([
      d.fonts.load('600 1em Eczar').then(function () { return true; }, function () { return false; }),
      timeout(ms == null ? 500 : ms, false)
    ]);
  }
  function whenLoaded(img) {
    if (!img) return Promise.resolve(false);
    if (img.complete && img.naturalWidth) return Promise.resolve(true);
    return new Promise(function (resolve) {
      img.addEventListener('load', function () { resolve(true); }, { once: true });
      img.addEventListener('error', function () { resolve(false); }, { once: true });
    });
  }
  function decodeOne(img) {
    if (!img) return Promise.resolve();
    if (img.decode) return img.decode();
    return whenLoaded(img);
  }
  function decodeAll(imgs, ms) {
    return Promise.race([
      Promise.all(toArray(imgs).map(decodeOne)).then(function () { return true; }, function () { return false; }),
      timeout(ms == null ? 600 : ms, false)
    ]);
  }
  function lite() {
    var c = w.navigator.connection;
    if (!c) return false;
    return !!c.saveData || /^(slow-2g|2g|3g)$/.test(c.effectiveType || '');
  }

  var flipPromise = null;
  function loadFlip() {
    if (w.Flip && w.gsap) { w.gsap.registerPlugin(w.Flip); return Promise.resolve(w.Flip); }
    if (flipPromise) return flipPromise;
    flipPromise = new Promise(function (resolve, reject) {
      var s = d.createElement('script');
      s.src = FLIP_SRC;
      s.async = true;
      s.onload = function () {
        if (!w.Flip || !w.gsap) { reject(new Error('Flip failed to load')); return; }
        w.gsap.registerPlugin(w.Flip);
        resolve(w.Flip);
      };
      s.onerror = function () { flipPromise = null; reject(new Error('Flip failed to load')); };
      d.head.appendChild(s);
    });
    return flipPromise;
  }

  function onFinal(fn) { if (typeof fn === 'function') finals.push(fn); }

  function enter(el, o) {
    if (!el || !o || typeof o.play !== 'function' || !('IntersectionObserver' in w)) return;
    var state = 'unknown';
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (e) {
        if (state === 'unknown') {
          var below = e.boundingClientRect.top >= (w.innerHeight || h.clientHeight);
          if (!below) { state = 'static'; io.disconnect(); return; }
          state = 'waiting';
          if (o.prepare) o.prepare(el);
          onFinal(function () { if (state === 'waiting') { state = 'done'; io.disconnect(); finish(); } });
          return;
        }
        if (state === 'waiting' && e.isIntersecting) { state = 'done'; io.disconnect(); o.play(el); }
      });
    }, { rootMargin: o.rootMargin || '0px 0px -15% 0px' });
    var jumpTimer = 0;
    function onJump() {
      clearTimeout(jumpTimer);
      jumpTimer = setTimeout(function () {
        if (state !== 'waiting') { w.removeEventListener('scroll', onJump); return; }
        if (el.getBoundingClientRect().bottom <= 0) { state = 'done'; io.disconnect(); w.removeEventListener('scroll', onJump); finish(); }
      }, 150);
    }
    w.addEventListener('scroll', onJump, { passive: true });
    function finish() {
      if (o.final) { o.final(el); return; }
      el.style.opacity = ''; el.style.transform = ''; el.style.clipPath = ''; el.style.visibility = '';
    }
    io.observe(el);
  }

  function runFinals() {
    var g = w.gsap;
    if (g && g.globalTimeline) g.globalTimeline.getChildren(true, true, true).forEach(function (t) { if (t.progress() < 1) t.progress(1); });
    if (d.getAnimations) d.getAnimations().forEach(function (a) { try { if (a.effect && a.effect.getTiming().iterations !== Infinity) a.finish(); } catch (err) { /* not finishable */ } });
    finals.slice().forEach(function (fn) { try { fn(); } catch (err) { report('final', err); } });
  }
  w.addEventListener('beforeprint', runFinals);
  d.addEventListener('beforematch', runFinals, true);

  var MOD_KEY = /^(Shift|Control|Alt|Meta|F\d{1,2})$/;
  function skipOnInput(tl) {
    if (!tl) return function () {};
    var coarse = mq('(pointer: coarse)');
    var startY = w.scrollY;
    var down = null;
    var opt = { passive: true, capture: true };
    var done = false;
    var list = [['keydown', onKey]];
    if (coarse) list.push(['pointerdown', onDown], ['pointerup', onUp]);
    else list.push(['wheel', fire], ['pointerdown', fire], ['scroll', onScroll]);
    function off() {
      if (done) return;
      done = true;
      list.forEach(function (p) { w.removeEventListener(p[0], p[1], opt); });
    }
    function fire() {
      off();
      if (qa) { tl.progress(1); return; }
      var rem = tl.duration() - tl.time();
      if (rem > 0) tl.timeScale(Math.max(tl.timeScale(), rem / SKIP_TO_END_S));
    }
    function onKey(e) { if (!MOD_KEY.test(e.key || '')) fire(); }
    function onScroll() { if (Math.abs(w.scrollY - startY) > 8) fire(); }
    function onDown(e) { down = { x: e.clientX, y: e.clientY, t: e.timeStamp }; }
    function onUp(e) {
      if (!down) return;
      var near = Math.abs(e.clientX - down.x) <= 10 && Math.abs(e.clientY - down.y) <= 10;
      var quick = e.timeStamp - down.t <= 300;
      down = null;
      if (near && quick) fire();
    }
    list.forEach(function (p) { w.addEventListener(p[0], p[1], opt); });
    var prev = tl.eventCallback('onComplete');
    var params = tl.vars && tl.vars.onCompleteParams;
    tl.eventCallback('onComplete', function () { off(); if (prev) prev.apply(tl, params || []); });
    return off;
  }

  var LAZY = {
    player: { sel: 'a[data-clip], button[data-clip]', methods: ['open', 'close', 'isOpen', 'manifest', 'rail', 'hoverPreview'] },
    viewer: { sel: 'a[data-view]', methods: ['open', 'close'] }
  };
  var lazyNames = (P24.lazyComponents || []).filter(function (n) { return !!LAZY[n]; });
  var lazyLoads = {};
  var lazyReady = {};
  function findComponent(name) {
    for (var i = 0; i < components.length; i++) if (components[i].name === name) return components[i];
    return null;
  }
  function loadComponent(name) {
    if (lazyLoads[name]) return lazyLoads[name];
    lazyLoads[name] = new Promise(function (resolve, reject) {
      var s = d.createElement('script');
      s.src = 'js/components/' + name + '.js';
      s.async = true;
      s.onload = function () {
        var c = findComponent(name);
        if (!c) { reject(new Error('component ' + name + ' did not register')); return; }
        var api = c.factory(P24.ctx || makeCtx(h.classList.contains('js-motion')));
        if (P24.ctx) P24.ctx[name] = api;
        resolve(api);
      };
      s.onerror = function () { lazyLoads[name] = null; reject(new Error('component ' + name + ' failed to load')); };
      d.head.appendChild(s);
    });
    return lazyLoads[name];
  }
  function proxy(name) {
    var p = { lazy: true };
    LAZY[name].methods.forEach(function (m) {
      p[m] = function () {
        var a = arguments;
        return loadComponent(name).then(function (api) { return api[m].apply(api, a); });
      };
    });
    return p;
  }
  lazyNames.forEach(function (name) {
    var sel = LAZY[name].sel;
    d.addEventListener('click', function (e) {
      if (lazyReady[name]) return;
      var t = e.target.closest && e.target.closest(sel);
      if (!t || e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
      e.preventDefault();
      loadComponent(name).then(function (api) { api.open(t); }, function () { if (t.href) w.location.href = t.href; });
    });
    var warm = function (e) {
      if (lazyReady[name] || !e.target.closest || !e.target.closest(sel)) return;
      loadComponent(name).catch(function () { /* retried on click */ });
    };
    d.addEventListener('pointerover', warm, { passive: true });
    d.addEventListener('focusin', warm);
    d.addEventListener('touchstart', warm, { passive: true });
  });
  if (lazyNames.length) {
    w.addEventListener('load', function () {
      setTimeout(function () { lazyNames.forEach(function (n) { loadComponent(n).catch(function () { /* on demand */ }); }); }, 4000);
    }, { once: true });
  }

  function makeCtx(motionOK) {
    var mobile = mq(MQ_MOBILE);
    var ctx = {
      gsap: w.gsap || null,
      SplitText: w.SplitText || null,
      motionOK: motionOK,
      mobile: mobile,
      coarse: mq('(pointer: coarse)'),
      qa: qa,
      lite: lite(),
      internalNav: h.classList.contains('vt-nav'),
      m1: { play: !h.classList.contains('m1-skip'), holdName: h.classList.contains('m1-type') },
      ease: EASE,
      dur: function (s) { return mq(MQ_MOBILE) ? s * MOBILE_FACTOR : s; },
      enter: enter,
      loadFlip: loadFlip,
      fontsReady: fontsReady,
      decodeAll: decodeAll,
      whenLoaded: whenLoaded,
      own: own,
      onFinal: onFinal,
      skipOnInput: skipOnInput,
      setIntro: function (intro) { P24.intro = intro || null; },
      vt: {
        internalNav: h.classList.contains('vt-nav'),
        supported: !!(P24._vt && P24._vt.supported),
        name: function (el, n) { if (P24._vt) P24._vt.name(el, n); }
      }
    };
    ctx.reveal = function (els, opts) { return P24._reveal ? P24._reveal(ctx, els, opts || {}) : undefined; };
    ctx.heading = function (el, opts) { return P24._type ? P24._type.heading(ctx, el, opts || {}) : undefined; };
    ctx.roll = function (el, text) {
      if (P24._type) return P24._type.roll(ctx, el, text);
      if (el) el.textContent = text;
      return undefined;
    };
    components.forEach(function (c) {
      try { ctx[c.name] = c.factory(ctx); } catch (err) { report('component:' + c.name, err); }
    });
    lazyNames.forEach(function (n) { if (!ctx[n]) ctx[n] = proxy(n); });
    return ctx;
  }

  function runUnits(motionOK) {
    var ctx = makeCtx(motionOK);
    P24.ctx = ctx;
    var cleanups = [];
    units.forEach(function (u) {
      try {
        var c = u.mod.init(ctx);
        if (typeof c === 'function') cleanups.push(c);
      } catch (err) {
        report(u.id, err);
        h.classList.remove('js-motion');
      }
    });
    return function () { cleanups.forEach(function (c) { try { c(); } catch (err) { report('cleanup', err); } }); };
  }

  P24.register = function (id, mod) {
    if (!id || !mod || typeof mod.init !== 'function') throw new Error('P24.register(id, { init }) expects an init function');
    if (units.some(function (u) { return u.id === id; })) throw new Error('P24.register: duplicate id ' + id);
    units.push({ id: id, mod: mod });
  };
  P24.component = function (name, factory) {
    if (!name || typeof factory !== 'function') throw new Error('P24.component(name, factory) expects a factory');
    if (components.some(function (c) { return c.name === name; })) throw new Error('P24.component: duplicate ' + name);
    components.push({ name: name, factory: factory });
    if (LAZY[name]) lazyReady[name] = true;
  };

  function boot() {
    if (P24.booted) return;
    P24.booted = true;
    var g = w.gsap;
    if (!g) { h.classList.remove('js-motion'); runUnits(false); return; }
    if (w.SplitText) g.registerPlugin(w.SplitText);
    g.config({ autoSleep: 60, nullTargetWarn: false });
    g.defaults({ ease: EASE.out, duration: 0.6 });
    var mm = g.matchMedia();
    P24.mm = mm;
    mm.add({ ok: MQ_MOTION, reduce: MQ_REDUCE }, function (c) {
      var ok = !!c.conditions.ok;
      h.classList.toggle('js-motion', ok);
      return runUnits(ok);
    });
  }

  P24.ease = EASE;
  P24.loadFlip = loadFlip;
  P24.finish = runFinals;

  if (qa) {
    w.__p24 = {
      seek: function (t) {
        var i = P24.intro;
        if (!i || !i.timeline) return false;
        i.timeline.pause();
        i.timeline.seek(Number(t) || 0, false);
        return true;
      },
      state: function () {
        return {
          booted: !!P24.booted,
          motion: h.classList.contains('js-motion'),
          classes: h.className,
          intro: !!P24.intro,
          vtLog: (P24.vtLog || []).slice(),
          errors: errors.slice()
        };
      },
      finish: runFinals
    };
  }

  if (d.readyState === 'loading') d.addEventListener('DOMContentLoaded', boot, { once: true });
  else setTimeout(boot, 0);
})(window, document);

(function (w) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};

  function list(x) {
    if (!x) return [];
    if (x.nodeType === 1) return [x];
    return Array.prototype.slice.call(x);
  }

  function lines(ctx, el, opts) {
    if (ctx.heading) { ctx.heading(el, { rootMargin: opts.rootMargin }); return; }
    var g = ctx.gsap;
    var ST = ctx.SplitText;
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () { g.set(el, { autoAlpha: 0 }); },
      play: function () {
        g.set(el, { autoAlpha: 1 });
        if (!ST) { g.from(el, { y: ctx.mobile ? 12 : 20, autoAlpha: 0, duration: ctx.dur(0.7) }); return; }
        var split = ST.create(el, { type: 'lines', mask: 'lines', linesClass: 'p24-line', aria: 'auto' });
        g.from(split.lines, {
          yPercent: 110,
          duration: ctx.dur(0.7),
          stagger: 0.08,
          ease: ctx.ease.out,
          onComplete: function () { split.revert(); }
        });
      },
      final: function () { g.set(el, { clearProps: 'opacity,visibility' }); }
    });
  }

  function photo(ctx, el, opts) {
    var g = ctx.gsap;
    var frame = el.classList.contains('p24-frame') ? el : el.querySelector('.p24-frame') || el;
    var img = frame.querySelector('img, video');
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () {
        g.set(frame, { clipPath: 'inset(100% 0% 0% 0%)' });
        if (img) g.set(img, { scale: 1.06, transformOrigin: '50% 100%' });
      },
      play: function () {
        var open = function () {
          var d = ctx.dur(0.8);
          g.to(frame, { clipPath: 'inset(0% 0% 0% 0%)', duration: d, ease: ctx.ease.out, clearProps: 'clipPath' });
          if (img) g.to(img, { scale: 1, duration: d, ease: ctx.ease.out, clearProps: 'transform' });
        };
        if (!img || img.tagName !== 'IMG' || !ctx.decodeAll) { open(); return; }
        if (img.loading === 'lazy') img.loading = 'eager';
        ctx.decodeAll([img], 900).then(function (ok) {
          if (ok) { open(); return; }
          g.set(frame, { clearProps: 'clipPath' });
          g.set(img, { clearProps: 'transform' });
        });
      },
      final: function () {
        g.set(frame, { clearProps: 'clipPath' });
        if (img) g.set(img, { clearProps: 'transform' });
      }
    });
  }

  function group(ctx, el, opts) {
    var g = ctx.gsap;
    var kids = Array.prototype.slice.call(el.children);
    if (!kids.length) return;
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () { g.set(kids, { y: ctx.mobile ? 12 : 16, autoAlpha: 0 }); },
      play: function () {
        g.to(kids, {
          y: 0,
          autoAlpha: 1,
          duration: ctx.dur(0.7),
          stagger: opts.stagger == null ? 0.06 : opts.stagger,
          ease: ctx.ease.out,
          clearProps: 'transform,opacity,visibility'
        });
      },
      final: function () { g.set(kids, { clearProps: 'transform,opacity,visibility' }); }
    });
  }

  P24._reveal = function (ctx, els, opts) {
    if (!ctx.motionOK || !ctx.gsap) return;
    var type = opts.type || 'group';
    list(els).forEach(function (el) {
      if (type === 'lines') lines(ctx, el, opts);
      else if (type === 'photo') photo(ctx, el, opts);
      else group(ctx, el, opts);
    });
  };
})(window);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var ROLL_TRAVEL = 8;

  function hasDeva(el) { return !!(el.closest('[lang="hi"]') || el.querySelector('[lang="hi"]')); }

  function rise(ctx, el, done) {
    var g = ctx.gsap;
    var ST = ctx.SplitText;
    var dur = ctx.mobile ? 0.6 : 0.7;
    g.set(el, { autoAlpha: 1 });
    if (!ST || hasDeva(el)) {
      g.from(el, { y: ctx.mobile ? 12 : 20, autoAlpha: 0, duration: dur, ease: ctx.ease.out, clearProps: 'transform,opacity,visibility', onComplete: done });
      return;
    }
    var tween = null;
    var split = ST.create(el, {
      type: 'lines',
      mask: 'lines',
      linesClass: 'p24-line',
      aria: 'auto'
    });
    tween = g.from(split.lines, {
      yPercent: 110,
      duration: dur,
      stagger: 0.08,
      ease: ctx.ease.out,
      onComplete: function () { split.revert(); if (done) done(); }
    });
    return split;
  }

  function heading(ctx, el, opts) {
    if (!el || !ctx.motionOK || !ctx.gsap) return;
    var g = ctx.gsap;
    if (opts.now) {
      if (ctx.internalNav) return;
      if (w.getComputedStyle(el).opacity !== '0') return;
      ctx.own(el);
      rise(ctx, el);
      return;
    }
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () { g.set(el, { autoAlpha: 0 }); },
      play: function () { rise(ctx, el); },
      final: function () { g.set(el, { clearProps: 'opacity,visibility' }); }
    });
  }

  function roll(ctx, el, text) {
    if (!el) return;
    text = text == null ? '' : String(text);
    if (el._p24roll) { el._p24roll.progress(1); el._p24roll = null; }
    var oldText = el.textContent;
    if (oldText === text) return;
    var g = ctx.gsap;
    if (!ctx.motionOK || !g || !el.isConnected || !oldText) { el.textContent = text; return; }
    el.classList.add('p24-roll');
    el.textContent = '';
    var next = d.createElement('span');
    next.className = 'p24-roll__new';
    next.textContent = text;
    var ghost = d.createElement('span');
    ghost.className = 'p24-roll__old';
    ghost.setAttribute('aria-hidden', 'true');
    ghost.textContent = oldText;
    el.appendChild(next);
    el.appendChild(ghost);
    var dur = ctx.dur(0.3);
    el._p24roll = g.timeline({
      onComplete: function () { el.textContent = text; el.classList.remove('p24-roll'); el._p24roll = null; }
    })
      .to(ghost, { y: -ROLL_TRAVEL, autoAlpha: 0, duration: dur * 0.7, ease: 'power2.in' }, 0)
      .from(next, { y: ROLL_TRAVEL, autoAlpha: 0, duration: dur, ease: ctx.ease.ui }, dur * 0.3);
  }

  P24._type = { heading: heading, roll: roll };
})(window, document);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var lastLink = null;
  var NAMES = { 'cta-panel': 1, 'family-hero': 1 };

  function visible(el) {
    if (!el) return false;
    var r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0 && r.bottom > 0 && r.top < w.innerHeight;
  }

  function sourceFor(link, name) {
    if (name === 'cta-panel') return link;
    var sel = link.getAttribute('data-vt-source');
    if (sel) { var s = d.querySelector(sel); if (visible(s)) return s; }
    var node = link.parentElement;
    while (node && node !== d.body) {
      var stages = node.querySelectorAll('[data-story-stage]');
      for (var i = 0; i < stages.length; i++) {
        var win = stages[i].querySelector('.p24-story__window') || stages[i];
        if (visible(win)) return win;
      }
      node = node.parentElement;
    }
    return null;
  }

  function showKeyFrame(link, win) {
    var block = link.closest('[data-story-block]');
    if (!block || !win || !win.classList.contains('p24-story__window')) return;
    var key = block.getAttribute('data-story-key');
    if (!key) { var st = block.querySelector('[data-story-step]'); key = st ? (st.getAttribute('data-story-step') || '').split(/\s+/)[0] : ''; }
    var layer = key ? win.querySelector('.p24-story__layer[data-frame="' + key + '"]') : null;
    if (!layer || !layer.style.width) return;
    var img = layer.querySelector('img');
    if (img && !img.complete) return;
    var all = win.querySelectorAll('.p24-story__layer');
    for (var i = 0; i < all.length; i++) {
      if (all[i].getAnimations) all[i].getAnimations().forEach(function (an) { an.cancel(); });
      if (all[i] !== layer) all[i].classList.remove('is-on', 'is-top');
    }
    if (win.getAnimations) win.getAnimations().forEach(function (an) { an.cancel(); });
    layer.classList.add('is-on');
    layer.style.clipPath = '';
    var area = win.parentElement || win;
    var l = parseFloat(layer.style.left) || 0, t = parseFloat(layer.style.top) || 0;
    var lw = parseFloat(layer.style.width) || 0, lh = parseFloat(layer.style.height) || 0;
    win.style.clipPath = 'inset(' + t + 'px ' + Math.max(0, area.clientWidth - l - lw) + 'px ' + Math.max(0, area.clientHeight - t - lh) + 'px ' + l + 'px)';
  }

  function name(el, n) {
    if (!el || !n) return;
    var prev = d.querySelectorAll('[data-vt-named]');
    for (var i = 0; i < prev.length; i++) {
      if (prev[i].style.viewTransitionName === n) { prev[i].style.viewTransitionName = ''; prev[i].removeAttribute('data-vt-named'); }
    }
    el.style.viewTransitionName = n;
    el.setAttribute('data-vt-named', '');
  }
  function clearAll() {
    var named = d.querySelectorAll('[data-vt-named]');
    for (var i = 0; i < named.length; i++) { named[i].style.viewTransitionName = ''; named[i].removeAttribute('data-vt-named'); }
  }

  d.addEventListener('click', function (e) {
    var a = e.target && e.target.closest ? e.target.closest('a[href]') : null;
    lastLink = a && a.hasAttribute('data-vt') ? a : null;
  }, true);

  w.addEventListener('pageswap', function (e) {
    var vt = e.viewTransition;
    try { w.sessionStorage.removeItem('p24-vt'); } catch (err) { /* storage off: pairs are skipped */ }
    if (!vt) return;
    try {
      clearAll();
      var link = lastLink;
      lastLink = null;
      var entry = e.activation && e.activation.entry;
      if (!link || !entry || link.href !== entry.url) return;
      var n = link.getAttribute('data-vt');
      if (!NAMES[n]) return;
      var src = sourceFor(link, n);
      if (!visible(src)) return;
      if (n === 'family-hero') showKeyFrame(link, src);
      name(src, n);
      w.sessionStorage.setItem('p24-vt', n);
      if (d.documentElement.classList.contains('qa')) {
        var r = src.getBoundingClientRect();
        w.sessionStorage.setItem('p24-vtlog', JSON.stringify({ name: n, source: src.tagName.toLowerCase() + '.' + String(src.className).split(' ')[0], rect: [Math.round(r.left), Math.round(r.top), Math.round(r.width), Math.round(r.height)], url: entry.url }));
      }
    } catch (err) {
      vt.skipTransition();
    }
  });

  w.addEventListener('pageshow', function (e) { if (e.persisted) { clearAll(); lastLink = null; } });

  P24._vt = {
    name: name,
    clear: clearAll,
    internalNav: function () { return d.documentElement.classList.contains('vt-nav'); },
    supported: typeof d.startViewTransition === 'function' && !!w.CSS && CSS.supports('view-transition-name: none')
  };
})(window, document);

(function (w, d) {
  'use strict';
  var h = d.documentElement;
  var body = d.body;
  var hasIO = 'IntersectionObserver' in w;
  function each(sel, fn) { Array.prototype.forEach.call(d.querySelectorAll(sel), fn); }

  var page = body.getAttribute('data-page');
  each('[data-nav]', function (a) {
    if (page && a.getAttribute('data-nav') === page) a.setAttribute('aria-current', 'page');
  });

  var menuBtn = d.querySelector('[data-menu-open]');
  var menu = d.getElementById('p24-menu');
  if (menuBtn && menu && typeof menu.showModal === 'function') {
    var closeBtn = menu.querySelector('[data-menu-close]');
    var setOpen = function (open) {
      if (open && !menu.open) menu.showModal();
      if (!open && menu.open) menu.close();
      menuBtn.setAttribute('aria-expanded', String(open));
    };
    menuBtn.addEventListener('click', function () { setOpen(true); });
    if (closeBtn) closeBtn.addEventListener('click', function () { setOpen(false); });
    menu.addEventListener('close', function () {
      menuBtn.setAttribute('aria-expanded', 'false');
      menuBtn.focus({ preventScroll: true });
    });
    menu.addEventListener('click', function (e) {
      var a = e.target.closest('a');
      if (a && a.getAttribute('href').charAt(0) === '#') setOpen(false);
    });
    var closedOnHide = false;
    var reset = function () {
      menuBtn.setAttribute('aria-expanded', 'false');
      menuBtn.textContent = 'Menu';
      if (menu.open) menu.close();
    };
    w.addEventListener('pagehide', function () { if (menu.open) { closedOnHide = true; reset(); } });
    w.addEventListener('pageshow', function (e) {
      if (!e.persisted) return;
      var was = closedOnHide || menu.open;
      closedOnHide = false;
      reset();
      if (was) menuBtn.focus({ preventScroll: true });
    });
    var mqWide = w.matchMedia('(min-width: 761px)');
    var onWide = function () { if (mqWide.matches) setOpen(false); };
    if (mqWide.addEventListener) mqWide.addEventListener('change', onWide);
  } else if (menuBtn) {
    menuBtn.addEventListener('click', function () { var f = d.getElementById('p24-footer-pages'); if (f) f.scrollIntoView(); });
  }

  var dock = d.querySelector('[data-dock]');
  if (dock && !body.hasAttribute('data-no-dock')) {
    var sentinels = d.querySelectorAll('[data-dock-sentinel]');
    var footerCta = d.querySelector('[data-footer-cta]');
    var state = { sentinel: sentinels.length > 0, footer: false, typing: false };
    d.addEventListener('p24:dock', function () { render(); });
    var links = dock.querySelectorAll('a, button');
    var render = function () {
      var show = !state.sentinel && !state.footer && !state.typing && !h.classList.contains('story-stuck');
      if (show) dock.setAttribute('data-show', ''); else dock.removeAttribute('data-show');
      h.classList.toggle('dock-on', show);
      dock.setAttribute('aria-hidden', String(!show));
      Array.prototype.forEach.call(links, function (l) { l.tabIndex = show ? 0 : -1; });
    };
    if (hasIO && sentinels.length) {
      var seen = new Set();
      var ioS = new IntersectionObserver(function (entries) {
        entries.forEach(function (e) {
          if (e.isIntersecting && e.intersectionRatio >= 0.99) seen.add(e.target); else seen.delete(e.target);
        });
        state.sentinel = seen.size > 0;
        render();
      }, { threshold: [0, 0.99, 1] });
      Array.prototype.forEach.call(sentinels, function (s) { ioS.observe(s); });
    }
    if (hasIO && footerCta) {
      new IntersectionObserver(function (entries) {
        state.footer = entries[0].isIntersecting;
        render();
      }).observe(footerCta);
    }
    d.addEventListener('focusin', function (e) {
      state.typing = !!(e.target.closest && e.target.closest('input, select, textarea'));
      render();
    });
    render();
  }

  each('[data-replay-opening]', function (a) {
    a.addEventListener('click', function (e) {
      if (e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
      e.preventDefault();
      if ('scrollRestoration' in w.history) w.history.scrollRestoration = 'manual';
      w.scrollTo(0, 0);
      w.location.reload();
    });
  });

  if (h.classList.contains('qa')) {
    var qaBox = d.createElement('pre');
    qaBox.className = 'p24-qa';
    qaBox.setAttribute('aria-hidden', 'true');
    var draw = function () {
      var P24 = w.P24 || {};
      var NL = String.fromCharCode(10);
      qaBox.textContent = 'P24 QA · ' + h.className + NL + (P24.vtLog || []).map(function (x) { return JSON.stringify(x); }).join(NL);
    };
    draw();
    body.appendChild(qaBox);
    setTimeout(draw, 1200);
  }
})(window, document);

(function (w, d) {
  'use strict';

  var P24 = w.P24;
  if (!P24 || !P24.register) return;

  var ctx = null;
  var flip = null;
  var running = null;
  var bound = false;
  var ui = {};

  var LABELS = {
    as: 'Enquiring as', format: 'Format', date: 'Date or month', flexible: 'Dates flexible', city: 'City and country',
    name: 'Name', contact: 'Reply to', setting: 'In person or virtual', language: 'Hosting language',
    audience: 'Audience size', room: 'Who is in the room', org: 'Organisation', agency: 'Agency', budget: 'Budget range', notes: 'Anything else',
    kind: 'Request', message: 'Question'
  };
  var AS_TEXT = { agency: 'An event agency', host: 'The company hosting the event', other: 'Other' };
  var ORDER = ['as', 'date', 'flexible', 'city', 'format', 'name', 'contact', 'setting', 'language', 'audience', 'room', 'org', 'agency', 'budget', 'notes'];
  var ORDER_ASK = ['kind', 'as', 'message', 'name', 'contact', 'date', 'city'];
  var KIND_TEXT = { enquiry: 'An enquiry (no date yet)' };
  var STEP_LINE = { 1: 'Step 1 of 2 · Required', 2: 'Step 2 of 2 · Optional' };

  function each(list, fn) { Array.prototype.forEach.call(list, fn); }
  function motion() { return !!(ctx && ctx.motionOK && ctx.gsap); }
  function dur(s) { return ctx && ctx.dur ? ctx.dur(s) : s; }
  function smooth() { return motion() ? 'smooth' : 'auto'; }

  function checkContact(v) {
    if (!v) return 'Add a phone or WhatsApp number, or an email address, for the reply.';
    var isEmail = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(v);
    var digits = v.replace(/[^\d]/g, '');
    var isPhone = /^[+\d\s().-]+$/.test(v) && digits.length >= 8 && digits.length <= 15;
    return isEmail || isPhone ? '' : 'This does not look like a phone number or an email address.';
  }

  var RULES = [
    { name: 'as', target: 'f-as', check: function (v) { return v ? '' : 'Choose who is enquiring.'; } },
    { name: 'date', target: 'f-date', check: function (v) { return v ? '' : 'Add a date or a month. If it can move, tick Dates are flexible.'; } },
    { name: 'city', target: 'f-city', check: function (v) { return v ? '' : 'Add the city, and the country if it is outside India.'; } },
    { name: 'format', target: 'f-format', check: function (v) { return v ? '' : 'Choose a format, or Other.'; } },
    { name: 'name', target: 'f-name', check: function (v) { return v ? '' : 'Add your name.'; } },
    { name: 'contact', target: 'f-contact', check: checkContact }
  ];
  var ASK_RULES = [
    { name: 'message', target: 'q-message', check: function (v) { return v ? '' : 'Write your question.'; } },
    { name: 'name', target: 'q-name', check: function (v) { return v ? '' : 'Add your name.'; } },
    { name: 'contact', target: 'q-contact', check: checkContact }
  ];

  function valueOf(form, name) {
    var el = form && form.elements[name];
    if (!el) return '';
    if (el.type === 'checkbox') return el.checked ? el.value : '';
    return String(el.value || '').trim();
  }
  function value(name) { return valueOf(ui.form, name); }
  function askValue(name) { return valueOf(ui.ask, name); }


  function finishRunning() {
    for (var i = 0; i < 3 && running; i++) {
      var r = running;
      r.progress(1);
      if (running === r) running = null;
    }
  }

  function plateTween(tl, plate, state, h0) {
    var g = ctx.gsap;
    if (!plate) return;
    if (flip && state) {
      tl.add(flip.from(state, { targets: plate, scale: true, duration: dur(0.35), ease: ctx.ease.inOut }), 0);
      tl.set(plate, { clearProps: 'transform' });
      return;
    }
    var h1 = plate.getBoundingClientRect().height;
    if (!h0 || !h1 || Math.abs(h0 - h1) < 2) return;
    tl.fromTo(plate, { scaleY: h0 / h1, transformOrigin: '50% 0%' },
      { scaleY: 1, duration: dur(0.35), ease: ctx.ease.inOut, clearProps: 'transform' }, 0);
  }

  function change(o) {
    finishRunning();
    if (!motion()) { o.mutate(); if (o.after) o.after(); return; }
    var g = ctx.gsap;
    var outgoing = (o.outgoing || []).filter(function (el) { return el && el.getClientRects().length; });
    var phase2 = function () {
      var plate = o.plate;
      var state = flip && plate ? flip.getState(plate) : null;
      var h0 = plate ? plate.getBoundingClientRect().height : 0;
      g.set(outgoing, { clearProps: 'opacity,transform' });
      o.mutate();
      var tl = g.timeline({ onComplete: function () { if (running === tl) running = null; } });
      running = tl;
      plateTween(tl, plate, state, h0);
      if (o.extra) o.extra(tl);
      if (o.incoming) {
        tl.from(o.incoming, {
          opacity: 0, y: ctx.mobile ? 10 : 12, duration: dur(o.inDur || 0.4), ease: ctx.ease.out,
          immediateRender: true, clearProps: 'opacity,transform'
        }, 0.1);
      }
      if (o.after) o.after();
    };
    if (!outgoing.length) { phase2(); return; }
    var out = g.to(outgoing, {
      opacity: 0, y: -8, duration: dur(0.15), ease: 'power2.in',
      onComplete: function () { if (running === out) running = null; phase2(); }
    });
    running = out;
  }


  function currentStep() { return Number(ui.form.getAttribute('data-step')) || 1; }

  function scrollToCard() {
    var top = ui.card.getBoundingClientRect().top;
    if (top < 0 || top > w.innerHeight * 0.4) ui.card.scrollIntoView({ behavior: smooth(), block: 'start' });
  }

  function applyStep(n) {
    ui.form.setAttribute('data-step', String(n));
    ui.card.setAttribute('data-step', String(n));
    if (ui.step1Actions) ui.step1Actions.hidden = n !== 1;
    if (ui.backBtn) ui.backBtn.hidden = n !== 2;
    if (ui.segs[1]) ui.segs[1].classList.toggle('is-on', n === 2);
  }

  function setStep(n, focusHeading) {
    var from = currentStep();
    var step = ui.form.querySelector('[data-enq-step="' + n + '"]');
    var prev = ui.form.querySelector('[data-enq-step="' + from + '"]');
    var heading = step && step.querySelector('.enq-step__title');
    var headAlt = n === 2 ? ui.form.querySelector('.enq-submit') : ui.step1Actions;
    change({
      plate: ui.plate,
      outgoing: from === n ? [] : [prev, from === 2 ? ui.form.querySelector('.enq-submit') : ui.step1Actions, from === 1 ? ui.policy : null],
      incoming: from === n ? null : [step, headAlt, n === 1 ? ui.policy : null].filter(Boolean),
      mutate: function () { applyStep(n); },
      extra: function (tl) {
        if (ui.stepline) ctx.roll(ui.stepline, STEP_LINE[n]);
        var fill = ui.fills[1];
        if (fill) tl.to(fill, { scaleX: n === 2 ? 1 : 0, duration: dur(0.45), ease: ctx.ease.inOut }, 0.05);
      },
      after: function () {
        if (!motion()) {
          if (ui.stepline) ui.stepline.textContent = STEP_LINE[n];
          if (ui.fills[1]) ui.fills[1].style.transform = n === 2 ? 'none' : '';
        }
        if (focusHeading && heading) { heading.focus({ preventScroll: true }); scrollToCard(); }
      }
    });
  }


  function showFieldError(form, rule, msg) {
    var errEl = form.querySelector('[data-err-for="' + rule.name + '"]');
    var target = d.getElementById(rule.target);
    if (errEl) { errEl.textContent = msg; errEl.hidden = !msg; }
    if (!target) return;
    if (target.tagName === 'FIELDSET') {
      if (msg) target.setAttribute('data-invalid', ''); else target.removeAttribute('data-invalid');
    } else {
      target.setAttribute('aria-invalid', msg ? 'true' : 'false');
    }
  }

  function renderErrors(box, failed) {
    if (!box) return;
    var list = box.querySelector('[data-enq-errors-list]');
    var title = box.querySelector('[data-enq-errors-title]');
    while (list.firstChild) list.removeChild(list.firstChild);
    if (!failed.length) { box.hidden = true; return; }
    title.textContent = failed.length === 1 ? 'One thing to check' : 'A few things to check';
    failed.forEach(function (f) {
      var li = d.createElement('li');
      var a = d.createElement('a');
      a.href = '#' + f.rule.target;
      a.textContent = f.msg;
      a.addEventListener('click', function (e) {
        e.preventDefault();
        var t = d.getElementById(f.rule.target);
        var focusable = t && t.tagName === 'FIELDSET' ? (t.querySelector('input:checked') || t.querySelector('input')) : t;
        if (focusable) { focusable.focus({ preventScroll: true }); t.scrollIntoView({ block: 'center' }); }
      });
      li.appendChild(a);
      list.appendChild(li);
    });
    box.hidden = false;
  }

  function check(form, rules, get, show) {
    var failed = [];
    rules.forEach(function (rule) {
      var msg = rule.check(get(rule.name));
      if (show || !msg) showFieldError(form, rule, msg);
      if (msg) failed.push({ rule: rule, msg: msg });
    });
    return failed;
  }

  function focusErrors(box) {
    box.focus({ preventScroll: true });
    box.scrollIntoView({ behavior: smooth(), block: 'center' });
  }

  function passStep1() {
    ui.attempted = true;
    var failed = check(ui.form, RULES, value, true);
    renderErrors(ui.errorsBox, failed);
    if (!failed.length) return true;
    if (currentStep() === 2) { finishRunning(); applyStep(1); if (ui.stepline) ui.stepline.textContent = STEP_LINE[1]; syncFill(); }
    focusErrors(ui.errorsBox);
    return false;
  }


  function syncAsWording() {
    var isAgency = value('as') === 'agency';
    if (ui.orgLabel) ui.orgLabel.textContent = isAgency ? 'End client, if you can share it' : ui.orgDefault;
    if (ui.agencyLabel) ui.agencyLabel.textContent = isAgency ? 'Your agency' : ui.agencyDefault;
  }


  function readable(name, raw) {
    if (name === 'as') return AS_TEXT[raw] || raw;
    if (name === 'flexible') return raw ? 'Yes' : '';
    if (name === 'kind') return KIND_TEXT[raw] || '';
    return raw;
  }

  function renderEcho(get, order) {
    var summary = ui.summary;
    while (summary.firstChild) summary.removeChild(summary.firstChild);
    var isAgency = get('as') === 'agency';
    order.forEach(function (name) {
      var v = readable(name, get(name));
      if (!v) return;
      var row = d.createElement('div');
      row.className = 'enq-sheet__row';
      var dt = d.createElement('dt');
      var dd = d.createElement('dd');
      dt.textContent = isAgency && name === 'org' ? 'End client' : LABELS[name];
      dd.textContent = v;
      row.appendChild(dt);
      row.appendChild(dd);
      summary.appendChild(row);
    });
  }

  function showReceived() {
    var h2 = ui.received.querySelector('h2');
    change({
      plate: ui.plate,
      outgoing: [ui.form, ui.progress],
      incoming: [ui.received],
      inDur: 0.3,
      mutate: function () {
        ui.card.classList.add('is-sent');
        ui.received.classList.add('is-shown');
        if (ui.editBtn) ui.editBtn.hidden = false;
      },
      after: function () {
        if (h2) h2.focus({ preventScroll: true });
        ui.received.scrollIntoView({ behavior: smooth(), block: 'start' });
      }
    });
  }

  function hideReceived(then) {
    change({
      plate: ui.plate,
      outgoing: [ui.received],
      incoming: [ui.form, ui.progress],
      mutate: function () {
        ui.card.classList.remove('is-sent');
        ui.received.classList.remove('is-shown');
        if (w.location.hash === '#received' && w.history && w.history.replaceState) {
          w.history.replaceState(null, '', w.location.pathname + '#availability');
        }
      },
      after: then
    });
  }

  function syncFill() {
    var fill = ui.fills[1];
    if (!fill) return;
    if (motion()) ctx.gsap.set(fill, { scaleX: currentStep() === 2 ? 1 : 0 });
    else fill.style.transform = '';
  }


  function bind() {
    var form = ui.form;
    form.setAttribute('novalidate', '');
    if (ui.progress) ui.progress.hidden = false;
    if (ui.stepline) ui.stepline.hidden = false;
    applyStep(1);

    form.addEventListener('change', function (e) { if (e.target.name === 'as') syncAsWording(); });
    var revalidate = function (e) {
      if (!ui.attempted || !e.target.name) return;
      RULES.forEach(function (rule) { if (rule.name === e.target.name) showFieldError(form, rule, rule.check(value(rule.name))); });
      if (!RULES.some(function (r) { return r.check(value(r.name)); }) && ui.errorsBox) ui.errorsBox.hidden = true;
    };
    form.addEventListener('change', revalidate);
    form.addEventListener('input', revalidate);

    if (ui.nextBtn) ui.nextBtn.addEventListener('click', function () { if (passStep1()) setStep(2, true); });
    if (ui.backBtn) ui.backBtn.addEventListener('click', function () { setStep(1, true); });

    form.addEventListener('submit', function (e) {
      e.preventDefault();
      if (!passStep1()) return;
      ui.lastSource = 'availability';
      if (ui.editBtn) ui.editBtn.textContent = 'Edit the request';
      renderEcho(value, ORDER);
      showReceived();
    });

    if (ui.editBtn) {
      ui.editBtn.addEventListener('click', function () {
        if (ui.lastSource === 'enquiry' && ui.ask) {
          hideReceived(function () {
            var h = d.getElementById('enquiry-title');
            ui.ask.scrollIntoView({ behavior: smooth(), block: 'start' });
            if (h) h.focus({ preventScroll: true });
          });
          return;
        }
        hideReceived(function () {
          var h = ui.form.querySelector('[data-enq-step="' + currentStep() + '"] .enq-step__title');
          if (h) h.focus({ preventScroll: true });
          scrollToCard();
        });
      });
    }

    if (ui.ask) bindAsk();
    readArrival();

    var warm = function () {
      if (flip || !motion() || !ctx.loadFlip) return;
      ctx.loadFlip().then(function (F) { flip = F; }, function () { flip = null; });
    };
    each(d.querySelectorAll('.enq-card'), function (c) {
      c.addEventListener('focusin', warm, { once: true });
      c.addEventListener('pointerdown', warm, { once: true, passive: true });
      c.addEventListener('pointerover', warm, { once: true, passive: true });
    });
  }

  function bindAsk() {
    var ask = ui.ask;
    var box = ask.querySelector('[data-enq-errors]');
    var attempted = false;
    ask.setAttribute('novalidate', '');
    var re = function () {
      if (!attempted) return;
      if (!check(ask, ASK_RULES, askValue, false).length) box.hidden = true;
    };
    ask.addEventListener('input', re);
    ask.addEventListener('change', re);
    ask.addEventListener('submit', function (e) {
      e.preventDefault();
      attempted = true;
      var failed = check(ask, ASK_RULES, askValue, true);
      renderErrors(box, failed);
      if (failed.length) { focusErrors(box); return; }
      ui.lastSource = 'enquiry';
      renderEcho(askValue, ORDER_ASK);
      if (ui.editBtn) ui.editBtn.textContent = 'Edit the enquiry';
      showReceived();
    });
  }

  function readArrival() {
    var params;
    try { params = new URLSearchParams(w.location.search); } catch (err) { params = null; }
    if (!params) { syncAsWording(); return; }
    var as = params.get('as');
    if (as && AS_TEXT[as]) {
      [ui.form, ui.ask].forEach(function (f) {
        var radio = f && f.querySelector('input[name="as"][value="' + as + '"]');
        if (radio) radio.checked = true;
      });
    }
    syncAsWording();
    if (w.location.hash === '#received' && params.get('name')) {
      renderEcho(function (name) { return String(params.get(name) || '').trim(); }, params.get('kind') === 'enquiry' ? ORDER_ASK : ORDER);
      ui.card.classList.add('is-sent');
      ui.received.classList.add('is-shown');
      if (ui.editBtn) ui.editBtn.hidden = true;
      if (w.history && w.history.replaceState) w.history.replaceState(null, '', w.location.pathname + '#received');
    }
  }


  P24.register('enquire', {
    init: function (c) {
      var card = d.querySelector('[data-enq-card]');
      var form = card && card.querySelector('[data-enq-form]');
      if (!form) return undefined;
      ctx = c;
      if (!bound) {
        ui.card = card;
        ui.form = form;
        ui.plate = card.querySelector('[data-enq-plate]');
        ui.progress = card.querySelector('[data-enq-progress]');
        ui.segs = card.querySelectorAll('.enq-progress__seg');
        ui.fills = card.querySelectorAll('.enq-progress__fill');
        ui.stepline = form.querySelector('[data-enq-stepline]');
        ui.policy = form.querySelector('.enq-form__policy');
        ui.errorsBox = form.querySelector('[data-enq-errors]');
        ui.step1Actions = form.querySelector('[data-enq-step1-actions]');
        ui.nextBtn = form.querySelector('[data-enq-next]');
        ui.backBtn = form.querySelector('[data-enq-back]');
        ui.received = card.querySelector('[data-enq-received]');
        ui.summary = card.querySelector('[data-enq-summary]');
        ui.editBtn = card.querySelector('[data-enq-edit]');
        ui.ask = d.querySelector('[data-enq-ask]');
        ui.orgLabel = form.querySelector('[data-enq-org-label]');
        ui.agencyLabel = form.querySelector('[data-enq-agency-label]');
        ui.orgDefault = ui.orgLabel ? ui.orgLabel.textContent : '';
        ui.agencyDefault = ui.agencyLabel ? ui.agencyLabel.textContent : '';
        ui.lastSource = 'availability';
        ui.attempted = false;
        bind();
        bound = true;
      }
      syncFill();

      if (c.motionOK) {
        c.heading(d.getElementById('enq-title'), { now: true });
        c.heading(d.getElementById('next-title'));
        c.heading(d.getElementById('enquiry-title'));
        c.reveal(d.querySelector('[data-enq-nextsteps]'), { type: 'group' });
      }

      return function () {
        finishRunning();
        if (c.gsap) c.gsap.set([ui.plate].concat(Array.prototype.slice.call(ui.fills)), { clearProps: 'transform' });
        if (ui.stepline) ui.stepline.textContent = STEP_LINE[currentStep()];
      };
    }
  });
})(window, document);
