window.P24 = window.P24 || {};
window.P24.lazyComponents = [];
/* Prototype 24 · js/p24-watch.js — generated by tools/assemble.cjs from tools/pages.json; do not edit. */

(function (w, d) {
  'use strict';

  var h = d.documentElement;
  var MQ_MOTION = '(prefers-reduced-motion: no-preference)';
  var MQ_REDUCE = '(prefers-reduced-motion: reduce)';
  var MQ_MOBILE = '(max-width: 760px)';
  var EASE = Object.freeze({ out: 'expo.out', inOut: 'power3.inOut', ui: 'power2.out', window: 'cubic-bezier(.65,0,.35,1)', page: 'cubic-bezier(.16,1,.3,1)' });
  var FLIP_SRC = 'vendor/Flip.min.js';
  var MOBILE_FACTOR = 0.85;
  var SKIP_TO_END_S = 0.25;

  var P24 = w.P24 = w.P24 || {};
  var units = [];
  var components = [];
  var finals = [];
  var errors = P24.errors = P24.errors || [];
  var qa = h.classList.contains('qa');

  function mq(q) { return w.matchMedia(q).matches; }
  function toArray(x) {
    if (!x) return [];
    if (x.nodeType === 1) return [x];
    return Array.prototype.slice.call(x);
  }
  function timeout(ms, value) { return new Promise(function (resolve) { setTimeout(function () { resolve(value); }, ms); }); }
  function report(id, err) {
    errors.push({ unit: id, message: String(err && err.message || err) });
    setTimeout(function () { throw err; }, 0);
  }

  function own(els) { toArray(els).forEach(function (el) { el.classList.add('m-owned'); }); }

  function fontsReady(ms) {
    if (!d.fonts || !d.fonts.load) return Promise.resolve(true);
    return Promise.race([
      d.fonts.load('600 1em Eczar').then(function () { return true; }, function () { return false; }),
      timeout(ms == null ? 500 : ms, false)
    ]);
  }
  function whenLoaded(img) {
    if (!img) return Promise.resolve(false);
    if (img.complete && img.naturalWidth) return Promise.resolve(true);
    return new Promise(function (resolve) {
      img.addEventListener('load', function () { resolve(true); }, { once: true });
      img.addEventListener('error', function () { resolve(false); }, { once: true });
    });
  }
  function decodeOne(img) {
    if (!img) return Promise.resolve();
    if (img.decode) return img.decode();
    return whenLoaded(img);
  }
  function decodeAll(imgs, ms) {
    return Promise.race([
      Promise.all(toArray(imgs).map(decodeOne)).then(function () { return true; }, function () { return false; }),
      timeout(ms == null ? 600 : ms, false)
    ]);
  }
  function lite() {
    var c = w.navigator.connection;
    if (!c) return false;
    return !!c.saveData || /^(slow-2g|2g|3g)$/.test(c.effectiveType || '');
  }

  var flipPromise = null;
  function loadFlip() {
    if (w.Flip && w.gsap) { w.gsap.registerPlugin(w.Flip); return Promise.resolve(w.Flip); }
    if (flipPromise) return flipPromise;
    flipPromise = new Promise(function (resolve, reject) {
      var s = d.createElement('script');
      s.src = FLIP_SRC;
      s.async = true;
      s.onload = function () {
        if (!w.Flip || !w.gsap) { reject(new Error('Flip failed to load')); return; }
        w.gsap.registerPlugin(w.Flip);
        resolve(w.Flip);
      };
      s.onerror = function () { flipPromise = null; reject(new Error('Flip failed to load')); };
      d.head.appendChild(s);
    });
    return flipPromise;
  }

  function onFinal(fn) { if (typeof fn === 'function') finals.push(fn); }

  function enter(el, o) {
    if (!el || !o || typeof o.play !== 'function' || !('IntersectionObserver' in w)) return;
    var state = 'unknown';
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (e) {
        if (state === 'unknown') {
          var below = e.boundingClientRect.top >= (w.innerHeight || h.clientHeight);
          if (!below) { state = 'static'; io.disconnect(); return; }
          state = 'waiting';
          if (o.prepare) o.prepare(el);
          onFinal(function () { if (state === 'waiting') { state = 'done'; io.disconnect(); finish(); } });
          return;
        }
        if (state === 'waiting' && e.isIntersecting) { state = 'done'; io.disconnect(); o.play(el); }
      });
    }, { rootMargin: o.rootMargin || '0px 0px -15% 0px' });
    var jumpTimer = 0;
    function onJump() {
      clearTimeout(jumpTimer);
      jumpTimer = setTimeout(function () {
        if (state !== 'waiting') { w.removeEventListener('scroll', onJump); return; }
        if (el.getBoundingClientRect().bottom <= 0) { state = 'done'; io.disconnect(); w.removeEventListener('scroll', onJump); finish(); }
      }, 150);
    }
    w.addEventListener('scroll', onJump, { passive: true });
    function finish() {
      if (o.final) { o.final(el); return; }
      el.style.opacity = ''; el.style.transform = ''; el.style.clipPath = ''; el.style.visibility = '';
    }
    io.observe(el);
  }

  function runFinals() {
    var g = w.gsap;
    if (g && g.globalTimeline) g.globalTimeline.getChildren(true, true, true).forEach(function (t) { if (t.progress() < 1) t.progress(1); });
    if (d.getAnimations) d.getAnimations().forEach(function (a) { try { if (a.effect && a.effect.getTiming().iterations !== Infinity) a.finish(); } catch (err) { /* not finishable */ } });
    finals.slice().forEach(function (fn) { try { fn(); } catch (err) { report('final', err); } });
  }
  w.addEventListener('beforeprint', runFinals);
  d.addEventListener('beforematch', runFinals, true);

  var MOD_KEY = /^(Shift|Control|Alt|Meta|F\d{1,2})$/;
  function skipOnInput(tl) {
    if (!tl) return function () {};
    var coarse = mq('(pointer: coarse)');
    var startY = w.scrollY;
    var down = null;
    var opt = { passive: true, capture: true };
    var done = false;
    var list = [['keydown', onKey]];
    if (coarse) list.push(['pointerdown', onDown], ['pointerup', onUp]);
    else list.push(['wheel', fire], ['pointerdown', fire], ['scroll', onScroll]);
    function off() {
      if (done) return;
      done = true;
      list.forEach(function (p) { w.removeEventListener(p[0], p[1], opt); });
    }
    function fire() {
      off();
      if (qa) { tl.progress(1); return; }
      var rem = tl.duration() - tl.time();
      if (rem > 0) tl.timeScale(Math.max(tl.timeScale(), rem / SKIP_TO_END_S));
    }
    function onKey(e) { if (!MOD_KEY.test(e.key || '')) fire(); }
    function onScroll() { if (Math.abs(w.scrollY - startY) > 8) fire(); }
    function onDown(e) { down = { x: e.clientX, y: e.clientY, t: e.timeStamp }; }
    function onUp(e) {
      if (!down) return;
      var near = Math.abs(e.clientX - down.x) <= 10 && Math.abs(e.clientY - down.y) <= 10;
      var quick = e.timeStamp - down.t <= 300;
      down = null;
      if (near && quick) fire();
    }
    list.forEach(function (p) { w.addEventListener(p[0], p[1], opt); });
    var prev = tl.eventCallback('onComplete');
    var params = tl.vars && tl.vars.onCompleteParams;
    tl.eventCallback('onComplete', function () { off(); if (prev) prev.apply(tl, params || []); });
    return off;
  }

  var LAZY = {
    player: { sel: 'a[data-clip], button[data-clip]', methods: ['open', 'close', 'isOpen', 'manifest', 'rail', 'hoverPreview'] },
    viewer: { sel: 'a[data-view]', methods: ['open', 'close'] }
  };
  var lazyNames = (P24.lazyComponents || []).filter(function (n) { return !!LAZY[n]; });
  var lazyLoads = {};
  var lazyReady = {};
  function findComponent(name) {
    for (var i = 0; i < components.length; i++) if (components[i].name === name) return components[i];
    return null;
  }
  function loadComponent(name) {
    if (lazyLoads[name]) return lazyLoads[name];
    lazyLoads[name] = new Promise(function (resolve, reject) {
      var s = d.createElement('script');
      s.src = 'js/components/' + name + '.js';
      s.async = true;
      s.onload = function () {
        var c = findComponent(name);
        if (!c) { reject(new Error('component ' + name + ' did not register')); return; }
        var api = c.factory(P24.ctx || makeCtx(h.classList.contains('js-motion')));
        if (P24.ctx) P24.ctx[name] = api;
        resolve(api);
      };
      s.onerror = function () { lazyLoads[name] = null; reject(new Error('component ' + name + ' failed to load')); };
      d.head.appendChild(s);
    });
    return lazyLoads[name];
  }
  function proxy(name) {
    var p = { lazy: true };
    LAZY[name].methods.forEach(function (m) {
      p[m] = function () {
        var a = arguments;
        return loadComponent(name).then(function (api) { return api[m].apply(api, a); });
      };
    });
    return p;
  }
  lazyNames.forEach(function (name) {
    var sel = LAZY[name].sel;
    d.addEventListener('click', function (e) {
      if (lazyReady[name]) return;
      var t = e.target.closest && e.target.closest(sel);
      if (!t || e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
      e.preventDefault();
      loadComponent(name).then(function (api) { api.open(t); }, function () { if (t.href) w.location.href = t.href; });
    });
    var warm = function (e) {
      if (lazyReady[name] || !e.target.closest || !e.target.closest(sel)) return;
      loadComponent(name).catch(function () { /* retried on click */ });
    };
    d.addEventListener('pointerover', warm, { passive: true });
    d.addEventListener('focusin', warm);
    d.addEventListener('touchstart', warm, { passive: true });
  });
  if (lazyNames.length) {
    w.addEventListener('load', function () {
      setTimeout(function () { lazyNames.forEach(function (n) { loadComponent(n).catch(function () { /* on demand */ }); }); }, 4000);
    }, { once: true });
  }

  function makeCtx(motionOK) {
    var mobile = mq(MQ_MOBILE);
    var ctx = {
      gsap: w.gsap || null,
      SplitText: w.SplitText || null,
      motionOK: motionOK,
      mobile: mobile,
      coarse: mq('(pointer: coarse)'),
      qa: qa,
      lite: lite(),
      internalNav: h.classList.contains('vt-nav'),
      m1: { play: !h.classList.contains('m1-skip'), holdName: h.classList.contains('m1-type') },
      ease: EASE,
      dur: function (s) { return mq(MQ_MOBILE) ? s * MOBILE_FACTOR : s; },
      enter: enter,
      loadFlip: loadFlip,
      fontsReady: fontsReady,
      decodeAll: decodeAll,
      whenLoaded: whenLoaded,
      own: own,
      onFinal: onFinal,
      skipOnInput: skipOnInput,
      setIntro: function (intro) { P24.intro = intro || null; },
      vt: {
        internalNav: h.classList.contains('vt-nav'),
        supported: !!(P24._vt && P24._vt.supported),
        name: function (el, n) { if (P24._vt) P24._vt.name(el, n); }
      }
    };
    ctx.reveal = function (els, opts) { return P24._reveal ? P24._reveal(ctx, els, opts || {}) : undefined; };
    ctx.heading = function (el, opts) { return P24._type ? P24._type.heading(ctx, el, opts || {}) : undefined; };
    ctx.roll = function (el, text) {
      if (P24._type) return P24._type.roll(ctx, el, text);
      if (el) el.textContent = text;
      return undefined;
    };
    components.forEach(function (c) {
      try { ctx[c.name] = c.factory(ctx); } catch (err) { report('component:' + c.name, err); }
    });
    lazyNames.forEach(function (n) { if (!ctx[n]) ctx[n] = proxy(n); });
    return ctx;
  }

  function runUnits(motionOK) {
    var ctx = makeCtx(motionOK);
    P24.ctx = ctx;
    var cleanups = [];
    units.forEach(function (u) {
      try {
        var c = u.mod.init(ctx);
        if (typeof c === 'function') cleanups.push(c);
      } catch (err) {
        report(u.id, err);
        h.classList.remove('js-motion');
      }
    });
    return function () { cleanups.forEach(function (c) { try { c(); } catch (err) { report('cleanup', err); } }); };
  }

  P24.register = function (id, mod) {
    if (!id || !mod || typeof mod.init !== 'function') throw new Error('P24.register(id, { init }) expects an init function');
    if (units.some(function (u) { return u.id === id; })) throw new Error('P24.register: duplicate id ' + id);
    units.push({ id: id, mod: mod });
  };
  P24.component = function (name, factory) {
    if (!name || typeof factory !== 'function') throw new Error('P24.component(name, factory) expects a factory');
    if (components.some(function (c) { return c.name === name; })) throw new Error('P24.component: duplicate ' + name);
    components.push({ name: name, factory: factory });
    if (LAZY[name]) lazyReady[name] = true;
  };

  function boot() {
    if (P24.booted) return;
    P24.booted = true;
    var g = w.gsap;
    if (!g) { h.classList.remove('js-motion'); runUnits(false); return; }
    if (w.SplitText) g.registerPlugin(w.SplitText);
    g.config({ autoSleep: 60, nullTargetWarn: false });
    g.defaults({ ease: EASE.out, duration: 0.6 });
    var mm = g.matchMedia();
    P24.mm = mm;
    mm.add({ ok: MQ_MOTION, reduce: MQ_REDUCE }, function (c) {
      var ok = !!c.conditions.ok;
      h.classList.toggle('js-motion', ok);
      return runUnits(ok);
    });
  }

  P24.ease = EASE;
  P24.loadFlip = loadFlip;
  P24.finish = runFinals;

  if (qa) {
    w.__p24 = {
      seek: function (t) {
        var i = P24.intro;
        if (!i || !i.timeline) return false;
        i.timeline.pause();
        i.timeline.seek(Number(t) || 0, false);
        return true;
      },
      state: function () {
        return {
          booted: !!P24.booted,
          motion: h.classList.contains('js-motion'),
          classes: h.className,
          intro: !!P24.intro,
          vtLog: (P24.vtLog || []).slice(),
          errors: errors.slice()
        };
      },
      finish: runFinals
    };
  }

  if (d.readyState === 'loading') d.addEventListener('DOMContentLoaded', boot, { once: true });
  else setTimeout(boot, 0);
})(window, document);

(function (w) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};

  function list(x) {
    if (!x) return [];
    if (x.nodeType === 1) return [x];
    return Array.prototype.slice.call(x);
  }

  function lines(ctx, el, opts) {
    if (ctx.heading) { ctx.heading(el, { rootMargin: opts.rootMargin }); return; }
    var g = ctx.gsap;
    var ST = ctx.SplitText;
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () { g.set(el, { autoAlpha: 0 }); },
      play: function () {
        g.set(el, { autoAlpha: 1 });
        if (!ST) { g.from(el, { y: ctx.mobile ? 12 : 20, autoAlpha: 0, duration: ctx.dur(0.7) }); return; }
        var split = ST.create(el, { type: 'lines', mask: 'lines', linesClass: 'p24-line', aria: 'auto' });
        g.from(split.lines, {
          yPercent: 110,
          duration: ctx.dur(0.7),
          stagger: 0.08,
          ease: ctx.ease.out,
          onComplete: function () { split.revert(); }
        });
      },
      final: function () { g.set(el, { clearProps: 'opacity,visibility' }); }
    });
  }

  function photo(ctx, el, opts) {
    var g = ctx.gsap;
    var frame = el.classList.contains('p24-frame') ? el : el.querySelector('.p24-frame') || el;
    var img = frame.querySelector('img, video');
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () {
        g.set(frame, { clipPath: 'inset(100% 0% 0% 0%)' });
        if (img) g.set(img, { scale: 1.06, transformOrigin: '50% 100%' });
      },
      play: function () {
        var open = function () {
          var d = ctx.dur(0.8);
          g.to(frame, { clipPath: 'inset(0% 0% 0% 0%)', duration: d, ease: ctx.ease.out, clearProps: 'clipPath' });
          if (img) g.to(img, { scale: 1, duration: d, ease: ctx.ease.out, clearProps: 'transform' });
        };
        if (!img || img.tagName !== 'IMG' || !ctx.decodeAll) { open(); return; }
        if (img.loading === 'lazy') img.loading = 'eager';
        ctx.decodeAll([img], 900).then(function (ok) {
          if (ok) { open(); return; }
          g.set(frame, { clearProps: 'clipPath' });
          g.set(img, { clearProps: 'transform' });
        });
      },
      final: function () {
        g.set(frame, { clearProps: 'clipPath' });
        if (img) g.set(img, { clearProps: 'transform' });
      }
    });
  }

  function group(ctx, el, opts) {
    var g = ctx.gsap;
    var kids = Array.prototype.slice.call(el.children);
    if (!kids.length) return;
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () { g.set(kids, { y: ctx.mobile ? 12 : 16, autoAlpha: 0 }); },
      play: function () {
        g.to(kids, {
          y: 0,
          autoAlpha: 1,
          duration: ctx.dur(0.7),
          stagger: opts.stagger == null ? 0.06 : opts.stagger,
          ease: ctx.ease.out,
          clearProps: 'transform,opacity,visibility'
        });
      },
      final: function () { g.set(kids, { clearProps: 'transform,opacity,visibility' }); }
    });
  }

  P24._reveal = function (ctx, els, opts) {
    if (!ctx.motionOK || !ctx.gsap) return;
    var type = opts.type || 'group';
    list(els).forEach(function (el) {
      if (type === 'lines') lines(ctx, el, opts);
      else if (type === 'photo') photo(ctx, el, opts);
      else group(ctx, el, opts);
    });
  };
})(window);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var ROLL_TRAVEL = 8;

  function hasDeva(el) { return !!(el.closest('[lang="hi"]') || el.querySelector('[lang="hi"]')); }

  function rise(ctx, el, done) {
    var g = ctx.gsap;
    var ST = ctx.SplitText;
    var dur = ctx.mobile ? 0.6 : 0.7;
    g.set(el, { autoAlpha: 1 });
    if (!ST || hasDeva(el)) {
      g.from(el, { y: ctx.mobile ? 12 : 20, autoAlpha: 0, duration: dur, ease: ctx.ease.out, clearProps: 'transform,opacity,visibility', onComplete: done });
      return;
    }
    var tween = null;
    var split = ST.create(el, {
      type: 'lines',
      mask: 'lines',
      linesClass: 'p24-line',
      aria: 'auto'
    });
    tween = g.from(split.lines, {
      yPercent: 110,
      duration: dur,
      stagger: 0.08,
      ease: ctx.ease.out,
      onComplete: function () { split.revert(); if (done) done(); }
    });
    return split;
  }

  function heading(ctx, el, opts) {
    if (!el || !ctx.motionOK || !ctx.gsap) return;
    var g = ctx.gsap;
    if (opts.now) {
      if (ctx.internalNav) return;
      if (w.getComputedStyle(el).opacity !== '0') return;
      ctx.own(el);
      rise(ctx, el);
      return;
    }
    ctx.enter(el, {
      rootMargin: opts.rootMargin,
      prepare: function () { g.set(el, { autoAlpha: 0 }); },
      play: function () { rise(ctx, el); },
      final: function () { g.set(el, { clearProps: 'opacity,visibility' }); }
    });
  }

  function roll(ctx, el, text) {
    if (!el) return;
    text = text == null ? '' : String(text);
    if (el._p24roll) { el._p24roll.progress(1); el._p24roll = null; }
    var oldText = el.textContent;
    if (oldText === text) return;
    var g = ctx.gsap;
    if (!ctx.motionOK || !g || !el.isConnected || !oldText) { el.textContent = text; return; }
    el.classList.add('p24-roll');
    el.textContent = '';
    var next = d.createElement('span');
    next.className = 'p24-roll__new';
    next.textContent = text;
    var ghost = d.createElement('span');
    ghost.className = 'p24-roll__old';
    ghost.setAttribute('aria-hidden', 'true');
    ghost.textContent = oldText;
    el.appendChild(next);
    el.appendChild(ghost);
    var dur = ctx.dur(0.3);
    el._p24roll = g.timeline({
      onComplete: function () { el.textContent = text; el.classList.remove('p24-roll'); el._p24roll = null; }
    })
      .to(ghost, { y: -ROLL_TRAVEL, autoAlpha: 0, duration: dur * 0.7, ease: 'power2.in' }, 0)
      .from(next, { y: ROLL_TRAVEL, autoAlpha: 0, duration: dur, ease: ctx.ease.ui }, dur * 0.3);
  }

  P24._type = { heading: heading, roll: roll };
})(window, document);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var lastLink = null;
  var NAMES = { 'cta-panel': 1, 'family-hero': 1 };

  function visible(el) {
    if (!el) return false;
    var r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0 && r.bottom > 0 && r.top < w.innerHeight;
  }

  function sourceFor(link, name) {
    if (name === 'cta-panel') return link;
    var sel = link.getAttribute('data-vt-source');
    if (sel) { var s = d.querySelector(sel); if (visible(s)) return s; }
    var node = link.parentElement;
    while (node && node !== d.body) {
      var stages = node.querySelectorAll('[data-story-stage]');
      for (var i = 0; i < stages.length; i++) {
        var win = stages[i].querySelector('.p24-story__window') || stages[i];
        if (visible(win)) return win;
      }
      node = node.parentElement;
    }
    return null;
  }

  function showKeyFrame(link, win) {
    var block = link.closest('[data-story-block]');
    if (!block || !win || !win.classList.contains('p24-story__window')) return;
    var key = block.getAttribute('data-story-key');
    if (!key) { var st = block.querySelector('[data-story-step]'); key = st ? (st.getAttribute('data-story-step') || '').split(/\s+/)[0] : ''; }
    var layer = key ? win.querySelector('.p24-story__layer[data-frame="' + key + '"]') : null;
    if (!layer || !layer.style.width) return;
    var img = layer.querySelector('img');
    if (img && !img.complete) return;
    var all = win.querySelectorAll('.p24-story__layer');
    for (var i = 0; i < all.length; i++) {
      if (all[i].getAnimations) all[i].getAnimations().forEach(function (an) { an.cancel(); });
      if (all[i] !== layer) all[i].classList.remove('is-on', 'is-top');
    }
    if (win.getAnimations) win.getAnimations().forEach(function (an) { an.cancel(); });
    layer.classList.add('is-on');
    layer.style.clipPath = '';
    var area = win.parentElement || win;
    var l = parseFloat(layer.style.left) || 0, t = parseFloat(layer.style.top) || 0;
    var lw = parseFloat(layer.style.width) || 0, lh = parseFloat(layer.style.height) || 0;
    win.style.clipPath = 'inset(' + t + 'px ' + Math.max(0, area.clientWidth - l - lw) + 'px ' + Math.max(0, area.clientHeight - t - lh) + 'px ' + l + 'px)';
  }

  function name(el, n) {
    if (!el || !n) return;
    var prev = d.querySelectorAll('[data-vt-named]');
    for (var i = 0; i < prev.length; i++) {
      if (prev[i].style.viewTransitionName === n) { prev[i].style.viewTransitionName = ''; prev[i].removeAttribute('data-vt-named'); }
    }
    el.style.viewTransitionName = n;
    el.setAttribute('data-vt-named', '');
  }
  function clearAll() {
    var named = d.querySelectorAll('[data-vt-named]');
    for (var i = 0; i < named.length; i++) { named[i].style.viewTransitionName = ''; named[i].removeAttribute('data-vt-named'); }
  }

  d.addEventListener('click', function (e) {
    var a = e.target && e.target.closest ? e.target.closest('a[href]') : null;
    lastLink = a && a.hasAttribute('data-vt') ? a : null;
  }, true);

  w.addEventListener('pageswap', function (e) {
    var vt = e.viewTransition;
    try { w.sessionStorage.removeItem('p24-vt'); } catch (err) { /* storage off: pairs are skipped */ }
    if (!vt) return;
    try {
      clearAll();
      var link = lastLink;
      lastLink = null;
      var entry = e.activation && e.activation.entry;
      if (!link || !entry || link.href !== entry.url) return;
      var n = link.getAttribute('data-vt');
      if (!NAMES[n]) return;
      var src = sourceFor(link, n);
      if (!visible(src)) return;
      if (n === 'family-hero') showKeyFrame(link, src);
      name(src, n);
      w.sessionStorage.setItem('p24-vt', n);
      if (d.documentElement.classList.contains('qa')) {
        var r = src.getBoundingClientRect();
        w.sessionStorage.setItem('p24-vtlog', JSON.stringify({ name: n, source: src.tagName.toLowerCase() + '.' + String(src.className).split(' ')[0], rect: [Math.round(r.left), Math.round(r.top), Math.round(r.width), Math.round(r.height)], url: entry.url }));
      }
    } catch (err) {
      vt.skipTransition();
    }
  });

  w.addEventListener('pageshow', function (e) { if (e.persisted) { clearAll(); lastLink = null; } });

  P24._vt = {
    name: name,
    clear: clearAll,
    internalNav: function () { return d.documentElement.classList.contains('vt-nav'); },
    supported: typeof d.startViewTransition === 'function' && !!w.CSS && CSS.supports('view-transition-name: none')
  };
})(window, document);

(function (w, d) {
  'use strict';
  var h = d.documentElement;
  var body = d.body;
  var hasIO = 'IntersectionObserver' in w;
  function each(sel, fn) { Array.prototype.forEach.call(d.querySelectorAll(sel), fn); }

  var page = body.getAttribute('data-page');
  each('[data-nav]', function (a) {
    if (page && a.getAttribute('data-nav') === page) a.setAttribute('aria-current', 'page');
  });

  var menuBtn = d.querySelector('[data-menu-open]');
  var menu = d.getElementById('p24-menu');
  if (menuBtn && menu && typeof menu.showModal === 'function') {
    var closeBtn = menu.querySelector('[data-menu-close]');
    var setOpen = function (open) {
      if (open && !menu.open) menu.showModal();
      if (!open && menu.open) menu.close();
      menuBtn.setAttribute('aria-expanded', String(open));
    };
    menuBtn.addEventListener('click', function () { setOpen(true); });
    if (closeBtn) closeBtn.addEventListener('click', function () { setOpen(false); });
    menu.addEventListener('close', function () {
      menuBtn.setAttribute('aria-expanded', 'false');
      menuBtn.focus({ preventScroll: true });
    });
    menu.addEventListener('click', function (e) {
      var a = e.target.closest('a');
      if (a && a.getAttribute('href').charAt(0) === '#') setOpen(false);
    });
    var closedOnHide = false;
    var reset = function () {
      menuBtn.setAttribute('aria-expanded', 'false');
      menuBtn.textContent = 'Menu';
      if (menu.open) menu.close();
    };
    w.addEventListener('pagehide', function () { if (menu.open) { closedOnHide = true; reset(); } });
    w.addEventListener('pageshow', function (e) {
      if (!e.persisted) return;
      var was = closedOnHide || menu.open;
      closedOnHide = false;
      reset();
      if (was) menuBtn.focus({ preventScroll: true });
    });
    var mqWide = w.matchMedia('(min-width: 761px)');
    var onWide = function () { if (mqWide.matches) setOpen(false); };
    if (mqWide.addEventListener) mqWide.addEventListener('change', onWide);
  } else if (menuBtn) {
    menuBtn.addEventListener('click', function () { var f = d.getElementById('p24-footer-pages'); if (f) f.scrollIntoView(); });
  }

  var dock = d.querySelector('[data-dock]');
  if (dock && !body.hasAttribute('data-no-dock')) {
    var sentinels = d.querySelectorAll('[data-dock-sentinel]');
    var footerCta = d.querySelector('[data-footer-cta]');
    var state = { sentinel: sentinels.length > 0, footer: false, typing: false };
    d.addEventListener('p24:dock', function () { render(); });
    var links = dock.querySelectorAll('a, button');
    var render = function () {
      var show = !state.sentinel && !state.footer && !state.typing && !h.classList.contains('story-stuck');
      if (show) dock.setAttribute('data-show', ''); else dock.removeAttribute('data-show');
      h.classList.toggle('dock-on', show);
      dock.setAttribute('aria-hidden', String(!show));
      Array.prototype.forEach.call(links, function (l) { l.tabIndex = show ? 0 : -1; });
    };
    if (hasIO && sentinels.length) {
      var seen = new Set();
      var ioS = new IntersectionObserver(function (entries) {
        entries.forEach(function (e) {
          if (e.isIntersecting && e.intersectionRatio >= 0.99) seen.add(e.target); else seen.delete(e.target);
        });
        state.sentinel = seen.size > 0;
        render();
      }, { threshold: [0, 0.99, 1] });
      Array.prototype.forEach.call(sentinels, function (s) { ioS.observe(s); });
    }
    if (hasIO && footerCta) {
      new IntersectionObserver(function (entries) {
        state.footer = entries[0].isIntersecting;
        render();
      }).observe(footerCta);
    }
    d.addEventListener('focusin', function (e) {
      state.typing = !!(e.target.closest && e.target.closest('input, select, textarea'));
      render();
    });
    render();
  }

  each('[data-replay-opening]', function (a) {
    a.addEventListener('click', function (e) {
      if (e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
      e.preventDefault();
      if ('scrollRestoration' in w.history) w.history.scrollRestoration = 'manual';
      w.scrollTo(0, 0);
      w.location.reload();
    });
  });

  if (h.classList.contains('qa')) {
    var qaBox = d.createElement('pre');
    qaBox.className = 'p24-qa';
    qaBox.setAttribute('aria-hidden', 'true');
    var draw = function () {
      var P24 = w.P24 || {};
      var NL = String.fromCharCode(10);
      qaBox.textContent = 'P24 QA · ' + h.className + NL + (P24.vtLog || []).map(function (x) { return JSON.stringify(x); }).join(NL);
    };
    draw();
    body.appendChild(qaBox);
    setTimeout(draw, 1200);
  }
})(window, document);

(function (w, d) {
  'use strict';
  var P24 = w.P24 = w.P24 || {};
  var h = d.documentElement;
  var MANIFEST = 'media/manifest.json';
  var AUDIO_CHIP = '[AUDIO — AWAITING REVIEW]';
  var TRANSCRIPT_CHIP = '[TRANSCRIPT — TO BE PREPARED AND APPROVED]';
  var PREVIEW_DELAY_MS = 150;
  var PREVIEW_STOP_S = 4;
  var SLIDE_PX = 40;
  var READY_MS = 400;
  var CONTROLS_MS = 1500;

  var manifestPromise = null;
  var dlg = null;
  var ui = {};
  var current = null;
  var busy = false;
  var previewStops = [];
  var ctlTimer = 0;

  d.addEventListener('play', function (e) {
    var v = e.target;
    Array.prototype.forEach.call(d.querySelectorAll('video'), function (o) { if (o !== v && !o.paused) o.pause(); });
  }, true);

  function getManifest() {
    if (!manifestPromise) {
      manifestPromise = fetch(MANIFEST, { credentials: 'same-origin' })
        .then(function (r) { if (!r.ok) throw new Error('manifest ' + r.status); return r.json(); })
        .catch(function (err) { manifestPromise = null; throw err; });
    }
    return manifestPromise;
  }
  function clipList(m) { return Array.isArray(m.clips) ? m.clips : Object.keys(m.clips || {}).map(function (k) { return m.clips[k]; }); }
  function findClip(m, id) {
    var list = clipList(m);
    for (var i = 0; i < list.length; i++) if (list[i].id === id) return list[i];
    return null;
  }

  function mobile() { return w.matchMedia('(max-width: 760px)').matches; }
  function scrimAlpha() { return mobile() ? 1 : 0.96; }
  function motionOK() { return h.classList.contains('js-motion') && !!w.gsap; }
  function approved(c) { return /^approved\b/i.test(c.audioStatus || '') && !!c.srcAudio; }
  function lite() { var c = w.navigator.connection; return !!(c && (c.saveData || /^(slow-2g|2g|3g)$/.test(c.effectiveType || ''))); }

  function el(tag, cls, text) {
    var n = d.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  }
  function btn(cls, text) {
    var b = el('button', 'p24-player__ctl ' + (cls || ''), text);
    b.type = 'button';
    return b;
  }

  function groupName(trigger, opts) {
    if (opts && opts.group) return opts.group;
    var g = trigger.closest('[data-group]');
    return g ? g.getAttribute('data-group') : null;
  }
  function groupMembers(name) {
    if (!name) return [];
    var seen = {};
    var out = [];
    Array.prototype.forEach.call(d.querySelectorAll('[data-clip]'), function (t) {
      var gEl = t.closest('[data-group]');
      if (!gEl || gEl.getAttribute('data-group') !== name) return;
      var row = t.closest('li');
      if (row && !row.getClientRects().length) return;
      var id = t.getAttribute('data-clip');
      if (seen[id]) return;
      seen[id] = true;
      out.push(t);
    });
    return out;
  }

  function build() {
    if (dlg) return;
    dlg = el('dialog', 'p24-player');
    dlg.setAttribute('aria-labelledby', 'p24-player-title');

    var bar = el('div', 'p24-player__bar');
    ui.close = btn('p24-player__ctl--close', 'Close');
    ui.sound = el('span', 'p24-player__sound');
    ui.captions = btn('', 'Captions');
    ui.captions.setAttribute('aria-pressed', 'true');
    bar.appendChild(ui.close);
    bar.appendChild(ui.sound);
    bar.appendChild(ui.captions);

    var body = el('div', 'p24-player__body');
    ui.media = el('div', 'p24-player__media');
    ui.video = el('video');
    ui.video.muted = true;
    ui.video.setAttribute('muted', '');
    ui.video.playsInline = true;
    ui.video.setAttribute('playsinline', '');
    ui.video.controls = true;
    ui.video.preload = 'metadata';
    ui.video.setAttribute('controlslist', 'nodownload noplaybackrate noremoteplayback');
    ui.video.setAttribute('disablepictureinpicture', '');
    ui.track = el('track');
    ui.track.kind = 'captions';
    ui.track.srclang = 'en';
    ui.track.label = 'English';
    ui.video.appendChild(ui.track);
    ui.media.appendChild(ui.video);

    var meta = el('div', 'p24-player__meta');
    ui.title = el('h2', 'p24-player__title');
    ui.title.id = 'p24-player-title';
    ui.facts = el('dl', 'p24-player__facts');
    ui.notes = el('div', 'p24-player__notes');
    var cta = el('a', 'p24-link-arrow', 'Request availability →');
    cta.href = 'enquire.html#availability';
    cta.setAttribute('data-vt', 'cta-panel');
    meta.appendChild(ui.title);
    meta.appendChild(ui.facts);
    meta.appendChild(ui.notes);
    meta.appendChild(cta);

    ui.nav = el('div', 'p24-player__nav');
    ui.prev = btn('p24-player__step', '← Previous clip');
    ui.next = btn('p24-player__step', 'Next clip →');
    ui.nav.appendChild(ui.prev);
    ui.nav.appendChild(ui.next);
    meta.appendChild(ui.nav);

    body.appendChild(ui.media);
    body.appendChild(meta);
    dlg.appendChild(bar);
    dlg.appendChild(body);
    d.body.appendChild(dlg);

    ui.close.addEventListener('click', close);
    ui.prev.addEventListener('click', function () { step(-1); });
    ui.next.addEventListener('click', function () { step(1); });
    dlg.addEventListener('cancel', function (e) { e.preventDefault(); close(); });
    dlg.addEventListener('keydown', onKey);
    ui.captions.addEventListener('click', function () {
      var on = ui.captions.getAttribute('aria-pressed') !== 'true';
      ui.captions.setAttribute('aria-pressed', String(on));
      captionsMode(on);
    });
  }

  function onKey(e) {
    if (e.key !== 'ArrowLeft' && e.key !== 'ArrowRight') return;
    var a = d.activeElement;
    if (a && (/^(VIDEO|INPUT|SELECT|TEXTAREA)$/.test(a.tagName) || a.getAttribute('role') === 'slider')) return;
    if (!current || !current.group.length) return;
    e.preventDefault();
    step(e.key === 'ArrowLeft' ? -1 : 1);
  }

  function fact(label, value) {
    var row = el('div');
    row.appendChild(el('dt', null, label));
    row.appendChild(el('dd', null, value));
    return row;
  }

  function resetTrack(c) {
    var old = ui.track;
    if (old && old.track) old.track.mode = 'disabled';
    if (old && old.parentNode) old.parentNode.removeChild(old);
    ui.track = el('track');
    ui.track.kind = 'captions';
    ui.track.srclang = 'en';
    ui.track.label = 'English';
    ui.track.default = true;
    if (c.vtt) ui.track.src = c.vtt;
    ui.video.appendChild(ui.track);
  }
  function captionsMode(on) { if (ui.track && ui.track.track) ui.track.track.mode = on ? 'showing' : 'hidden'; }
  function controlsOff() {
    var v = ui.video;
    clearTimeout(ctlTimer);
    v.controls = false;
    v.addEventListener('playing', controlsOn, { once: true });
    ctlTimer = setTimeout(controlsOn, CONTROLS_MS);
  }
  function controlsOn() { clearTimeout(ctlTimer); if (ui.video) ui.video.controls = true; }
  function posterReady(c) {
    if (!c.poster || typeof Image === 'undefined') return Promise.resolve();
    var img = new Image();
    img.src = c.poster;
    var dec = img.decode ? img.decode().catch(function () { /* shows when it loads */ }) : Promise.resolve();
    return Promise.race([dec, new Promise(function (r) { setTimeout(r, READY_MS); })]);
  }

  function fill(c, animateTitle) {
    fillMeta(c, animateTitle);
    fillMedia(c);
  }
  function fillMeta(c, animateTitle) {
    var title = c.event || c.title || 'Clip';
    if (animateTitle && P24.ctx && P24.ctx.roll) P24.ctx.roll(ui.title, title);
    else ui.title.textContent = title;
    ui.facts.textContent = '';
    ui.facts.appendChild(fact('Client', c.client || 'Client not named'));
    if (c.place) ui.facts.appendChild(fact('Place', c.place));
    if (c.dateLabel || c.date) ui.facts.appendChild(fact('Date', c.dateLabel || c.date));

    ui.notes.textContent = '';
    if (/placeholder/i.test(c.captionsStatus || '') && c.hasAudio) ui.notes.appendChild(el('span', 'p24-ph', TRANSCRIPT_CHIP));

    ui.sound.textContent = '';
    if (approved(c)) {
      var s = btn('', 'Sound on');
      s.setAttribute('aria-pressed', 'false');
      s.addEventListener('click', function () { soundOn(c, s); });
      ui.sound.appendChild(s);
    } else if (c.hasAudio) {
      var dis = btn('', 'Sound on');
      dis.disabled = true;
      ui.sound.appendChild(dis);
      ui.sound.appendChild(d.createTextNode(' '));
      ui.sound.appendChild(el('span', 'p24-ph', AUDIO_CHIP));
    } else {
      ui.sound.appendChild(el('span', 'p24-player__nosound', 'No sound'));
    }

    ui.captions.hidden = !c.vtt;
  }
  function fillMedia(c) {
    var v = ui.video;
    controlsOff();
    v.poster = c.poster || '';
    if (c.w && c.h) { v.width = c.w; v.height = c.h; v.style.setProperty('--clip-w', c.w + 'px'); }
    v.setAttribute('aria-label', c.alt || c.posterAlt || '');
    resetTrack(c);
    v.src = c.src;
    if (c.inPoint) v.addEventListener('loadedmetadata', function () { try { v.currentTime = c.inPoint; } catch (e) { /* not seekable yet */ } }, { once: true });
    var capsOn = !/placeholder/i.test(c.captionsStatus || '');
    ui.captions.setAttribute('aria-pressed', String(capsOn));
    captionsMode(capsOn);
  }

  function soundOn(c, button) {
    var v = ui.video;
    var on = button.getAttribute('aria-pressed') !== 'true';
    var t = v.currentTime;
    v.src = on ? c.srcAudio : c.src;
    v.addEventListener('loadedmetadata', function () {
      try { v.currentTime = t; } catch (e) { /* not seekable yet */ }
      v.muted = !on;
      var p = v.play();
      if (p && p.catch) p.catch(function () { /* stays paused; the native controls remain */ });
    }, { once: true });
    button.setAttribute('aria-pressed', String(on));
    button.textContent = on ? 'Sound off' : 'Sound on';
  }

  function flipSource(trigger) {
    return trigger.closest('[data-flip-id]') || trigger.querySelector('[data-flip-id]') || trigger;
  }
  function play() {
    var p = ui.video.play();
    if (p && p.catch) p.catch(function () { controlsOn(); /* autoplay refused: the poster and native controls remain */ });
  }

  function updateNav(m) {
    var grp = current.group;
    var i = current.index;
    var show = grp.length > 1;
    ui.nav.hidden = !show;
    if (!show) return;
    var prevT = grp[(i - 1 + grp.length) % grp.length];
    var nextT = grp[(i + 1) % grp.length];
    var pc = findClip(m, prevT.getAttribute('data-clip'));
    var nc = findClip(m, nextT.getAttribute('data-clip'));
    ui.prev.setAttribute('aria-label', 'Previous clip: ' + (pc ? pc.event || pc.title || pc.id : ''));
    ui.next.setAttribute('aria-label', 'Next clip: ' + (nc ? nc.event || nc.title || nc.id : ''));
  }

  function step(dir) {
    if (!current || busy || current.group.length < 2) return;
    var grp = current.group;
    var i = (current.index + dir + grp.length) % grp.length;
    var trigger = grp[i];
    busy = true;
    getManifest().then(function (m) {
      var c = findClip(m, trigger.getAttribute('data-clip'));
      if (!c) { busy = false; return; }
      var g = w.gsap;
      var swap = function () {
        ui.video.pause();
        current.clip = c;
        current.trigger = trigger;
        current.returnFocus = null;
        current.source = flipSource(trigger);
        current.index = i;
        fill(c, motionOK());
        updateNav(m);
        play();
      };
      posterReady(c).then(function () {
        if (!current) { busy = false; return; }
        if (!motionOK()) { swap(); busy = false; return; }
        g.timeline({ onComplete: function () { busy = false; } })
          .to(ui.media, { x: -dir * SLIDE_PX, autoAlpha: 0, duration: 0.18, ease: 'power2.in' })
          .call(swap)
          .fromTo(ui.media, { x: dir * SLIDE_PX, autoAlpha: 0 }, { x: 0, autoAlpha: 1, duration: 0.27, ease: P24.ease ? P24.ease.inOut : 'power3.inOut', clearProps: 'transform,opacity,visibility' });
      });
    }, function () { busy = false; });
  }

  function show(c, trigger, m, grpName, opts) {
    build();
    previewStops.forEach(function (f) { f(); });
    var source = (opts && opts.flipFrom) || flipSource(trigger);
    var grp = groupMembers(grpName);
    var idx = -1;
    for (var k = 0; k < grp.length; k++) if (grp[k].getAttribute('data-clip') === c.id) idx = k;
    current = { clip: c, trigger: trigger, source: source, group: idx > -1 ? grp : [], index: Math.max(0, idx), returnFocus: (opts && opts.returnFocus) || null };
    fill(c, false);
    updateNav(m);
    ui.media.setAttribute('data-flip-id', source.getAttribute('data-flip-id') || ('clip-' + c.id));
    var g = w.gsap;

    if (motionOK() && w.Flip) {
      var state = w.Flip.getState(source);
      dlg.setAttribute('data-phase', 'opening');
      dlg.showModal();
      play();
      g.fromTo(dlg, { backgroundColor: 'rgba(252,251,249,0)' }, { backgroundColor: 'rgba(252,251,249,' + scrimAlpha() + ')', duration: 0.3, ease: 'power2.out' });
      w.Flip.from(state, {
        targets: ui.media,
        scale: true,
        duration: 0.6,
        ease: 'power3.inOut',
        onComplete: function () { dlg.setAttribute('data-phase', 'open'); busy = false; }
      });
      return;
    }
    dlg.setAttribute('data-phase', 'open');
    dlg.showModal();
    play();
    if (g) g.fromTo(dlg, { opacity: 0 }, { opacity: 1, duration: 0.15, ease: 'none', clearProps: 'opacity', onComplete: function () { busy = false; } });
    else busy = false;
  }

  function open(trigger, opts) {
    if (!trigger || busy || (dlg && dlg.open)) return Promise.resolve(false);
    var id = (opts && opts.clip) || trigger.getAttribute('data-clip');
    if (!id) return Promise.resolve(false);
    busy = true;
    var needFlip = motionOK() && !w.Flip;
    return Promise.all([getManifest(), needFlip ? P24.loadFlip().catch(function () { return null; }) : null])
      .then(function (res) {
        var c = findClip(res[0], id);
        if (!c) throw new Error('No clip "' + id + '" in ' + MANIFEST);
        show(c, trigger, res[0], groupName(trigger, opts), opts);
        return true;
      })
      .catch(function (err) {
        busy = false;
        if (trigger.href) w.location.href = trigger.href;
        setTimeout(function () { throw err; }, 0);
        return false;
      });
  }

  function finishClose() {
    var c = current;
    dlg.close();
    dlg.removeAttribute('data-phase');
    if (w.gsap) w.gsap.set([ui.media, dlg], { clearProps: 'all' });
    ui.video.pause();
    ui.video.removeAttribute('src');
    ui.video.load();
    controlsOn();
    current = null;
    busy = false;
    var back = c && (c.returnFocus && c.returnFocus.isConnected ? c.returnFocus : c.trigger);
    if (back && back.isConnected) back.focus({ preventScroll: true });
  }

  function close() {
    if (!dlg || !dlg.open || !current || busy) return;
    busy = true;
    ui.video.pause();
    clearTimeout(ctlTimer);
    ui.video.controls = false;
    ui.video.removeAttribute('src');
    ui.video.load();
    var g = w.gsap;
    var src = current.source;
    var r = src && src.isConnected ? src.getBoundingClientRect() : null;
    var onScreen = r && r.width > 0 && r.bottom > 0 && r.top < w.innerHeight;
    if (motionOK() && w.Flip && onScreen) {
      dlg.setAttribute('data-phase', 'opening');
      g.to(dlg, { backgroundColor: 'rgba(252,251,249,0)', duration: 0.45, ease: 'power2.out' });
      w.Flip.fit(ui.media, src, { scale: true, duration: 0.45, ease: 'power3.inOut', onComplete: finishClose });
      return;
    }
    if (g) g.to(dlg, { opacity: 0, duration: 0.15, ease: 'none', onComplete: finishClose });
    else finishClose();
  }

  function rail(video, list) {
    if (!video || !list) return function () {};
    var items = Array.prototype.slice.call(list.querySelectorAll('[data-in]'));
    var active = null;
    var label = el('span', 'p24-rail__now', 'Now showing');
    items.forEach(function (it) {
      if (!it.querySelector('.p24-rail__bar')) {
        var b = el('span', 'p24-rail__bar');
        b.setAttribute('aria-hidden', 'true');
        it.appendChild(b);
      }
    });
    function range(it) { return [parseFloat(it.getAttribute('data-in')) || 0, parseFloat(it.getAttribute('data-out')) || 0]; }
    function barOf(it) { return it.querySelector('.p24-rail__bar'); }
    function jump(it, p) {
      var b = barOf(it);
      b.style.transition = 'none';
      b.style.transform = 'scaleX(' + p + ')';
      void b.offsetWidth;
      b.style.transition = '';
    }
    function setActive(it) {
      if (active === it) return;
      if (active) { active.removeAttribute('aria-current'); jump(active, 0); }
      active = it;
      if (!it) { if (label.parentNode) label.remove(); return; }
      it.setAttribute('aria-current', 'true');
      (it.querySelector('[data-rail-label]') || it).appendChild(label);
      var r = range(it);
      jump(it, Math.max(0, Math.min(1, (video.currentTime - r[0]) / Math.max(0.1, r[1] - r[0]))));
    }
    function onTime() {
      var t = video.currentTime;
      var hit = null;
      items.forEach(function (it) { var r = range(it); if (t >= r[0] && t < r[1]) hit = it; });
      setActive(hit);
      if (!hit) return;
      var r = range(hit);
      barOf(hit).style.transform = 'scaleX(' + Math.max(0, Math.min(1, (t - r[0]) / Math.max(0.1, r[1] - r[0]))) + ')';
    }
    function onSeek() { if (active) { var r = range(active); jump(active, Math.max(0, Math.min(1, (video.currentTime - r[0]) / Math.max(0.1, r[1] - r[0])))); } onTime(); }
    function onClick(e) {
      var it = e.target.closest('[data-in]');
      if (!it || !list.contains(it) || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
      e.preventDefault();
      var r = range(it);
      try { video.currentTime = r[0] + 0.01; } catch (err) { /* not seekable yet */ }
      setActive(it);
      var p = video.play();
      if (p && p.catch) p.catch(function () { /* stays paused */ });
    }
    video.addEventListener('timeupdate', onTime);
    video.addEventListener('seeking', onSeek);
    list.addEventListener('click', onClick);
    return function () {
      video.removeEventListener('timeupdate', onTime);
      video.removeEventListener('seeking', onSeek);
      list.removeEventListener('click', onClick);
      setActive(null);
    };
  }

  function hoverPreview(root, opts) {
    var sel = (opts && opts.selector) || '[data-clip]';
    if (!root || !motionOK() || lite() || !w.matchMedia('(hover: hover) and (pointer: fine)').matches) return function () {};
    var timer = 0;
    var token = 0;
    var pending = null;
    var live = null;
    function stop() {
      clearTimeout(timer);
      pending = null;
      token++;
      if (!live) return;
      var v = live.video;
      live = null;
      if (!v) return;
      v.pause();
      v.removeAttribute('src');
      v.load();
      v.remove();
    }
    function start(card) {
      stop();
      var mine = token;
      var frame = card.querySelector('[data-flip-id]') || card.closest('[data-flip-id]') || card;
      var src = card.getAttribute('data-preview-src') || (/\.mp4(#.*)?$/.test(card.getAttribute('href') || '') ? card.getAttribute('href') : null);
      var ended = function (v) {
        if (!live || live.video !== v) return;
        stop();
        live = { card: card, video: null };
      };
      var go = function (url, from) {
        if (!url) return;
        var v = el('video', 'p24-preview');
        v.muted = true;
        v.playsInline = true;
        v.setAttribute('muted', '');
        v.setAttribute('playsinline', '');
        v.setAttribute('aria-hidden', 'true');
        v.preload = 'auto';
        v.addEventListener('loadedmetadata', function () {
          if (from > 0) { try { v.currentTime = from; } catch (e) { /* not seekable: plays from 0 */ } }
        }, { once: true });
        v.addEventListener('canplay', function () {
          if (!live || live.video !== v) return;
          v.classList.add('is-on');
          var p = v.play();
          if (p && p.catch) p.catch(function () { /* stays on the poster */ });
        }, { once: true });
        v.addEventListener('timeupdate', function () { if (v.currentTime >= (from || 0) + PREVIEW_STOP_S) ended(v); });
        v.addEventListener('ended', function () { ended(v); });
        v.src = url.split('#')[0];
        frame.appendChild(v);
        live = { card: card, video: v };
      };
      var attrIn = parseFloat(card.getAttribute('data-preview-in'));
      if (src && !isNaN(attrIn)) { go(src, attrIn); return; }
      getManifest().then(function (m) {
        var c = findClip(m, card.getAttribute('data-clip'));
        if (mine !== token) return;
        var from = !isNaN(attrIn) ? attrIn : (c && (c.previewIn || c.inPoint)) || 0;
        go(src || (c && c.src), from);
      }, function () { if (src && mine === token) go(src, 0); });
    }
    function onEnter(e) {
      var card = e.target.closest && e.target.closest(sel);
      if (!card || !root.contains(card) || e.pointerType !== 'mouse') return;
      if ((live && live.card === card) || pending === card) return;
      clearTimeout(timer);
      pending = card;
      timer = setTimeout(function () { pending = null; start(card); }, PREVIEW_DELAY_MS);
    }
    function onLeave(e) {
      var card = e.target.closest && e.target.closest(sel);
      if (!card) return;
      if (e.relatedTarget && card.contains(e.relatedTarget)) return;
      stop();
    }
    root.addEventListener('pointerover', onEnter);
    root.addEventListener('pointerout', onLeave);
    previewStops.push(stop);
    return function () {
      previewStops = previewStops.filter(function (f) { return f !== stop; });
      root.removeEventListener('pointerover', onEnter);
      root.removeEventListener('pointerout', onLeave);
      stop();
    };
  }

  d.addEventListener('click', function (e) {
    var t = e.target.closest && e.target.closest('a[data-clip], button[data-clip]');
    if (!t || e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey) return;
    e.preventDefault();
    open(t);
  });
  var warmed = false;
  function warm(e) {
    if (warmed || !e.target.closest || !e.target.closest('[data-clip]')) return;
    warmed = true;
    getManifest().catch(function () { /* retried on open */ });
    if (motionOK()) P24.loadFlip().catch(function () { /* open() falls back to a fade */ });
  }
  d.addEventListener('pointerover', warm, { passive: true });
  d.addEventListener('focusin', warm);
  d.addEventListener('touchstart', warm, { passive: true });

  var api = {
    open: open,
    close: close,
    isOpen: function () { return !!(dlg && dlg.open); },
    manifest: getManifest,
    rail: rail,
    hoverPreview: hoverPreview
  };
  P24.player = api;
  if (P24.component) P24.component('player', function () { return api; });
})(window, document);

(function (w, d) {
  'use strict';
  var P24 = w.P24;
  if (!P24 || typeof P24.register !== 'function') return;

  var STAGGER = 0.09;
  var DECODE_WAIT_MS = 500;

  function all(root, sel) { return Array.prototype.slice.call(root.querySelectorAll(sel)); }
  function range(it) { return [parseFloat(it.getAttribute('data-in')) || 0, parseFloat(it.getAttribute('data-out')) || 0]; }

  function revealGrid(ctx, grid) {
    var g = ctx.gsap;
    var frames = all(grid, '.watch-card__frame');
    var imgs = frames.map(function (f) { return f.querySelector('img'); }).filter(Boolean);
    if (!frames.length) return;
    var state = 'idle';
    ctx.enter(grid, {
      rootMargin: '0px 0px -12% 0px',
      prepare: function () {
        state = 'prepared';
        g.set(frames, { clipPath: 'inset(100% 0% 0% 0%)' });
        g.set(imgs, { scale: 1.06 });
      },
      play: function () {
        ctx.decodeAll(imgs, DECODE_WAIT_MS).then(function () {
          if (state !== 'prepared') return;
          state = 'playing';
          var dur = ctx.dur(0.8);
          g.to(frames, { clipPath: 'inset(0% 0% 0% 0%)', duration: dur, ease: ctx.ease.out, stagger: STAGGER, clearProps: 'clipPath' });
          g.to(imgs, { scale: 1, duration: dur, ease: ctx.ease.out, stagger: STAGGER, clearProps: 'transform' });
        });
      },
      final: function () {
        state = 'done';
        g.set(frames, { clearProps: 'clipPath' });
        g.set(imgs, { clearProps: 'transform' });
      }
    });
  }

  function sequence(ctx, root) {
    var video = root.querySelector('[data-watch-video]');
    var list = root.querySelector('[data-watch-rail]');
    var frame = root.querySelector('.watch-seq__frame');
    var playBtn = root.querySelector('[data-watch-play]');
    var l1 = root.querySelector('[data-watch-l1]');
    var l2 = root.querySelector('[data-watch-l2]');
    var full = root.querySelector('[data-watch-full]');
    if (!video || !list || !frame) return null;

    var items = all(list, '[data-in]');
    var rest = { l1: l1.textContent, l2: l2.textContent };
    var current = null;
    var offs = [];

    if (ctx.player && typeof ctx.player.rail === 'function') {
      var offRail = ctx.player.rail(video, list);
      if (typeof offRail === 'function') offs.push(offRail);
      else if (offRail && offRail.then) offRail.then(function (f) { if (typeof f === 'function') offs.push(f); }, function () { /* the rows stay #t= links */ });
    }

    function chapterAt(t) {
      for (var i = 0; i < items.length; i++) { var r = range(items[i]); if (t >= r[0] && t < r[1]) return items[i]; }
      return null;
    }
    function show(it) {
      if (it === current) return;
      current = it;
      if (!it) {
        ctx.roll(l1, rest.l1);
        ctx.roll(l2, rest.l2);
        full.hidden = true;
        return;
      }
      ctx.roll(l1, it.getAttribute('data-l1'));
      ctx.roll(l2, it.getAttribute('data-l2'));
      var id = it.getAttribute('data-full');
      var card = id ? d.querySelector('[data-group] a[data-clip="' + id + '"]') : null;
      full.hidden = !card;
      if (card) { full.href = '#clip-' + id; full.setAttribute('data-target', id); }
    }
    function onTime() { if (!video.paused || video.seeking) show(chapterAt(video.currentTime)); }
    function onSeeked() { show(chapterAt(video.currentTime)); }
    function onPlay() { frame.setAttribute('data-playing', ''); if (!video.controls) video.controls = true; }
    function onEnded() { frame.removeAttribute('data-playing'); show(null); }
    function onPlayBtn() {
      var p = video.play();
      if (p && p.catch) p.catch(function () { video.controls = true; /* stays on the poster, with the native controls */ });
    }
    function onRow(e) {
      if (!e.target.closest('[data-in]')) return;
      var r = video.getBoundingClientRect();
      var vh = w.innerHeight || d.documentElement.clientHeight;
      if (r.top < 0 || r.bottom > vh) video.scrollIntoView({ behavior: ctx.motionOK ? 'smooth' : 'auto', block: 'nearest' });
    }
    function onFull(e) {
      var id = full.getAttribute('data-target');
      var card = id ? d.querySelector('[data-group] a[data-clip="' + id + '"]') : null;
      if (!card || !ctx.player || typeof ctx.player.open !== 'function') return;
      e.preventDefault();
      video.pause();
      var group = card.closest('[data-group]').getAttribute('data-group');
      ctx.player.open(card, { clip: id, group: group, flipFrom: frame, returnFocus: full });
    }

    var hadControls = video.hasAttribute('controls');
    if (video.paused) video.controls = false;
    frame.setAttribute('data-ready', '');
    video.addEventListener('timeupdate', onTime);
    video.addEventListener('seeked', onSeeked);
    video.addEventListener('play', onPlay);
    video.addEventListener('ended', onEnded);
    if (playBtn) playBtn.addEventListener('click', onPlayBtn);
    list.addEventListener('click', onRow);
    full.addEventListener('click', onFull);

    return function () {
      offs.forEach(function (f) { f(); });
      video.removeEventListener('timeupdate', onTime);
      video.removeEventListener('seeked', onSeeked);
      video.removeEventListener('play', onPlay);
      video.removeEventListener('ended', onEnded);
      if (playBtn) playBtn.removeEventListener('click', onPlayBtn);
      list.removeEventListener('click', onRow);
      full.removeEventListener('click', onFull);
      frame.removeAttribute('data-ready');
      if (hadControls) video.controls = true;
      current = null;
    };
  }

  P24.register('watch', {
    init: function (ctx) {
      var root = d.getElementById('watch-top');
      if (!root) return undefined;
      var main = d.getElementById('main') || d.body;
      var cleanups = [];

      ctx.heading(root.querySelector('[data-page-title]'), { now: true });
      all(main, '[data-watch-h2]').forEach(function (h) { ctx.heading(h); });

      var seqOff = sequence(ctx, root);
      if (seqOff) cleanups.push(seqOff);

      if (ctx.motionOK && ctx.gsap) all(main, '[data-watch-grid]').forEach(function (grid) { revealGrid(ctx, grid); });

      if (ctx.player && typeof ctx.player.hoverPreview === 'function') {
        var offPrev = ctx.player.hoverPreview(main, { selector: '.watch-card__frame:not([data-preview="off"])' });
        if (typeof offPrev === 'function') cleanups.push(offPrev);
      }

      return function () { cleanups.forEach(function (f) { f(); }); };
    }
  });
})(window, document);
